### ISSUE TITLE
ProjectFile.getDefaultCalendar().getWorkWeeks() not work?

### ISSUE THREAD

**Issue by dargonwanglong** [joniles/mpxj#100]
I am using MPXJ 7.8.1 to read MS Project file(.mpp). I created a new calendar via copy "24 Hours" as following:
<img width="757" alt="Screen Shot 2019-05-15 at 12 04 57 PM" src="https://user-images.githubusercontent.com/16732869/57748174-5f604100-770b-11e9-8efa-05ac4d151e28.png">

When I use ProjectFile.getDefaultCalendar().getWorkWeeks() to get the workweeks, it returns nothing.
```
    ...
    UniversalProjectReader reader = new UniversalProjectReader()
    ProjectFile projectFile = reader.read(stream)
    ProjectProperties projectProperties = projectFile.getProjectProperties()
    def calendar = projectFile.getDefaultCalendar()
    calendar.getName() + ': ' + calendar.getWorkWeeks()
    
    Output: My Calendar: []
```

**Comment by joniles** [comment]
I think what's happening here is that MS Project doesn't store anything when the calendar only has the default working week. Basically this is saying that the default working day pattern and start and end times for each day is the same regardless of the date. When you add a new working week, you'll see that MPXJ picks this up.
