### ISSUE TITLE
Cannot read custom fields sometimes

### ISSUE THREAD

**Issue by marci32** [joniles/mpxj#101]
Sometimes custom fields (mostly populated with lookup tables) are missing when we are reading them from mpp files. (Maybe this was a related issue, but we still have something like this:  #38 )

Finally we have some mpps ([mpps.zip](https://github.com/joniles/mpxj/files/3187068/mpps.zip)) to share which contain the following issue:
The 11. task (unique id: 14) in the original mpp (**QualityReportTestGIVE**) has a value in TaskField Text8.
I deleted the value and saved it as **QualityReportTestGIVE_2**.
Reading the **first version** there is no problem (all values are fine). However, reading the **second one**, Text8 is missing from **other** tasks as well (unique id: 16 and 15), **not just from the one that I modified**.
Other interesting fact: when I open the **second version** in MSP 2013 and save it again (as **QualityReportTestGIVE_3**) without any modification, then reading the **third version**, Text8 is OK in other tasks and missing only from the earlier modified task which would be the expected behavior with the second version as well.

Currently used MPXJ version in Java: 7.6.3 (but we had the same experience with earlier versions)

Could it be fixed somehow?
Please let me know if you need further information.

**Comment by joniles** [comment]
Just to let you know, I think I have a fix for this. I need to do some more testing but I'm hoping to have something in place early next week.

**Comment by joniles** [comment]
I believe that the code now in git fixes this issue.
