### ISSUE TITLE
Dates of tasks are incorrect

### ISSUE THREAD

**Issue by harishgirishankar** [joniles/mpxj#103]
Hello,
We've discovered a really strange bug where the dates are being imported incorrectly from a Microsoft Project file. Initially, we thought it might a problem with the frontend library, but I can confirm that the dates are being read incorrectly on import. 

I've attached some screenshots of the dates in Microsoft Project, and the dates reported in our software after import. I'll be happy to send the file to an email if you need it.

Cheers!
  
![dates_in_project_file](https://user-images.githubusercontent.com/15919559/58066493-b9a84880-7bc8-11e9-95c8-dc2faeb8aac9.png)
![dates_reported](https://user-images.githubusercontent.com/15919559/58066494-b9a84880-7bc8-11e9-99df-abc568f71f23.png)

**Comment by joniles** [comment]
Could you let me have a copy of the file? Thanks!

**Comment by harishgirishankar** [comment]
I've sent the file to your email.

**Comment by joniles** [comment]
Thank you, I will take a look as soon as I can.

**Comment by joniles** [comment]
I'm going to close this issue as I haven't received any further details.
