### ISSUE TITLE
Activity codes are not being returned

### ISSUE THREAD

**Issue by alatui** [joniles/mpxj#104]
Hi Jon Iles,

First of all, thanks for your great work building this lib.

I've got a problem reading the Activity Codes(http://www.mpxj.org/apidocs/net/sf/mpxj/Task.html#getActivityCodes--) from a xer file I'm exporting out from P6. The activity codes for all tasks are always coming up as an empty list even though I have activities assigned.

 Please find below the xer file I'm playing with:
[test.xer.zip](https://github.com/joniles/mpxj/files/3212135/test.xer.zip)

**Comment by joniles** [comment]
Hi, I think the code I've just committed fixes this issue, let me know if you still have issues once you have a chance to try it!
