### ISSUE TITLE
Same TaskField is mapped to different FIELD_ARRAY-indices in MPPTaskField14.java

### ISSUE THREAD

**Issue by rendner** [joniles/mpxj#113]
Hi Jon,

I'm unsure if this could be a problem or not, at least it looks like this could be a problem.
The following TaskField's are defined twice:
- TaskField.SCHEDULED_START
- TaskField.SCHEDULED_FINISH
- TaskField.SCHEDULED_DURATION

the first time:
https://github.com/joniles/mpxj/blob/bc607649e6b9b9bc72aa5d74d87caad7daa3b097/src/main/java/net/sf/mpxj/common/MPPTaskField14.java#L606-L608

the second time:
https://github.com/joniles/mpxj/blob/6416471b9f53658c241c4e1215eb48e1d38cf881/src/main/java/net/sf/mpxj/common/MPPTaskField14.java#L996-L998

**Comment by joniles** [comment]
Hi @rendner thanks for the note. The duplication occurs as I've seen these values in MPP files identified by both the first and second set of indexes. This is probably a symptom of me not understanding enough of how data is represented in MPP14 files, but this does allow us to read these values from different forms of MPP14 file. It would be a problem if I had mapped different fields to the same array index!
