### ISSUE TITLE
Leveling Duration Format displays variations on the mpxj test files.

### ISSUE THREAD

**Issue by testing-things-111** [joniles/mpxj#116]
In most files Leveling format is "8" after reading .mpp files from the mpxj pool the format becomes "10".

**Comment by joniles** [comment]
Could you attach some MPP file which illustrate the problem, with some notes on the expected values, and the values you receive when read using MPXJ? Thanks!

**Comment by testing-things-111** [comment]
Nearly all .mpp files are affected (7.9.2).

[files.zip](https://github.com/joniles/mpxj/files/3533510/files.zip)

**Comment by testing-things-111** [comment]
"8" -> "10" in most cases. This can be verified by saving the file with MSP to .xml and are read using MPXJ. This issue was not present in 7.9.1.

**Comment by testing-things-111** [comment]
The issue concerns only .mpp files. I do not know if mspdi files are affected as I do not read them.

**Comment by joniles** [comment]
Apologies, I'm struggling slightly to understand the issue. Can you provide some notes on exactly which attribute you are looking at (I'm guessing it's `Task.getLevelingDelayUnits()`?) what values you are expecting for a specific task in a particular file, and what you're seeing when you read the data using MPXJ. I'm very keen to help - just not sure what I'm looking for - thanks!

**Comment by testing-things-111** [comment]
Hello Jon,

I am enclosing a set of files, which show the issue clearly - 7.9.2.zip, which contains the original .mpp files,
for each of which two .xml files are included: (i) one produced by MSP; and (ii) one generated from mpxj mpp reader data. Nearly all
.mpp files from the mpxj set of files show the same behavior as the files enclosed, i.e. LevelingGanttFormat value is changed.
For simplicity, I have included only the tasks sections of the .xml files (winmerge xyz.xml mpxj/xyz.xml).

I use c# and the Task getter for levelingganttformat is not available. The code used is roughly as follows:

                LevelingDelayFormat =
                    (T.LevelingDelayFormat == null)
                    ? DefaultLevelingDelayFormat // null case
                    : T.LevelingDelayFormat.Mpxj_ToMsLevelingDelayFormat(); // extension

This has worked since ever (e.g. since mpxj 6.x.x or earlier).

P.S. Sorry about the previous scatterred descriptions, but I am new and not quite used to github.

[7.9.2.zip](https://github.com/joniles/mpxj/files/3587864/7.9.2.zip)

**Comment by joniles** [comment]
I must admit that I'm still somewhat confused, however I did take a closer look at this area of the code and found that there was definitely a situation when writing an MSPDI file where we'd discard the leveling delay format, which could cause you problem later if you re-read the file.

I'm not sure if this is the issue you are encountering, however the changes I've made have been merged, and will form part of the next release. If this doesn't solve your problem we can try again... I will need step-by-step instructions in order to reproduce though!

**Comment by testing-things-111** [comment]
Hello Jon,

Thank you for your response.

As requested here is the step by step:

1. Lets assume we have a file abc.mpp
2. Open abc.mpp with MSP (version in this case is irrelevant, i use 2016).
3. Convert the file with MSP to abc.xml
4. Now open abc.mpp with MPXJ.
5. and use this sort of pseudo code:
	foreach (task in Tasks)
	{
	    Write(task.UniqueID);
	    WriteLine(task.LevelingGanttFormat);
	}
6. Compare the values for each task's LevelingGanttFormat, and you'll see the values changed from 8 to 10

Please note that MPXJ's mspdi does not come into play. May be the problem is in (i) a conversion table (sorry I am totally useless with Java code);
(ii) changes in 7.9.2 may have affected the value of task.LevelingGanttFormat, for example, mix up with the format from task.LevelingDelay.
I have not been able to ascertain either.

I hope your fix solves the problem. Thank you.

**Comment by joniles** [comment]
Thanks for the update, that was very helpful. Can you confirm how you have implemented `LevelingGanttFormat` as this is not an attribute exposed by MPXJ's `Task` class.

**Comment by testing-things-111** [comment]
Your fix works. Thank you.
My mistake: LevelingGanttFormat should read **LevelingDelayFormat**.
