### ISSUE TITLE
Tests for reading MPP files

### ISSUE THREAD

**Issue by dampir** [joniles/mpxj#117]
@joniles How you are testing reading of MPP files? Do you have some repository with mpp samples which is used to check mpjx reading?

**Comment by joniles** [comment]
I do have a set of MPP files which I have been given to me in the past to help debug problems. These mainly contain real world data, hence they are not something I can share. I run regression tests using this data to validate that when I make changes to MPXJ that they can still be read, and still produce the expected results.

I also started working on some rudimentary test data generation (https://github.com/joniles/mpxj/blob/master/junit/GenerateTestData.bas). If I had all the time in the world(!) I'd expand this so we could validate that every attribute is read correctly from files produced by every MS Project version.
