### ISSUE TITLE
Add multiple front-end tasks to a task, but when project is opened, the front-end task is not displayed

### ISSUE THREAD

**Issue by heisdot** [joniles/mpxj#119]
Add multiple front-end tasks to a task, but when project is opened, the front-end task is not displayed, and it is successful if only one front-end task is added.
```
if (CollectionUtils.isNotEmpty(list)) {
          for (PredecessorVO predecessorVO : list) {
                 net.sf.mpxj.Task target = getMpxTaskByUniqueId(mpxTasks, predecessorVO.getTargetTask());

                 Duration lag = Duration.getInstance(predecessorVO.getLag().getDuration(),
                                predecessorVO.getLag().getUnits());
                 mpxTask.addPredecessor(target, predecessorVO.getType(), lag);
          }
}
```

**Comment by joniles** [comment]
Hello! thanks for the note. Can you provide a sample file which you have generated using MPXJ which shows the problem? Thanks!

**Comment by heisdot** [comment]
it's lucky to receive your reply. Below is my file. The exported file is in MPX format

**Comment by heisdot** [comment]
> Hello! thanks for the note. Can you provide a sample file which you have generated using MPXJ which shows the problem? Thanks!

**Comment by heisdot** [comment]
[single.zip](https://github.com/joniles/mpxj/files/3646673/single.zip)

**Comment by heisdot** [comment]
it's lucky to receive your reply. Below is my file. The exported file is in MPX format
[single.zip](https://github.com/joniles/mpxj/files/3646681/single.zip)

**Comment by joniles** [comment]
Thank you for the files. Can you give me a specific example of something in that MPX file which is not what you are expecting to see?

**Comment by joniles** [comment]
I'm going to close this issue as I haven't received a response.
