### ISSUE TITLE
Elapsed Days to Days Duration Conversion Incorrect

### ISSUE THREAD

**Issue by rsinha9** [joniles/mpxj#120]
The conversion from elapsed days to days is incorrect, first the minutes are calculated based on a 24 hour clock and then the conversion back is done based on minutes per day which is hardcoded to assume that there are 8 hour days.

Example:
If you have 1ed it is first converted to 1440 minutes and then when it's converted back with the 8 hour day it's converted to 3d.

**Comment by joniles** [comment]
Hi, thanks for the note. Can you provide an example of where this is happening?

**Comment by rsinha9** [comment]
Hi @joniles, yes attached is a mpp file that has a task with a duration of 10ed, when you grab the duration and convert it to Days you get 30ed, because it's 10 * 24 * 60 = 14400 minutes, 14400 / 480 = 30.
`public class ElapsedDaysTest {

	@Test
	public void testIncorrectElapsedDaysToDays() throws FileNotFoundException, MPXJException, URISyntaxException {
		MPPReader reader = new MPPReader();
		ProjectFile file = reader.read(loadResource("Elapsed Days.mpp"));
		Task firstTask = file.getTasks().getByID(1);

		assertThat(firstTask.getDuration().getUnits()).isEqualTo(TimeUnit.ELAPSED_DAYS);
		Duration convertedDuration = firstTask.getDuration().convertUnits(TimeUnit.DAYS, file.getProjectProperties());
		assertThat(convertedDuration.getUnits()).isEqualTo(TimeUnit.DAYS);
		assertThat(convertedDuration.getDuration()).isEqualTo(6D);
	}
	
	public static FileInputStream loadResource(String path) throws URISyntaxException, FileNotFoundException {
		ClassLoader classLoader = ElapsedDaysTest.class.getClassLoader();
		URL resource = classLoader.getResource(path);
		URI uri = new URI(resource.toString());
		File mppFile = new File(uri.getPath());
		
		return new FileInputStream(mppFile);
	}

}`
[Elapsed Days.zip](https://github.com/joniles/mpxj/files/3659116/Elapsed.Days.zip)

**Comment by joniles** [comment]
Thanks for the test case. I think the issue is the one noted in the comment on the `convertUnits` method:

```
    * This method provides an <i>approximate</i> conversion between duration
    * units. It does take into account the project defaults for number of hours
    * in a day and a week, but it does not take account of calendar details.
    * The results obtained from it should therefore be treated with caution.
```

The only way to correctly convert an elapsed days duration is to use the `getEffectiveCalendar` method of the task to retrieve a calendar, then use the `getDuration` method of the calendar to calculate the number of working days between the start and finish date of the task
