### ISSUE TITLE
mpxj from web app  - access control errors

### ISSUE THREAD

**Issue by timscorbett** [joniles/mpxj#127]
The following works fine from a console app but fails on a backend web
application in C#. Is there a workaround?

prj =  m_reader.read( xer);

An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.
net.sf.mpxj.reader.UniversalProjectReader.read(File file)

**Comment by ndarlington** [comment]
I'd say it looks like a gap between IKVM and .net core: dotnet/corefx#39920

Are you able to use another .net target in the 4.x range?  IKVM is good but not maintained so I wouldn't expect to see an implementation of it becoming .netcore compatible in the foreseeable future.

Refs:
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-3.0

**Comment by joniles** [comment]
I'm going to close this for now as I think @ndarlington's answer covered everything. There is a glimmer of hope on the horizon for .net core as [this project](https://github.com/ikvm-revived/ikvm) is active in bringing the IKVM code up-to-date.

**Comment by joniles** [comment]
Quick update: MPXJ 10.0.0 has been released which includes support for .NET Core.
