### ISSUE TITLE
Export to MSPDI File,Custom fields cannot be added.

### ISSUE THREAD

**Issue by stonecrazy666** [joniles/mpxj#129]
Custom fields cannot be added，Where is the problem? My code is as follows:
`net.sf.mpxj.ProjectFile projectFile = new net.sf.mpxj.ProjectFile();
                net.sf.mpxj.mpp.CustomFieldValueItem customFieldValueItem = new net.sf.mpxj.mpp.CustomFieldValueItem(new java.lang.Integer(1));
                customFieldValueItem.Description = "TestTaskAutoId";
                customFieldValueItem.Guid = java.util.UUID.randomUUID();
                customFieldValueItem.Value = "TestTaskAutoId";
                customFieldValueItem.Type = net.sf.mpxj.CustomFieldValueDataType.TEXT;

                net.sf.mpxj.CustomFieldContainer customFieldContainer = new net.sf.mpxj.CustomFieldContainer();
                customFieldContainer.RegisterValue(customFieldValueItem);

                net.sf.mpxj.CustomField customField = new net.sf.mpxj.CustomField(net.sf.mpxj.TaskField.TEXT1, customFieldContainer);
                customField.Alias = "TestTaskAutoId";

                projectFile.CustomFields.RegisterValue(customFieldValueItem);`

**Comment by joniles** [comment]
Hi, I've just merged the code to support writing outline codes/custom fields lookup tables to MSPDI files.
