### ISSUE TITLE
Option to completely reload a project file

### ISSUE THREAD

**Issue by ceds** [joniles/mpxj#133]
I have a plugin system that loads assemblies from .dll files.  One of the plugins make use of mpxj library.  As you know, you cannot unload an assembly once loaded, and what's happening is the plugin loads the .mpp file, but when it needs to load the file again in the future it uses the exact same .mpp data as the original load (does not reload the file).  How can I force mpxj to reload the .mpp file?

**Comment by joniles** [comment]
The `UniversalProjectReader` identifies the schedule type and creates a new instance of the necessary reader class each time it is used, so you should be able to use this to repeatedly load data from a file - the file will be read again each time you do this.

**Comment by joniles** [comment]
I'm going to close this issue as I haven't received any further feedback - do let me know if there is anything else related to this I can help with.
