### ISSUE TITLE
I converted the MPP file to an XML file, but the customfieldvalueitem is missing

### ISSUE THREAD

**Issue by yuanhca** [joniles/mpxj#134]
I use an MPP file as a template, insert data into it, and export it

**Comment by yuanhca** [comment]
I noticed that this feature was added in version 7.9.8, but it has not been released to Maven center. Another question is, can this framework export project views? Thanks for answers

**Comment by joniles** [comment]
Hi, I see you've closed the issue, but just to confirm the custom field functionality you are interested in will be in 7.98., which I imagine will be released before the end of the month. Regarding your other question, the MSPDI file format doesn't support import or export of view configurations.

**Comment by EPLB** [comment]
> ...custom field functionality you are interested in will be in 7.98

Just so I understand, @joniles  , in 7.9.7 I will see custom MPP Task fields defined in the ProjectFile object in memory but the **_values_** of these Task-level custom fields are not read in this version? Because I can see my custom field names in Hash Maps if I traverse the object arrays in the debugger. You are saying not to (yet) bother trying to extract the values?

**Comment by joniles** [comment]
@EPLB for MPP files, presently you will be able to read custom field lookup tables and the actual custom field values applied to tasks, resources etc.

for MSPDI files you can currently read and write the actual custom field values applied to tasks, resources etc, but you cannot present read or write the lookup tables which control which values these fields can have. Support for reading and writing these lookup tables will be available in 7.9.8.

**Comment by yuanhca** [comment]
@joniles hi,I noticed that you have released version 7.9.8, but I haven't found a way to write ValueGUID in task.

**Comment by joniles** [comment]
@whymesay it's been a few years! Just circling back to pick up questions I hadn't responded to. It looks like the code to set `ValueGUID` was added in version 8.3.2.

**Comment by whymesay** [comment]
> [@whymesay](https://github.com/whymesay) it's been a few years! Just circling back to pick up questions I hadn't responded to. It looks like the code to set `ValueGUID` was added in version 8.3.2.

@joniles Wow, time really flies! I no longer handle this project, but I'm glad it's still piquing your interest.
