### ISSUE TITLE
java.lang.module.ResolutionException

### ISSUE THREAD

**Issue by martinm1000** [joniles/mpxj#138]
Hi, when updating the library to 8.0.0 in a java 13 application that uses **modules** I get this error while the JVM boot up:
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules jaxb.api and webservices.api export package javax.xml.bind.annotation to module rtfparserkit
```

I tried this but that **didn't work.**
```
--add-opens jaxb.api/javax.xml.bind.annotation.adapters=rtfparserkit
--add-opens webservices.api/javax.xml.bind.annotation.adapters=rtfparserkit
```

I don't think this is something I can fix on my side.

**Comment by joniles** [comment]
Are you using maven to build your project and manage dependencies, or some other mechanism?

**Comment by martinm1000** [comment]
@joniles I am, I get this by running the application under IDEA. But everything compiled ok. I guess your libraries are not using modules ? Or can you see if using a more recent versions of jaxb (>= 2.3.0 ) will work better on the module path ?

![image](https://user-images.githubusercontent.com/3790866/71844404-05462e80-3094-11ea-8739-1f8d2e17b543.png)

**Comment by joniles** [comment]
That's correct, MPXJ doesn't use modules. I' trying to be as backwards-compatible as possible so the only hard requirement we have now is the use of Java 8. MPXJ ships with all of the required dependencies in the `lib` directory, including the JAXB JARs.

**Comment by martinm1000** [comment]
Well I'm just not going to update. This is the only library (its dependencies) that is a problem right now for me. My other dependencies are all running as modules/automatic modules. Maybe someone else might get an idea how to fix this, its been a while since I debugged the whole module thing.

**Comment by joniles** [comment]
Hmmm... having done some further research, I'll take a look at bumping the JAXB version to see if that'll get around the issue.

**Comment by martinm1000** [comment]
I was able to remove some of the dependencies I had that were preventing me from updating to a more recent mpxj version. Since no one else complained, I guess we can close this issue. Thank you !

**Comment by joniles** [comment]
Thanks for letting me know, glad you were able to move forward.
