### ISSUE TITLE
Wrong TimephasedWork for Material resource assignment

### ISSUE THREAD

**Issue by ConstructionProject** [joniles/mpxj#139]
When material resource assignment has some actuals entered, getTimephasedWork returns List with wrong EndDate. Please check getTimephasedWork for MaterialResource assignment In 1-task-project attached. 
More precisely in source code:   EndDate returns by Date finish=  calendar.getDate(startWork, adjustedTotalWork, false), (line 190 in  src\net\sf\mpxj\mpp\TimephasedDataFactory.java) has to be 2020/02/04 instead of 2020/01/17 returned.

[MPXJ_TimePhasedMaterilaResourceBug_to_JonIles.zip](https://github.com/joniles/mpxj/files/4059112/MPXJ_TimePhasedMaterilaResourceBug_to_JonIles.zip)

**Comment by joniles** [comment]
Hi! Sorry for the delay in getting to this, I think I've fixed the issue. The changes have been merged and will be in the next MPXJ release.

**Comment by ConstructionProject** [comment]
Thanks Jon!
Will check it out

*CP *Support Team
https://cproject.pro


вт, 8 нояб. 2022 г. в 23:26, Jon Iles ***@***.***>:
