### ISSUE TITLE
Activity ID in primavera is not getting exported

### ISSUE THREAD

**Issue by patsrik** [joniles/mpxj#14]
The Activity ID is not being set to the Task object of mpxj when reading from primavera using the  PrimaveraXERFileReader class. 
The default ACTIVITY IDs in primavera are set as A0001, A0002 etc. When you export a project as P6 XML, you will see that this id of the Activity is set in the _id_ tag.
But when you are reading the Primavera XER file using the mpxj  PrimaveraXERFileReader, the Task object's id is set as a sequence (1,2,3 etc). What is the way to get the Activity ID of the project seen in P6? Am using the Task class's getID() API to get this id.

**Comment by joniles** [comment]
Hi! 

The ActivityID can be found in the Text1 field.

Jon

**Comment by patsrik** [comment]
Hi, we are getting the ActivityID by using the _getText(int index)_ API of the **Task** class. Thank you for the information. 
But when we import the same xml back to Primavera, we expect the same id gets set as the Activity ID. What we have observed is, the WBS number is getting set as the Activity Id. What is the solution for this ? Your immediate response for the issues raised till now is much appreciated. Thank you

**Comment by joniles** [comment]
When you say XML, are you importing a PMXML file into Primavera?

**Comment by patsrik** [comment]
Yes, we are generating the XML using PrimaveraPMFileWriter and importing as
PMXML.

On Mon, Jun 20, 2016 at 10:48 AM, Jon Iles <notifications@github.com> wrote:

> When you say XML, are you importing a PMXML file into Primavera?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joniles/mpxj/issues/14#issuecomment-227084282>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGztUMkWC_Yuk1aJPB_EmMkq1O04Tevdks5qNlPsgaJpZM4I4ht7>
> .
>



-- 
Regards,
Srikanth Patruni
Sr Developer, Lean Station
www.leanstation.com.sg
Mob : +49 1517 5954915

**Comment by patsrik** [comment]
Hi, is there a way we can get the Activity ID while exporting as PMXML ?

On Mon, Jun 20, 2016 at 11:19 AM, Srikanth Patruni <
patrunisrikanth@gmail.com> wrote:

> Yes, we are generating the XML using PrimaveraPMFileWriter and importing
> as PMXML.
>
> On Mon, Jun 20, 2016 at 10:48 AM, Jon Iles <notifications@github.com>
> wrote:
>
>> When you say XML, are you importing a PMXML file into Primavera?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/joniles/mpxj/issues/14#issuecomment-227084282>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AGztUMkWC_Yuk1aJPB_EmMkq1O04Tevdks5qNlPsgaJpZM4I4ht7>
>> .
>>
>
>
>
> --
> Regards,
> Srikanth Patruni
> Sr Developer, Lean Station
> www.leanstation.com.sg
> Mob : +49 1517 5954915
>



-- 
Regards,
Srikanth Patruni
Sr Developer, Lean Station
www.leanstation.com.sg
Mob : +49 1517 5954915

**Comment by joniles** [comment]
Hi, I've added the `setActivityIdField` method to the PMXML file writer which will allow you to set which task field is used to populate the Activity ID attribute in the PMXML file it generates. Currently this defaults to `TaskField.WBS` to retain the current behaviour. Assuming you have the Activity ID value in the Text1 field then calling `setActivityIdField` with `TaskField.TEXT1` before you write the PMXML file should give you what you want!

**Comment by patsrik** [comment]
Thank you very much Jon. It means a lot :).

On Sun, Jun 26, 2016 at 9:01 AM, Jon Iles <notifications@github.com> wrote:

> Hi, I've added the setActivityIdField method to the PMXML file writer
> which will allow you to set which task field is used to populate the
> Activity ID attribute in the PMXML file it generates. Currently this
> defaults to TaskField.WBS to retain the current behaviour. Assuming you
> have the Activity ID value in the Text1 field then calling
> setActivityIdField with TaskField.TEXT1 before you write the PMXML file
> should give you what you want!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joniles/mpxj/issues/14#issuecomment-228587723>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGztUIaNPXiRogAm8LiKJw61KgzTi0-fks5qPiPkgaJpZM4I4ht7>
> .
>



-- 
Regards,
Srikanth Patruni
Sr Developer, Lean Station
www.leanstation.com.sg
Mob : +49 1517 5954915
