### ISSUE TITLE
If the duration is negative, it will be wrong to write to the xml data

### ISSUE THREAD

**Issue by yuanhca** [joniles/mpxj#140]
If the duration is negative, it will be wrong to write to the xml data, then in the xml it is -PT416H0M0S, but the project will read as 0. I tried using Project to save as xml, and the result was PT-416H0M0S.
@joniles

**Comment by yuanhca** [comment]
@joniles

**Comment by joniles** [comment]
Can I just confirm, is this the MSPDI file format you are referring to? How are you generating a negative duration?

**Comment by yuanhca** [comment]
> Can I just confirm, is this the MSPDI file format you are referring to? How are you generating a negative duration?

yes，MSPDI file format。We need a duration before a time, and then we find that project can set a negative duration, so we use it.

**Comment by joniles** [comment]
Could you attach a sample MSPDI file showing the negative duration? Are you reading an MPP file containing a negative duration then writing it to MSPDI, or are you building a new MSPDI file yourself? If you're reading this value from an MPP file could you attach a copy too? Thanks!

**Comment by yuanhca** [comment]
> Could you attach a sample MSPDI file showing the negative duration? Are you reading an MPP file containing a negative duration then writing it to MSPDI, or are you building a new MSPDI file yourself? If you're reading this value from an MPP file could you attach a copy too? Thanks!

[template.zip](https://github.com/joniles/mpxj/files/4085619/template.zip)
This compressed package contains mpp file and MSPDI, they have negative duration, and MSPDI file is generated using Project 'Save As'.

**Comment by joniles** [comment]
Hi, I've fixed the issue. The code is now available in git, and will form part of the next MPXJ release.
