### ISSUE TITLE
getTimephasedWork taking too much time 

### ISSUE THREAD

**Issue by Dalot** [joniles/mpxj#141]
Hey,

```
ASP.NET.MVC 5.2.7;
net.sf.mpxj-common 8.0.2;
net.sf.mpxj-for-csharp 8.0.2;
net.sf.mpxj-ikvm 8.0.2;
```

I am looking through a list of ResourceAssignments that I fetched like this
```List<ResourceAssignment> resourceAssignments = _projectFile.ResourceAssignments.toArray().Cast<ResourceAssignment>().ToList();```

I then loop through that List and retrieve each ResourceAssignment's `TimephasedWork` and `TimephasedActualWork`.

I am retrieving all the data successfully but it is taking too much time on both getters, significantly more than any other method I used all over the library. I am not being able to understand why...

As an example, a list of 138 `ResourceAssignments` is taking up to **20s**.

![image](https://user-images.githubusercontent.com/8915574/72986068-469e4400-3ddf-11ea-9de6-0c8c139465b2.png)

Anything that could help me get a decent time?

**Comment by Dalot** [comment]
I have looked **into** the library and the only thing I see that could be the **culprit** is the **LinkedList**...?

If I am correct, if you use a **LinkedList**, the CPU will have to jump from memory reference to memory reference in other to track all the nodes and it could be the bottleneck.

I am able to parse an entire MPP Project in 4s-7s if not using this getter. I will take around 3.5 minutes just to get all the TimephasedWork and TimephasedActualWork of all ResourceAssignments and they are not that many. What is also interesting is that if I am fetching 5k objects (ResourceAssignments + TimephasedWork + TimephasedActualWork), the last 1k will take more time than the first 4k suggesting that it's traversing `n` nodes to get the `(n + 1)`. 

**I did not run particular tests** to confirm this assessment due to time constraints, I will wait for any further information from anyone here.

Thank you

**Comment by Dalot** [comment]
After giving it another look, I thought that it would be less time consuming using **Parallelism** than refactoring the whole `TimephasedWork` structure logic in mpxj's library, especially because I am often doing repetitive tasks anyway. It defintely helped and I was able **to reduce 3.5 minutes to 30s**. It is a significant improvement but 30s still feels a lot and thus, **LinkedList** still may be an issue.

I also want to clarify that I have much code unrelated to the current **TimephasedWork** getter that it **does not implement** async/await, concurrency nor parallelism and there is nowhere to find such performance bottlene. Being so, I still think the present affair is something worth sorting out if you find the opportunity. 

Thank you.

**Comment by joniles** [comment]
Hi, thanks for the notes. Would you be able to provide a sample MPP file which illustrates the problem?

**Comment by Dalot** [comment]
Hey, there you go:

https://we.tl/t-seD9yQ2jFq

The times with this file(just a portion of the one discussed above) were around 18s with **TimephasedWork** and 1 ~ 2 second without it.

Thank you for taking a look into this.

**Comment by Dalot** [comment]
@joniles Did you get the file? If not please download it here https://we.tl/t-vJAWFRpeHT

Let me tell you that I am using a i7-8700 3.20GHz CPU which definetly helps a lot. Already tried in other CPUs and it is a disaster. 

Do you already have any idea of what is going on? I might be able to help if you share any information regarding the issue.

Thank you!

**Comment by joniles** [comment]
My apologies, I thought I had downloaded the file to work with, but now I've had some time to take a look I've been unable to locate my copy. Happy to take another look if that's helpful to you. On a related note, the next release of MPXJ removes the use of `LinkedList` entirely so that may tackle one aspect of the performance issue you were seeing.

**Comment by joniles** [comment]
I'm going to close this issue as it's been around for a while now. My apologies for not picking up the sample file in a timely manner. If you do happen to have a copy available still I'd be happy to take another look. There was actually some performance improvement work in this area recently, so the latest version of MPXJ may have improved the situation.
