### ISSUE TITLE
Is it possible to get last opened table?

### ISSUE THREAD

**Issue by PhantomStyle** [joniles/mpxj#144]
I have two identical files. The only difference is that I have different last opened tables. I mean that on the first file I had one table opened before exiting from ms project, and on the second file I had another opened table. Both of these tables exist in both files. The difference is only between last opened tables.
So, can I get information about what table was opened when I closed the file?

**Comment by joniles** [comment]
I think what you need is
```java
String viewName = projectFile.getViews().getViewState().getViewName();
```
This should give you the name of the view that will be shown when the file is opened, which in turn will define which table is visible. You can find the corresponding view definition in the `ViewContainer` from `projectFile.getViews()`.

**Comment by PhantomStyle** [comment]
Thanks. It works!

**Comment by PhantomStyle** [comment]
It worked with 2013 version files. Seems it doesn't work with 2003 version. Can you help me?

**Comment by joniles** [comment]
I tried this with a quick sample file I created in Project 2003 and it seemed to work ok. Can you attach a file which doesn't work for you? Thanks!

**Comment by joniles** [comment]
I'm closing this as I didn't have a response to my last message.
