### ISSUE TITLE
How to retrieve default work week?

### ISSUE THREAD

**Issue by dargonwanglong** [joniles/mpxj#149]
I'm using MPXJ 8.0.5 and I'm trying to retrieve all work weeks in calendar.

I created a new calendar called "My Calendar" as project calendar. And changed the work days for the default work week, and created a new work week called "Special".

With the following test code, I can see the default work week and the new created work week. But when use ProjectCalendar.getWorkWeeks() to retrieve all work weeks, it only returns the new one.

How do I retrieve the data from the default work week?

My test code:
```
UniversalProjectReader reader = new UniversalProjectReader()
ProjectFile projectFile = reader.read("MSProject2WorkWeek.xml")
ProjectProperties projectProperties = projectFile.getProjectProperties()
ProjectCalendar calendar = projectFile.getDefaultCalendar()
```

My test project file:
[MSProject2WorkWeek.xml.zip](https://github.com/joniles/mpxj/files/4256908/MSProject2WorkWeek.xml.zip)

**Comment by dargonwanglong** [comment]
@joniles 
Any update for this?

**Comment by joniles** [comment]
Hi, apologies for the delay in responding. The `ProjectCalendar` instance itself is the default work week:

```java
ProjectCalendar calendar = projectFile.getDefaultCalender();
ProjectCalendarWeek defaultWeek = (ProjectCalendarWeek)calendar;
List<ProjectCalendarWeek> otherWeeks = calendar.getWorkWeeks();
```
