### ISSUE TITLE
Cannot get the value of the Custom Outline code field from XML file.

### ISSUE THREAD

**Issue by dargonwanglong** [joniles/mpxj#150]
Here is my test XML file:
[ProjectSample.XML.zip](https://github.com/joniles/mpxj/files/4273461/ProjectSample.XML.zip)

Here is my test code:
```
UniversalProjectReader reader = new UniversalProjectReader()
ProjectFile projectFile = reader.read("ProjectSample.XML")
ProjectProperties projectProperties = projectFile.getProjectProperties()
ProjectCalendar calendar = projectFile.getDefaultCalendar()
CustomField field
projectFile.getCustomFields().iterator().each { customField ->
  String msFieldName = customField.getAlias()
  if (msFieldName.equals('dev_my_outline_code')) {
    field = customField
  }
}

projectFile.getChildTasks()[0].getCurrentValue(field.getFieldType())
```
In this way, I can get value from other custom fields, but failed to get value from custom outline code field, it always return null. But for MPP file, this way works for the custom outline code field.

After import the test XML file to MS Project, some tasks outline code fields are not empty. See:
<img width="942" alt="2020-03-02 12 37 44" src="https://user-images.githubusercontent.com/16732869/75646149-9b0ccd00-5c83-11ea-846d-ff733bcf46d0.png">

Is this a bug or I need to use another method to get the value of this field?

**Comment by joniles** [comment]
Hi, apologies for the delay in replying. If you know the alias, you can use:

```java
task.getFieldByAlias("dev_my_outline_code")
```

to retrieve the value of the field.
