### ISSUE TITLE
How to get WBS tasks from P6 files 

### ISSUE THREAD

**Issue by gregra81** [joniles/mpxj#151]
Hi,
First of all, thank you very much for this wonderful library, it really helps!

I'm trying to understand how to get WBS in a P6 file, tried this:
```
    ProjectReader reader = new UniversalProjectReader();
    ProjectFile project = reader.read(fileInputStream);

    TaskContainer tasks = project.getTasks();
    for (Task task : tasks) {
        System.out.println("WBS Level: " + task.getWBSLevel());
    }
```

I get `null` for all tasks, but in P6 I actually see the WBS lines. What am I missing?

**Comment by joniles** [comment]
Hi, sorry for the delay in replying. The `Task` class in MPXJ doesn't have a `getWBSLevel` method, can you clarify which method you are using? Thanks!

**Comment by gregra81** [comment]
Thank you for your reply @joniles. My goal is to understand if a certain task is of type WBS or not

**Comment by joniles** [comment]
Hi! Currently MPXJ imports the "Activity Type" attribute for activities and writes the values to the `TEXT2` field. (The alias "Activity Type" has been set for this field so can use this to access it if that's more convenient). All tasks which have been derived from activities should have an Activity Type set. For tasks derived from WBS items `TEXT2` will be blank.

Hope that helps!

**Comment by gregra81** [comment]
@joniles I see that for the `Task` class I have the `getType` method which returns a `TaskType`.
`TaskType` has these enum values: 
```
  FIXED_UNITS(0),
  FIXED_DURATION(1),
  FIXED_WORK(2);
```
Which has nothing to do with WBS.

Am I missing something?

**Comment by joniles** [comment]
As noted above the value you need is in the `TEXT2` attribute. You can retrieve this as:

```java
task.getText(2);
```

or, as an alias has been defined for the field, you can use:

```java
task.getFieldByAlias("Activity Type");
```
