### ISSUE TITLE
MPP12Reader parsing Task with the wrong Flag4 / Flag17 data

### ISSUE THREAD

**Issue by ninthwaveltd** [joniles/mpxj#152]
Firstly, I just wanted to say that MPXJ is an awesome project, and thanks for all the hard work :)

I'm trying to debug an MPP file which is parsing incorrectly.

The plan contains 92 tasks but the task on line 71 is the only one failing to parse correctly.
It has the highest uniqueID in the plan of 449.

Using debug tools I have noticed that the 449 task gets added twice to the taskMap at [MPP12Reader.java#L87](https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/mpp/MPP12Reader.java#L873)

In my case the first occurrence of this is mapping to loop 95 and then overwritten by loop 97.
However, I am finding that the correct task data was at the loop 95 location.

Also of interest is that the taskFixedMeta.getAdjustedItemCount() is 98 while the non-adjusted getItemCount() is 96, so the bad data is being included by the adjusted item count.

I can see a couple of possible fixes, such as:

1) Reverse iterating the loop -> for (int loop = itemCount -1; loop >= 3; loop--)

2) I notice there is a heuristic applied -> "if we have more than 75% of the data" - so if two tasks were found we could keep the one with the best score (although I’m not sure that will solve my issue - The data.length of the 97th loop is well over 100%, this could be an odd symptom of it being the last iteration and maybe missing some item separator in the data stream)

3) Don't allow the .put to overwrite an existing Task already found

I'm not sure if there could be side effects or consequences of any of these ideas.
Hope all of this makes some sense, please let me know if anything is unclear.

Many Thanks,
Luke

**Comment by ninthwaveltd** [comment]
Also I am happy to make the fix and raise a pull request if we have an idea of the best way to deduplicate these tasks (determine which one should be kept).

**Comment by joniles** [comment]
Hello! Thanks for the note. This is unfortunately one of the problems of not really understanding the file format fully. Can you share a sample file (privately if that helps)? Happy to take a look at patches. I have a set of test MPP files which users have sent me over the years which I can use to regression test any changes we make.

**Comment by ninthwaveltd** [comment]
Hi, I'm afraid I cannot share the MPP plan's that I have as they do contain client data that is confidential.

I have tried just reverse iterating the loop as an initial solution and this is showing some promise.
For my own testing I have added an MPPReader.setReverseTaskParsing function.
Then in the MPP12Reader.java I have this code:

boolean reverse = m_reader.getReverseTaskParsing();
      //
      // First three items are not tasks, so let's skip them
      //
    	for (int floop = 3; floop < itemCount; floop++) // floop (Forward Loop)
      {
    	   int loop = reverse ? itemCount - floop + 3 : floop; // Set the loop variable
    	   ...

This is just test code that allows me to turn my change on and off easily within the JVM so I can parse a large number of MPP plans with and without this change and then compare all the values MPXJ has for those tasks and report on any changes that occur, then I can open the plan inside MSP and see which code is getting this more correct. The hope is I will only see corrections and no regressions but at least this way if I find regressions then I can investigate.
To date I have only just tried this against the single plan which was showing the issue and I am finding all the changes to be corrections.
Tomorrow I will run this test code against a much larger set of plans that I have access to and see what I turn up.

**Comment by darthWes** [comment]
We have some files that exhibit similar behavior.  I've corrected the issue, and all of our (hundreds) of examples work perfectly now.

We took the MPPReaders's (there are multiple) createTaskMap function and changed these lines:

if (!taskMap.containsKey(key) || taskVarData.getUnicodeString(key, taskNameKey) != null)

with these:

if (!taskMap.containsKey(key) && taskVarData.getUnicodeString(key, taskNameKey) != null)

Simply turning the or into and made all of our strange issues dissapear.

Sorry, no time to generate a patch, but that's worked for us.  I figure Jon is in a better position to understand what's going on.  Thanks for the hard work.

**Comment by ninthwaveltd** [comment]
So I've tried a couple of ideas:
1) Simply reversing the loop
boolean reverse = m_reader.getReverseTaskParsing();
//
// First three items are not tasks, so let's skip them
//
for (int floop = 3; floop < itemCount; floop++) // floop (Forward Loop)
{
int loop = reverse ? itemCount - floop + 3 : floop; // Set the loop variable
...

- initially I have implemented this with an on off switch for my own convenience in testing (hence the reverse boolean)

With reverse set to true, this works perfectly in the hundreds of plans I have to test with.
And I have just today recieved confirmation from our testing team with this solution.
**So I'm planning on going ahead with this patch in our system.**


2) I also tried favoring the tasks from the original itemCount and only allowing those extra tasks from the adjustedItemCount where no other data was seen for that UniqueID - This did solve my initial plans but I then found other plans in our system that then became incorrect.

3) I thought I had also tried what you suggest @darthWes but I concluded the OR was important, however I can do some retesting with the data I have avaliable.

**Comment by joniles** [comment]
@ninthwaveltd @darthWes thanks for looking at this. I've taken the approach suggested in the notes above, and also made some related fixed to try to ensure that the MPP9, 12 and 14 readers are more consistent. Could you try the code in this branch https://github.com/joniles/mpxj/pull/154 with any test data you have to see if it behaves as expected? Thanks!

**Comment by joniles** [comment]
https://github.com/joniles/mpxj/pull/154 has now been merged.
