### ISSUE TITLE
MPX File Is Not Being Imported In Primavera p6 Software

### ISSUE THREAD

**Issue by Arsuda** [joniles/mpxj#157]
I convert primavera xer file in to mpx formate using `MPXWriter` class. File converted successfully into mpx format. But  when i will try to import file in primavera p6 software its give error

`Import/Export Error: Cannot find a unique value for wbs_short_name in PROJWBS. Last value is 109989 L3 - LIVE X.12.1.109989 - Const.1008`

i am getting this above error. attached screen short as per below. please help me for solved this issue.

![image](https://user-images.githubusercontent.com/6876271/84113462-3f9f6780-aa48-11ea-8f04-72c0a8ea9dc6.png)

**Comment by joniles** [comment]
Hi! Thanks for the note.

Can you attach a sample file for me to take a look at?

Have you tried generating a PMXML file rather than an MPX file, this would be more suitable for import into P6.

**Comment by Arsuda** [comment]
thank you for your response.
i was trying to PMXML import but in that file format not import PercentageComplete in primavera software

**Comment by joniles** [comment]
Can you attach a sample MPX file so I can take a look? Thanks!

**Comment by joniles** [comment]
I'm going to close this as I haven't heard back.
