### ISSUE TITLE
Is it possible to access the resource usage calendar table?

### ISSUE THREAD

**Issue by gavinhailey-sunriselabs** [joniles/mpxj#158]
I am trying to access the table that is shown to the right on the resource usage view (rows defined by resources, columns defined by week), but I can only seem to access the total resource usage table.

**Comment by joniles** [comment]
Hello! Just to confirm, this is from a Microsoft Project file?

**Comment by gavinhailey-sunriselabs** [comment]
Correct, it's a .mpp
