### ISSUE TITLE
Can MPXJ be used in a .net Core or .net Standard project?

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#163]
I tried to use MPXJ (via nuget) in a .net Core project but I'm getting an error on this line:
 ProjectFile project = reader.read(filePath);

This is the error:
System.MissingMethodException: 'Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.'

Is using MPXJ in a .net Core project supported?

Kind Regards
Fredrik Dahlberg
Safran Software Soutions

**Comment by joniles** [comment]
Hi Fredrik,

thanks for your note. Unfortunately MPXJ doesn't work with .net core presently. I'm keeping an eye on this project https://github.com/ikvm-revived/ikvm which looks like it will bring .net core support to IKVM. When it does I will build a .net core compatible version of MPXJ.

Jon

**Comment by fdahlberg** [comment]
Sounds good. Ideally it should be .net standard support so that it can be used in other runtimes than .net core. But .net core is fine for me as well.
