### ISSUE TITLE
ASTA "elapsed time" lag is incorrectly interpreted

### ISSUE THREAD

**Issue by d6mck** [joniles/mpxj#164]
Powerproject supports durations specified in "elapsed time", which is the actual physical time between two dates, rather than the "working time" as defined by a calendar.

When processing predecessors, any "elapsed time" lags are misinterpreted, which will likely lead to scheduling differences when any files exported using mpxj are read elsewhere.

Elapsed times are differentiated in a sqlite database duration column with a 1 in the 0th triplet, like this:

> **1**,0,<6.720000000000000E+02>,

I have coded a solution which works for our examples. It adds support for reading the 0th entry in the duration triplet, and then adjusts any "elapsed time" lag to "working time".

[SqliteResultSetRow.patch.txt](https://github.com/joniles/mpxj/files/4989205/SqliteResultSetRow.patch.txt)
[Row.patch.txt](https://github.com/joniles/mpxj/files/4989207/Row.patch.txt)
[MapRow.patch.txt](https://github.com/joniles/mpxj/files/4989208/MapRow.patch.txt)
[AstaDatabaseFileReader.patch.txt](https://github.com/joniles/mpxj/files/4989209/AstaDatabaseFileReader.patch.txt)
[AstaReader.patch2.txt](https://github.com/joniles/mpxj/files/4989210/AstaReader.patch2.txt)

**Comment by d6mck** [comment]
[This](https://help.elecosoft.com/powerproject/english/15.0.01/Content/HTML_Topics/Conceptual/Starting_work/Creating_bars_and_tasks/Planning_in_working_or_elapsed_time.htm?Highlight=ew) might explain "elapsed time" better.

**Comment by joniles** [comment]
Thanks for the patches, I have them up and running in a new branch. 

My initial observation is that you're going to the trouble of converting an elapsed duration into a working hours duration and using that as the lag. MS Project supports elapsed duration types, so for your example of 2016 elapsed hours -> 480 working hours, I _think_ we could simply express the lag as `2016eh` rather than `480h`. This would preserve the fact that the lag was originally expressed as an elapsed duration and avoid us having to undertake the duration calculation. Would that approach work for you?

**Comment by joniles** [comment]
Could of quick questions:
* do you have a sample file you could attach with an elapsed lag duration?
* Is it possible for any other duration values (e.g task duration) to be expressed as elapsed time?

**Comment by d6mck** [comment]
I think you're right that the elapsed time should be passed on to the handling application, rather than "fixed" internally by mpxj. We'll likely stick with our own kludge though, until we can program to handle elapsed times.

Sample file (with commentary text) attached. I think it's possible that elapsed times could be used elsewhere. The online manual mentions task durations specifically.

[Elapsed Time Lag Example.zip](https://github.com/joniles/mpxj/files/5056805/Elapsed.Time.Lag.Example.zip)

**Comment by joniles** [comment]
Hi,

I've updated the code to detect and handle elapsed durations based on your patch.

Thanks!

Jon
