### ISSUE TITLE
It is possible to get value of sched_open_critical_flag from an .xer file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#165]
Hi,

I'm using PrimaveraXERFileReader to read a .xer file. In P6 there is a scheduling option called "Make open ended activities critical". This setting affects how the late dates are calculated. In the xer file you find the value in the SCHEDOPTIONS table under the field name "sched_open_critical_flag".
Is it possible to get this value from a .xer file  via MPXJ? I did a search for sched_open_critical_flag in the mpxj repo but couldn't find anything.

Kind Regards
Fredrik Dahlberg

PS. Is this the right place to send questions about the functionality?

**Comment by joniles** [comment]
I'll add support for this in the next MPXJ release, probably by the end of August I suspect.

**Comment by fdahlberg** [comment]
Excellent! Thanks a lot!

**Comment by joniles** [comment]
Done! The changes are in git. The flag is imported as a custom property, you'll find them in the project properties.
