### ISSUE TITLE
Importing UTF-16LE encoded xer file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#166]
Hi,
I am trying to use PrimaveraXERFileReader to import a russian xer file that according to notepad is encoded using UTF-16 LE. Every time I try I get the following exception:
Message: Error reading file (failed at line 1)
Stack trace: 
   at net.sf.mpxj.primavera.PrimaveraXERFileReader.processFile(InputStream )
   at net.sf.mpxj.primavera.PrimaveraXERFileReader.read(InputStream is)
   at net.sf.mpxj.reader.AbstractProjectReader.read(String fileName)
   at Safran_Import_Export_Test.XERTest.TestEncoding() in C:\dev\code\Safran MPXJ Test\Safran Import Export Test\XERTest.cs:line 55

I've tried to set both the encoding charset to a number of different things but always get the same result. It might be that I'm doing something wrong. 

Let me know if you need any more info.

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
The `UniversalProjectReader` _should_ handle that for you, so you can use that as the reader class rather than using the `PrimaveraXERFileReader` directly. If it doesn't work for you, can you attach a sample file I can look at?

**Comment by fdahlberg** [comment]
I tried the UniversalProjectReader but that just returned null! Also I need the PrimaveraXERFileReader to read in multiple projects.

Looking at the code (https://github.com/joniles/mpxj/blob/2d6630aab9180c56f19b9ad6e0485ff83744dcb0/src/main/java/net/sf/mpxj/primavera/PrimaveraXERFileReader.java#L267) it occurred to me that the encoding is not taken into account when reading the first characters to make sure that they are "ERMHDR". Could that have somethin to do with it?

Fred
PS. I Could send you the file to your email but don't want to publish it here on an open forum since it's one we got from a customer.

**Comment by fdahlberg** [comment]
Hi,
I managed to remove most of the stuff from the xer file so atttached it here if you want to test it. 
Fred. 
[Текущий график - Small.zip](https://github.com/joniles/mpxj/files/5036145/-.Small.zip)

**Comment by joniles** [comment]
Thanks for the sample file, that was very helpful. I've got a fair idea of what I need to do to fix this. Unfortunately I'm away next week but I'll get the necessary changes in once I get back.

**Comment by joniles** [comment]
The fix for this is now in git and will be in the next MPXJ release.

**Comment by fdahlberg** [comment]
Hi john,

I've just updated to the latest nuget package (8.1.4) and this still doesn't seem to work. I tried to import the file attached to this issue and I get the Exception:
MPXJException: Invalid file format

Fred

**Comment by joniles** [comment]
Are you using `UniversalProjectReader` to open the file? This is doing the work to determine the correct encoding, if you are using `PrimaveraXERFileReader` directly you'd need to replicate that logic and manually set the charset.

**Comment by fdahlberg** [comment]
I am using the PrimaveraXERFileReader. This is because i need to read in all the projects (see start of this thread).  
I could of course copy your code from the UniversalReader and set the character set manually. I guess I would also have to do the skip bytes part on the stream before passing it to PrimaveraXERFileReader. Basically i will create my own UniversalReader. Should be fine. 

It would have been great if this could just work but I guess that would require some changes in the structure. 

Maybe it could have been good if there was a static function that just returned file data (type, character set, and bytes to skip) when given a file path. Based on this data one could do various things. 

Maybe it could have been good if UniversalReader had implemented readAll. For most files it could just return an array with one ProjectFile object in.

**Comment by joniles** [comment]
I will be implementing `readAll` in `UniversalProjectReader`.

**Comment by joniles** [comment]
Just to confirm, I've now added `readAll` to `UniversalProjectReader`.

**Comment by fdahlberg** [comment]
Excellent! Thanks a lot.
