### ISSUE TITLE
mpp文件转换为xml文件后原本的部分字段被隐藏

### ISSUE THREAD

**Issue by firesouls** [joniles/mpxj#167]
![image](https://user-images.githubusercontent.com/34544351/89635958-65c37580-d8da-11ea-97e2-7ba86c5a0784.png)
在使用此代码将mpp文件转换为xml格式之后，Project2016 打开文件时有许多的字段隐藏了，只保留了新建文件时的几个列。我是刚接触这个包的开发者，请问是需要设置些什么属性吗？如果有打扰到的话我很抱歉，但是我实在找不到解决的方案了！

**Comment by joniles** [comment]
From Google translate:

> After using this code to convert the mpp file to xml format, many fields are hidden when the file is opened in Project2016, and only a few columns when creating a new file are retained. I am a developer who is new to this package. Are there any attributes that need to be set? I'm sorry if it disturbs you, but I really can't find a solution!

**Comment by joniles** [comment]
Hello! Hopefully I have understood you question correctly. The MSPDI file format doesn't include any information about which view is shown in Microsoft Project, or which columns are visible. The schedule data should all be present, but you will need to manually add the columns you want to see.

你好！希望我已正确理解您的问题。 MSPDI文件格式不包含有关Microsoft Project中显示哪个视图或可见列的任何信息。计划数据应该全部存在，但是您将需要手动添加要查看的列。

**Comment by firesouls** [comment]
> 你好！希望我已正确理解您的问题。MSPDI文件格式不包含有关Microsoft Project中显示哪个视图或可见列的任何信息。计划数据应该全部存在，但是您将需要手动添加要查看的列。
> 
> MSPDI文件格式不包含有关Microsoft Project中显示该视图或可见列的任何信息。计划数据应该全部存在，但是您将需要手动添加要查看的列。

感谢您的回复，请问相关的方法可以提示一下吗？

**Comment by firesouls** [comment]
> 你好！希望我已正确理解您的问题。MSPDI文件格式不包含有关Microsoft Project中显示哪个视图或可见列的任何信息。计划数据应该全部存在，但是您将需要手动添加要查看的列。
> 
> MSPDI文件格式不包含有关Microsoft Project中显示该视图或可见列的任何信息。计划数据应该全部存在，但是您将需要手动添加要查看的列。

Thank you for your reply. Could you give me a hint about the relevant methods?

**Comment by joniles** [comment]
When you say "Could you give me a hint about the relevant methods", do you mean: "how do I manually add columns to a view in Microsoft Project:?

**Comment by firesouls** [comment]
Yes,I mean that.Thank you

**Comment by firesouls** [comment]
> 当您说“您能给我一些有关方法的提示”时，您的意思是：“如何在Microsoft Project中手动向视图添加列：？

您好，请问您能帮助我吗？

**Comment by joniles** [comment]
Sorry for the delay in replying, I've been away. As a user in Microsoft Project you can right click on the column header, and from there there is a menu option to allow you to insert new columns and choose the type of the column to show. This can also be achieved automatically using a VBA script.

**Comment by firesouls** [comment]
> Sorry for the delay in replying, I've been away. As a user in Microsoft Project you can right click on the column header, and from there there is a menu option to allow you to insert new columns and choose the type of the column to show. This can also be achieved automatically using a VBA script.

感谢您的回复，我已经通过jacob完成了对文件的操作
