### ISSUE TITLE
Is importing of P6 expenses via an xer file supported?

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#168]
Hi,

In my P6 project the activities have expenses defined.
![image](https://user-images.githubusercontent.com/9571179/89895662-79255800-dbdc-11ea-99fa-6ac767743add.png)

I can't see that these come into the mpxj model. They're stored in the PROJCOST table in the .xer file.
![image](https://user-images.githubusercontent.com/9571179/89895709-8f331880-dbdc-11ea-941f-44bc6c2743bf.png)

I did a search for PROJCOST in the repo but I can't see that it's being read.
Is there something that I'm missing here or are expenses not currently supported?

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Activity expenses are not currently supported, although I would be open to adding support for them.

**Comment by fdahlberg** [comment]
Hi John,

It would be great if you could add support for this. In fact it's essential for us that it's there, if we're going to start using mpxj. We need our users to get teh same total cost in our tool as they see in P6. 
I guess the question is how the expenses fit into the MPXJ model. What do you think? 

Fred

**Comment by fdahlberg** [comment]
Hi Jon, 

Have you had time to do any thinking on this one? We're getting ready to start using MPXJ in the next release of our software but we need this functionality to use it for Primavera files. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
I'm planning to work on the implementation this week.

**Comment by joniles** [comment]
The implementation is now available as part of the 8.3.0 release. Tasks now have an `ExpenseItems` attribute.
