### ISSUE TITLE
How to get the "real" duration for an activity

### ISSUE THREAD

**Issue by gregra81** [joniles/mpxj#169]
I'm having a problem with getting the current duration for an existing activity. In my P6 I have the `Edge Case - Activity (30% Complete)`:
![image (2)](https://user-images.githubusercontent.com/3256420/90131611-16b38f80-dd75-11ea-92f6-09961906766d.png)

You can see that the baseline duration is 40 days, the actual duration is 3 and the remaining is 28 (so that the "up to date" duration is actually 31).

In MPXJ, when I'm getting these values in the task:

- `task.getDuration()` = 40
- `task.getRemainingDuration()` = 28
- `task.getActualDuration()` = 0 (instead of 3)

My questions are:

- Why does the `task.getActualDuration()` returns 0 and not 3?
- How can I get the "real" (actual) duration? So I'd expect to get 31 and not 40 in this case

Any help will be appreciated, thanks!

**Comment by fdahlberg** [comment]
Hi,

I had the the exact same problem some time ago. 
I don't think the actual duration is stored in the xer file since it's a calculated field. Therefore I guess mpxj can't give it to you. 
I solved it by calculating the actual duration as the difference between actual start date and the early start date. You have to take the calendar into account of course.   

Fred

**Comment by joniles** [comment]
@fdahlberg just to confirm, I'm assuming you mean the remaining duration is the difference between the actual start dat and the early finish date?

Assuming my understanding is correct, this sounds like something MPXJ should be calculating. I'll try to implement this for the next release.

**Comment by joniles** [comment]
Let me try that again... 

actual duration = difference between early start date and actual start date

I'll take a look at implementing this in MPXJ.

**Comment by gregra81** [comment]
@joniles FYI, from what I tested the duration and the actual duration values are incorrect only for XER. For PMXML the values are exported correctly. If I have to guess, I'd say that it's because XER format doesn't support exporting baseline while PMXML does.
So my recommendation is to apply this change only for XER (as there are other things that influence duration such as holidays and part-time crews, meaning that duration is not just the difference in dates)

**Comment by joniles** [comment]
Hi @gregra81, just tidying up some of these open issues. I _think_ I addressed this in the changes in https://github.com/joniles/mpxj/pull/203 so I'm going to close this issue. If this is still a problem, could you attach your sample XER file so I can take a closer look? Thanks!

**Comment by gregra81** [comment]
@joniles thanks!
