### ISSUE TITLE
Writing TimephasedWork to XML

### ISSUE THREAD

**Issue by martinm1000** [joniles/mpxj#17]
Hi, is the library supporting writing detailed timephasedwork when writing to ms project's xml file ?

What's missing from this code ?

https://gist.github.com/martinm1000/08f020407c8ca83e61e94289ac3d48ec

I don't see the detail of day by day entries to the assignation. (and I can't find much code on the web for that).

**Comment by sreeharibs** [comment]
I tried a similar code, but the problem is The TimePhasedData is not written to the projectFile in Disk (i tried saving as mspdi).

**Comment by sreeharibs** [comment]
No problem. It worked !

```
		MSPDIWriter writer = new MSPDIWriter();
		writer.setWriteTimephasedData(true);
		writer.write(projectFile, HOME_DIRECTORY+"project_aasn_out2.mspdi");
```

**Comment by martinm1000** [comment]
@sreeharibs Thank you, I need to test more, but it looks that's what was missing for it to work !
