### ISSUE TITLE
Summary property of Task is set to false for WBS elements when importing an xer file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#170]
Hi,
I'm importing an xer file with a number of WBS elements. I use the property ProjectFile.Tasks to get all the tasks in the proejct. This also seems to include all the WBS elements. I would expect the Summary to be set to true for the WBS elements. But that doesn't seem to be the case. Is there something that I've missed here?

I've attached an example file where this is happening. 

[Haitang Corporate Park.zip](https://github.com/joniles/mpxj/files/5080381/Haitang.Corporate.Park.zip)

Thanks
Fredrik Dahlberg

**Comment by joniles** [comment]
A fix for this is now in git, and will be part of the next MPXJ release.
