### ISSUE TITLE
Is it possible to get the "Raw" duration format when reading an MSPDI file? 

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#171]
Hi,
I'm trying to read an mpsdi file (.xml). One of the activities has a remaining duration described in the file as:
<RemainingDuration>PT24H0M0S</RemainingDuration>
When this comes in to The Task object the duration is now 3d.
I need the raw duration (24h) since this is what needs to go into our scheduler. Is it possible to get that somehow?

I saw that on the MPPReader there was a property called UseRawTimephasedData. Not sure if that is related to this issue. 

Kind Regards
Fredrik Dahlberg

PS. Do you prefer if I log these questions on the Sourceforge site?

**Comment by joniles** [comment]
From memory, all durations in the MSPDI file are expressed in hours, with a separate attribute indicating the type that the user actually supplied when they entered the value. So in your example I would imagine that the duration was entered in MS Project in days.

You can convert a duration to any time unit you chose, for example to convert a duration back to hours you'd use something like this:

```java
Duration durationInHours = duration.convertUnits(TimeUnit.HOURS, project.getProjectProperties());
```

Happy to continue receiving questions via GitHub.

**Comment by fdahlberg** [comment]
Thanks Jon,

That seems to work!

Fred
