### ISSUE TITLE
Get all projects from a primavera XML file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#172]
Is it possible to get all the projects in a primavera xml file. For xer files you have to use the PrimaveraXERFileReader and then call ReadAll. I can't see that there's the equivalent method on PrimaveraPMFileReader. 

Here's an example with three projects. 
[Haitang Corporate Park.zip](https://github.com/joniles/mpxj/files/5089867/Haitang.Corporate.Park.zip)

Kind Regards
Fred

**Comment by joniles** [comment]
Done! The changes are in git, and will be in the next version of MPXJ.

**Comment by fdahlberg** [comment]
Hi,

I can see that you've added readAll to PrimaveraPMFileReader in the latest version. This is good. But now I have another issue. How do I know that this file is actually a Primavera file and not eg. an MSP xml file? I guess I could read it with the Universalreader first, get the project type and then if it's a primavera xml file use the PrimaveraPMFileReader to read it again. But this is not ideal of course. Some of the file we read are huge and speed is important. 

It would be really nice if I could do either of these two things. 
1. Call a function that just gets me the file type of a file without reading and parsing the whole file. This function could contain what you do in mathesFileType method in the UniversalReader. After that I could choose the filereader to use. 
2. Call readAll on the UniversalReader. This could always return a list of ProjectFile objects that would just contain one ProjectFile for all the file types that don't support multiple project. I think this would be the nicest solution. 

What do you think?

Fred

**Comment by fdahlberg** [comment]
In the new readAll for PrimaveraPMFileReader  it doesn't seem like the property called ExportFlag on ProjectProperties is set. Is this on purpose? It would be good if it was set in the same way as for the xer file. I need to know which of imported projects that is completely exported. 
I guess it's a matter of reading the external attribute on the Project nodes.

**Comment by joniles** [comment]
I've updated `PrimaveraPMFileReader`, it will now set the "export flag" correctly in project properties. I've also added `ReadAll` support for all readers, including `UniversalProjectReader`, so you should only need to read the file you are working with once to retrieve all of the content.

**Comment by joniles** [comment]
Just published a new version which contains this change.
