### ISSUE TITLE
Can't see the CostRateTable for resource when importing P6 XML file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#174]
Hi,

When I'm importing a P6 project as an .xer file I can get the CostRateTable for each resource. For some reason this doesn't seem to be present in the mpxj model (Resource object) when importing an .xml file. 

I've attached the same project as an .xer and an .xml file. 
[Haitang.zip](https://github.com/joniles/mpxj/files/5108970/Haitang.zip)

Is there something I',m doing wrong here?

Kind Regards
Fredrik Dahlberg
PS. If you're interested we might consider helping you out with the development of mpxj.

**Comment by joniles** [comment]
Looking at this now.

**Comment by joniles** [comment]
I've updated the code to support reading cost rate tables from PMXML files, that'll be part of the next MPXJ release.

**Comment by joniles** [comment]
I've updated the code to make this consistent. Resource ID is now read into the TEXT1 attribute (with the alias "Resource ID") for both XER and PMXML files. I will stop reading the Resource ID into the initials field in the next major MPXJ release.
