### ISSUE TITLE
Task getCritical isn't calculated correctly for WBS tasks

### ISSUE THREAD

**Issue by lironzluf** [joniles/mpxj#177]
Hi,

I've encountered the following issue on XER Files (Doesn't seem to reproduce for MPP):
`Task.getCritical()` Returns `true` for all WBS tasks regardless if they're critical or not.

To my understanding, a WBS task is considered critical if one or more child tasks are critical.

Example file:
[EC00515.xer.zip](https://github.com/joniles/mpxj/files/5122290/EC00515.xer.zip)

Thanks,
Liron.

**Comment by joniles** [comment]
I've made a change which hopefully fixes this. The updated code is available in git, and will be in the next MPXJ release.

**Comment by gregra81** [comment]
@joniles This is great, when is this release expected?

**Comment by joniles** [comment]
@gregra81 just published a new version!

**Comment by lironzluf** [comment]
Thank you @joniles. Verified as fixed 👍
