### ISSUE TITLE
Constraints in MPXJ model

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#180]
Hi,

I noticed that you have both MANDATORY_START and MUST_START_ON as constraint types in the mpxj model. From my experience with P6 and MSP these are the same, but called Mandatory Start in P6 and Must Start On in MSP. 
I think it would be better if you only had one of them in mpxj and that both the P6 Mandatory Start and the MSP Must Start On are mapped to the same constraint type. 
Or maybe I'm wrong?
I also see that the P6 constraint type Start On is mapped to the mpxj type MUST_START_ON . This feels wrong since the Start On constraint in P6 is a much weaker constraint than the Must Start On in MSP. 

Since I guess MPXJ is focused on MSP i suggest you map the P6 Mandatory Start to MUST_START_ON and map the P6 Start On constraint to a new type called START_ON.

All this also goes for the finish constraints.

Fred

**Comment by joniles** [comment]
Looking at this now.

**Comment by joniles** [comment]
* I've updated the code to add START_ON, FINISH_ON as explicit constraint types.
* MANDATORY_START and MANDATORY_FINISH now map to MUST_START_ON and MUST_FINISH_ON respectively. 
* The MANDATORY_START and MANDATORY_FINISH constraint type enumerations have been marked as deprecated and will be removed in the next major release.
