### ISSUE TITLE
Which is XER property  unique for Primavera XER file ?

### ISSUE THREAD

**Issue by Arsuda** [joniles/mpxj#182]
The issue is when the same file is being exported from Primavera Software. Every time a file gets exported, a new external id is generated for the tasks. This makes it impossible for several users to work on one XER file and get them updated .

**Comment by joniles** [comment]
Hi, apologies for the delay in replying. Which value are you currently using as the unique ID of the task? I would typically be looking to use the task's GUID as the most "stable" identifier which shouldn't change regardless of how the schedule is edited.

**Comment by Arsuda** [comment]
I solved that issue by WBS code for unique identification it will not change.
