### ISSUE TITLE
使用mpxj生成mpx文件字段内容丢失问题

### ISSUE THREAD

**Issue by fanhaolong** [joniles/mpxj#183]
I used version 8.2.0 MPXJ to generate the MPX file, but the task name was inconsistent with the character name I set, and a character was randomly missing
![image](https://user-images.githubusercontent.com/47815936/93435166-9d6f0580-f8fb-11ea-8d86-d9e34a16be83.png)

**Comment by fanhaolong** [comment]
![Uploading image.png…]()

**Comment by joniles** [comment]
The MPX file format is a little limited, it only officially supports a small number of encodings. I'm wondering if you've not explicitly set the character encoding you'll be using the ANSI encoding, which might explain the missing characters. I'm assuming you're looking to encode Chinese, so perhaps something like this will work for you:

```java
projectFile.getProjectProperties().setMpxCodePage(CodePage.ZH);
```

Alternatively, if your use case allows I would recommend generating MSPDI files instead which are standard XML and encoded as UTF-8 so you shouldn't hit any encoding problems with text.

**Comment by joniles** [comment]
I haven't heard back from you for a while so I'm going to close this ticket. Please feel free to reopen if you want to continue discussing this issue.
