### ISSUE TITLE
Which custom fields come from P6 values that do not fit the mpxj model?

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#185]
Hi,

Some P6 values (task type, suspend date, resume date etc.) do not fit into to the mpxj model so they are stored in mpxj custom fields. The P6 user fields are also stored as custom fields. Is it possible when looking at the custom fields to know which come from P6 user fields?

In our system we also have user fields but we don't want for example suspend and resume date to come in as user fields. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
I've been thinking about this for a little while. I believe the best way to go is to add explicit attributes to the relevant classes in MPXJ to store the non-MS Project attributes we're collecting from other applications. That way custom fields are used purely for user defined values. How does that sound?

In order to preserve semantic versioning I'll need to do this as two releases, one as a minor version to include the new attributes and a major version bump to remove the use of custom fields.

**Comment by fdahlberg** [comment]
I think it sounds pretty good. I assume you want the MPXJ model to be as close as possible to the MSP model. 

When we're converting from the MPXJ model to our model we need to take into account the file type, but this is ok. 

Another way would be to make the MPXJ model more generic.
When you look at for example the ID field it's an integer in MPXJ. I guess you could change this to a string so that it could also be used for the P6 id. But this might create problems when exporting to MSP formats i guess....

**Comment by joniles** [comment]
> I assume you want the MPXJ model to be as close as possible to the MSP model

That was my original intention (20 years ago!) but I haven't been consistent with applying that approach, I have added attributes in the past which are not present in MS Project. It will only add a a handful of new attributes to tasks and resources, so it's not a big deal.

I'll let you know when I've made progress on this.


> we need to take into account the file type

I assume you've already got a solution for this, if not, take a look at the `FileApplication` and `FileType` attributes in `ProjectProperties`.

**Comment by fdahlberg** [comment]
OK! Sounds good. We're already using the filetype attribute in ProjectProperties. It's necessary since we import from multiple formats. 
When you add these new properties could you add a doc comment that says which file formats they're relevant for. That would probably be good to know in case someone wonders why a certain property is never set when you import a file.

**Comment by joniles** [comment]
I had another look at this. In the longer term I'd like to start moving some attributes into the MPXJ data model, but I may not want to move everything (there are some very _niche_ use cases!). To improve the current situation I've added the `userDefined` attribute to the `CustomField` class. This will be `true` for attributes which have been defined by user of the source application, and `false` for cases where MPXJ is just extending its data model to capture standard attributes from the source application.

Let me know if that doesn't work for your use case and I'll take another look!

**Comment by fdahlberg** [comment]
I think that sounds like a good solution! 
When will that be available?
