### ISSUE TITLE
Outline Code information lost in XML (MSPDI) export

### ISSUE THREAD

**Issue by d6mck** [joniles/mpxj#186]
We're trying to get outline codes to be exported from our software into XML, and there appears to be at least one sticking point.

Even from Microsoft Project itself (we're on 2019, but have seen similar with 2016), outline codes used in tasks, when passed through mpxj from MPP to XML, lose data such that reimporting doesn't work fully.

The issue appears to be the absence of the `<ValueID>` in a task's `<ExtendedAttribute>`. mpxj does not supply this value: it writes the `<Value>` instead. This appears to be not enough information for Microsoft Project to reconstruct a task's outline code value.

I assume the `<ValueID>` could be determined with reference to the data behind the top level `<OutlineCodes>` section, but I struggle to find out how.

Attached are the mpp, and the two xmls.

[Project1.zip](https://github.com/joniles/mpxj/files/5365583/Project1.zip)

**Comment by d6mck** [comment]
I found a workaround. I'd not go as far to claim it as a solution. I'm not proud of it, but it works for us!

If I pass a delimited string through to the `<ExtendedAttribute>` behind the outline code, the portion before the "|" character is applied to the `<Value>`, and the portion after is applied to the `<ValueID>`.

Shows up as I'd expect when imported into Microsoft Project.

I'm sure there's a neater way to do it. Patch, for what it's worth, attached!

[mspdiwriter.patch.txt](https://github.com/joniles/mpxj/files/5378560/mspdiwriter.patch.txt)

**Comment by joniles** [comment]
Hi. I'm assuming the attribute you're setting is `ValueGUID` rather than `ValueID`?

Here's my attempt: https://github.com/joniles/mpxj/pull/190 does this work for you?

I have some efficiency-related tidying up to do, but I _think_ that does what you need.

**Comment by d6mck** [comment]
Hi Jon, no the `<ValueId>` is what's required. Apologies, I didn't include the patch for mspdi's Project schema which would have highlighted that I added an additional XML element.

[project.patch.txt](https://github.com/joniles/mpxj/files/5408655/project.patch.txt)

**Comment by d6mck** [comment]
I've tweaked your patch to borrow your technique and, in combination with my own path for the Project schema, the XML is what we require. Note that I've commented out your `setValueGUID` call since we don't currently populate the GUIDs, and I get a crash otherwise.
[mspdiwriter2.patch.txt](https://github.com/joniles/mpxj/files/5416714/mspdiwriter2.patch.txt)

**Comment by joniles** [comment]
I've looked at this a little more closely, and I see that MS Project actually generates separate `OutlineCode` tags for outline code entries on a task rather than doing what MPXJ does presently and lump everything together using `ExtendedAttribute` tags. I think as a first step I'll update MPXJ to make this distinction (which also gives us access to the `ValueID` tag without having to modify the schema). We should then be able to get the logic in place to include the relevant `ValueGUID` or `ValueID` tags.

**Comment by joniles** [comment]
OK, my branch https://github.com/joniles/mpxj/pull/190 has been updated to take the `OutlineCode` approach.

**Comment by d6mck** [comment]
That looks great from our end, Jon. Renders as expected in Microsoft Project given the exported XML. Thanks.

**Comment by joniles** [comment]
Changes merged. New version coming shortly.
