### ISSUE TITLE
Calendar minutes per week is wrong in xer import if the hours per week is not an integer

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#194]
Hi,
I'm importing a P6 calendar with hours per day set to 7.5hrs. I noticed that in the mpxj model ProjectCalendar.MinutesPerDay is set to 420. I would expect it to be 450. 
The problem seems to be on lines 369-372 in PrimaveraReader.java. The cast to int seems to be in the wrong place. Instead of casting the result of the multiplication it casts the day_hr_cnt value. 
https://github.com/joniles/mpxj/blob/f303c60dcda6a92e13a0286c1d60f9c88e08ecf6/src/main/java/net/sf/mpxj/primavera/PrimaveraReader.java#L369

I've attached an example where this happens.
[CalendarTest.zip](https://github.com/joniles/mpxj/files/5643537/CalendarTest.zip)

For the import of pmxml the ProjectCalendar.MinutesPerDay seems to be set to 480 min regardless what the HoursPerDay value is. This also seems wrong. 

Let me know if you need any more info. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Great catch, thanks for that. Both issues you note have been fixed, the changes are now in git.

**Comment by fdahlberg** [comment]
Excellent! When do you think the next nuget version will come? I haven't tried to build the project from git yet. I'm a bit unsure how to build a combined java and .net project.

**Comment by joniles** [comment]
Just to confirm, an updated version of MPXJ is now available.

I made some rough notes [here](http://www.mpxj.org/howto-build.html) to explain the build process, ideally I need to go back and make them more step-by-step.

**Comment by fdahlberg** [comment]
Thanks! I've updated to the latest nuget package now. All looking good so far! Thanks for being so quick to fix these things. 

I might look into creating a build some day.
