### ISSUE TITLE
At Completion Units not coming in when importing pmxml file. 

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#195]
Hi,

When I import an .xer file the P6 resource assignment field "At Completion Units" comes in as ResourceAssignment.Work in the mpxj model. 
This doesn't however seem to work for the pmxml import. Here the ResourceAssignment.Work is empty, 
I've attached an xer and an pmxml from the same project. 
[Cost Test.zip](https://github.com/joniles/mpxj/files/5644105/Cost.Test.zip)

Let me know if you need any more info.,

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
I've updated the PMXML code to make it consistent with the XER code, and the results seem to match when I look at your test schedules. The changes are in git now.
