### ISSUE TITLE
Planned Start/Finish Date Missing (PMXML)

### ISSUE THREAD

**Issue by d6mck** [joniles/mpxj#196]
Hi Jon, I see you've a fix in the works for the above, which we came across this morning. Is a new release imminent?

**Comment by joniles** [comment]
I have a small list of fixes to get in... if I can get through those it'll be this week.

**Comment by d6mck** [comment]
Cheers, I'll keep an eye out.

**Comment by joniles** [comment]
The new version of MPXJ is available now.
