### ISSUE TITLE
Remaining cost seems to be wrong from the 8.4 version for PMXML file import

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#200]
Hi,

I noticed that that the remaining cost is wrong after the 8.4 version when I import the attached file. 
[Cost Test.zip](https://github.com/joniles/mpxj/files/5780773/Cost.Test.zip)

The remaining cost should be 46240 for the activity called "Not Started". This cost comes from two resource assignments, one with the  cost of 6240 and one with 40000. It seems like the 40000 cost is ignored in version 8.4. In version 8.3.5 this works as expected. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
I think I've fixed this, the relevant changes are in git. I'll probably have a new release out this week.

**Comment by fdahlberg** [comment]
In which nuget version will this be fixed?

**Comment by joniles** [comment]
I'm not sure yet. I have breaking changes I'd like to make, which will mean making the next version 9.0.0, and I still have a good few hours of changes to make to wrap things up.

**Comment by fdahlberg** [comment]
No worries. I'm not in a hurry to get this version at the moment.

**Comment by joniles** [comment]
Just closing the loop on this one - the 9.x releases of MPXJ contain this fix.

**Comment by fdahlberg** [comment]
Hi Jon,
I've been testing the latest version of mpxj a bit so far and it looks good. 
However, I noticed that the early and late dates don't seem to be populated when doing a PMXML import anymore. I think they were before. Is there a reason for this? We need these field so that we can compare our way of scheduling with how the tasks were scheduled in P6 (and other tools that we import from). 
Fred

**Comment by joniles** [comment]
Hi Fred,

The PMXML file doesn't actually contain values for Early Start, Early Finish, Late Start and Late Finish. What I was doing previously was using the values for Remaining Early Start, Remaining Early Finish, Remaining Late Start and Remaining Late Finish to populate the Early Start, Early Finish, Late Start and Late Finish attributes.

I've actually separated the various attributes out so Remaining Early Start, Remaining Early Finish, Remaining Late Start and Remaining Late Finish should have their own attributes and be read/written independently... however I messed that up during the big refactor and missed out some of that work. I've now corrected this (the changes are in Git). Once you get a version of MPXJ with the new code you'll be able to restore the original behaviour by using the values from the Remaining Early Start, Remaining Early Finish, Remaining Late Start and Remaining Late Finish attributes.

I _think_ that in order to correctly populate the Early Start, Early Finish, Late Start and Late Finish attributes when reading a PMXML file I'm going to need to run the critical path calculation on the activities. I'll add that to my todo list to do some more research.

Jon

**Comment by fdahlberg** [comment]
Hi Jon,

Thanks for your reply. I'm a little bit confused about Early Start vs Remaining Early Start etc. 
Looking at this page 
https://www.cdp-inc.com/content/tech-tips/understanding-activity-dates-p6
it seems to me that :
Early Start = Remaining Start date
Early Finish = Remaining Finish date
Late Start = Remaining Late Start date
Late Finish = Remaining Late Finish date
I also tried this in P6 and I can't see any difference between these dates.
If this is the case it seems a bit confusing if you have both versions in the mpxj model. 

It's important for us that the dates from P6 come in to the same properties in mpxj regardless of whether they come via an xer or an xml file. 
It's also important that we can get the dates that were calculated by P6. We're not really interested in dates calculated by mpxj. Does mpxj calculate any dates during the import? If so I think this should be an option. If mpxj calculates some dates there should be some way of knowing whether the dates came from the source file or were calculated.

Ideally I would like to see the Early and Late dates coming straight from P6 into the mpxj Task properties:
EarlyStart, EarlyFinish, LateStart and LateFinish. But if they come into the remaining versions that's fine too. As long as this same principle is applied to other file imports like MSP.


Kind Regards 
Fredrik Dahlberg

**Comment by fdahlberg** [comment]
Hi Jon,

After some more investigation I now see that there is a subtle difference between Remaining ES and ES in P6. The Remaining dates can be changed. However, as soon as you Schedule the dates will be the same again.
So if you export an project without scheduling it first these date pairs can be different. 
Knowing this I can see that there's a point in having them both in the mpxj model. 
The important thing for us though is that we can be sure that these dates come from the original file and that they haven't been calculated by mpxj. 

Thanks
Fred

**Comment by joniles** [comment]
> The important thing for us though is that we can be sure that these dates come from the original file and that they haven't been calculated by mpxj.

Early Start, Late Start, Early Finish, Late Finish are not available in PMXML files, so you won't be able to use these values when reading this particular file type if you can only work with data provided directly by P6. Frustratingly, the values are present in XER files, so you can use them without any problem if your source is an XER file.

On the broader question of whether a value has been calculated by MPXJ or has come from the source scheduling system, would you need to be able to query that information from MPXJ in some way?

**Comment by fdahlberg** [comment]
Hi Jon,
I forgot that Early Start, Late Start, Early Finish, Late Finish are not available in PMXML files. But that's fine. We can use the remaining versions then.

As long as we can be sure that the dates have not been calculated by mpxj we don't need to query mpxj about where the dates come from I guess. Maybe it's useful for some users of mpxj to have mpxj calculate dates but for us it would just be confusing. We just want to read in the  dates from the file as it is. 
Are any dates calculated today? I have assumed that all the dates in the mpxj model come from the source file. 

Fred
