### ISSUE TITLE
Actual Duration is not set for a P6 xer file import.

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#201]
Hi,

I'm looking at activities in P6 with actual duration. It seems like the field Task.ActualDuration is not set. Is this by design?
I've attached a file as an example.

[Actuals In the future Test.zip](https://github.com/joniles/mpxj/files/5781990/Actuals.In.the.future.Test.zip)

Let me know if something is not clear. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
The code now in git has been updated to calculate the actual duration. This seems to work ok for the example activities in your schedule... except the one where the actual start is after the data date. P6 is calculating 3 days actual duration for that activity, but I'm not sure how. Any suggestions gratefully received!

**Comment by fdahlberg** [comment]
Just realized that actual duration is not in the xer file since it's calculated by P6. So i guess it's ok not to have it in mpxj. 
I guess the 3 days come from the difference between actual and early date taking calendar into account. 
![image](https://user-images.githubusercontent.com/9571179/105060665-f3ee7b00-5a78-11eb-9276-1fdebaee0de0.png)

But now I'm not sure whether this needs to be calculated in mpxj. 

Thanks
Fred

**Comment by joniles** [comment]
> Just realized that actual duration is not in the xer file since it's calculated by P6.

That's no problem, I'd prefer MPXJ to be as complete as possible to make it easier for users to get usable data from it without having to perform additional calculations themselves. I'll leave the calculation in, although it ignores "edge cases" where the actual start is after the data date. I found that with another XER file I'd been supplied by a user, calculating the actual date using one of the early start dates didn't seem to produce results consistent with P6. We can come back to look at this again in future.
