### ISSUE TITLE
P6 Calendar Exception not coming in correctly via .xer

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#204]
Hi,

I have a P6 plan with a calendar that has exceptions. The normal work time for all days of the week is 8-12 and 13-17. On two days with exceptions (6 and 7 august) the work time is 8-12, so 4 hours instead of 8 hours. 
When it comes in to the mpxj those two days seem to come in with work from 0-24. 
It doesn't seem right. Or maybe it's something that I'm missing. 
Attached the xer file here:
[CalendarExceptionTest.zip](https://github.com/joniles/mpxj/files/5848587/CalendarExceptionTest.zip)

The calendar exceptions in the xer looks like this:
(0||Exceptions()
			(    
				(0||0(d|44047)())    
				(0||1(d|44048)())    
				(0||2(d|44049)(      (0||0(s|08:00|f|12:00)())))    
				(0||3(d|44050)(      (0||0(s|08:00|f|12:00)())))
			)
		)

Maybe the work time in the two last exceptions is ignored by mpxj. 

Would be great if you could have a look at this.

Thanks
Fredrik Dahlberg

**Comment by joniles** [comment]
Hi, I've had a quick look at the sample file. Here's what I can see when I open the file using the "project explorer" application included with MPXJ:

![image](https://user-images.githubusercontent.com/4912864/105738888-6d7de180-5f2f-11eb-8f82-08724270921a.png)

I ran the same file through the .Net version of `MpxjQuery` just to check it wasn't some weird .Net/Java thing and I can see the expected working time range on the two exceptions. I wonder if you'd spotted the start/end time for the exception - that's potentially misleading as it is showing the exception is active for a single day (from 00:00:00 to 23:59:59).

**Comment by fdahlberg** [comment]
Hi Jon,

Thanks for your reply. You're absolutely right. It was my mistake. I had missed the ranges underneath the exception. I think it works fine. Maybe it could be clearer but I'm not sure how. 

Thanks
Fred
