### ISSUE TITLE
In Xer import two identical links is not handled correctly by mpxj

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#207]
Hi,

Sometimes we've noticed that xer files can contain more than one of the same link. When this happens it can look like this in the TASKPRED section:
%R	646584	400975	400976	11511	11511	PR_FS	0		2021-02-18 17:00	2021-02-24 08:00
%R	646587	400974	400975	11511	11511	PR_FS	0		2021-03-03 17:00	2021-03-04 08:00
%R	649648	400975	402584	11511	11511	PR_SS	24		2021-02-23 17:00	2021-02-12 08:00
%R	649999	400975	402584	11511	11511	PR_FF1	0		2021-02-25 17:00	2021-02-24 08:00
%R	650017	400975	402584	11511	11511	PR_FF	0		2021-02-19 08:00	2021-03-03 17:00
%R	654575	404492	400975	11511	11511	PR_SS	0		2021-02-24 08:00	2020-08-10 08:00
%R	656834	404492	400975	11511	11511	PR_FF	0		2019-05-31 08:00	2023-02-10 17:00

As you can see the FF link between 402584 and 400975 is in there twice. I can see in the mpxj code that you're trying to stop duplicate links from coming in and that's good. Unfortunately in this case since the map RELATION_TYPE_MAP does not contain PR_FF1 the second link is imported as FS link. 

I managed to reproduce this issue in P6 and produced this file:
[Duplicate Link problem.zip](https://github.com/joniles/mpxj/files/5919710/Duplicate.Link.problem.zip)
In this example the FF links all come in as FS links. 

I think the best solution would be to ignore all the links that haven't got one of the correct link types (PR_FS, PR_SS, PR_FF, PR_SF).

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Looks like there are a couple of things going on here. The first is the unusual representation of the relationship type (`PR_FF1`). As P6 appears to be able to interpret these correctly I've updated MPXJ to do the same, so it will strip off the suffix and try to interpret what's left. 

The other interesting thing is that P6 actually allow multiple predecessor/successor relationships between tasks, including duplicates. In the long term I'd like to be able to support this, so you can work with the data exactly as P6 sees it, but for now I've left the existing logic in place in MPXJ which tries to remove duplicates.

I think the duplicate handling code originally came from a desire to match the constraints put in place by MS Project, which I don't think will allow you to create more than one relationship between two tasks, regardless of the relationship type (FF, FS SS etc). The code in MPXJ actually falls short in this respect as it does allow for multiple relationships as long as the types differ. I'm planning to revisit this as part of the work noted above.

Anyhow, the relevant changes are now in the git repo, hopefully the results will align with what you're expecting.

By the way, do you know how the unusual type values (e.g. `PR_FF1`) end up being generated?

**Comment by fdahlberg** [comment]
I think P6 ignores the links with suffixes. It's actually quite easy to create one. But I'm not sure why P6 allows it, since it seems like it only would happen from a user's mistake. Could be that it was better to keep it instead of just deleting it, thus allowing the user to correct his mistake. Attached video where you can see one way of creating these links. There might be more ways. 
[2021-05-05_13h02_29.zip](https://github.com/joniles/mpxj/files/6426625/2021-05-05_13h02_29.zip)

I wasn't aware that you couldn't have more than one link between two tasks in MS Project. Tested and that's correct. Good to know. We often see people linking two tasks with both SS and FF link in P6. So I guess that can't be done in MSP.
