### ISSUE TITLE
P6 roles in an xer file are not imported 

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#208]
Hi.

It seems like P6 roles are not included when importing an xer file. Here's an example:
[Role Test.zip](https://github.com/joniles/mpxj/files/5926386/Role.Test.zip)
It's important for us that they come in so that we can get the costs in our tool to match the cost in P6. The roles and role assignments could come in as normal resources. Maybe the resource representing roles could be marked somehow in a userfield or similar, but that is not very important at the moment.

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Hi, the code to support roles is now available in the git repo. I'm importing roles as resources, and there is now a `role` flag on the resource which is `true` if the resource represents a role and `false` if it is a normal resource.

**Comment by fdahlberg** [comment]
That sounds like a very good solution I think.

**Comment by fdahlberg** [comment]
Tested this and seems to work well. Excellent work!
