### ISSUE TITLE
The same resource assigned multiple times to the same task is not handled during xer import

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#211]
In P6 you can assign the same resource to a task multiple times. Like this:

![image](https://user-images.githubusercontent.com/9571179/109484120-58d9bf80-7a80-11eb-807d-7cd8d1d0a15a.png)

When this project is exported to xer and imported into mpxj it seems like only one of the resource assignments come in. 
Here is the xer file. 
[Duplicate res ass test.zip](https://github.com/joniles/mpxj/files/6060821/Duplicate.res.ass.test.zip)

Would be great  if this could be handled by mpxj. We need this data from P6,. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Hi, I've just released MPXJ 9.3.1 which has been updated to preserve multiple resource assignments. Let me know how you get on!

**Comment by fdahlberg** [comment]
Tested it. Works very well!
