### ISSUE TITLE
Baselines returned null for Primavera schedule files

### ISSUE THREAD

**Issue by lironzluf** [joniles/mpxj#215]
Since upgrading to version `9.0.0` 
`baselineStart` and `baselineFinish` return `null` on all tasks for Primavera schedule files (XER, PMXML)

Uploaded an example XER
[Hospital.xer.zip](https://github.com/joniles/mpxj/files/6182627/Hospital.xer.zip)

**Comment by joniles** [comment]
Working on it... I'll update here once I'm done and provide more detailed notes on baseline handling. 👀

**Comment by joniles** [comment]
I've released MPXJ 9.2.0 which contains baseline-related updates.

Here are the various situations where baselines are populated:

If a project in P6 has its "Project Baseline" set to "<current project>" then the baseline attributes in MPXJ will be populated from the current project when reading an XER or PMXML file.

If a project in P6 has its "Project Baseline" set to reference a specific baseline project, and the user exports a PMXML file which includes that baseline project (the user must select this option explicitly on export), then the baseline attributes will be populated automatically in MPXJ.

If a project in P6 has its "Project Baseline" set to reference a specific baseline project, and it is exported as an XER file, or it is exported as a PMXML file without explicitly including the baseline project, the baseline attributes in MPXJ _will not_ be populated.

However... _if_ you can get the user to export the baseline project separately, you can read it using MPXJ, then when you read the main project you can call the `ProjectFile.setBaseline()` method to populate the baseline attributes from the baseline project. You can see an example of this [here](https://github.com/joniles/mpxj/blob/6e81fa1c68c34ef841c430057cc6cb751659a415/src/main/java/net/sf/mpxj/primavera/PrimaveraPMFileReader.java#L296-L307), this is the code which attaches baselines when reading PMXML files.
