### ISSUE TITLE
Original WorkContour value read from .mpp files instead of Contoured

### ISSUE THREAD

**Issue by ndarlington** [joniles/mpxj#228]
When writing files for Project to open, we can set the Modified flag on TimeScaledValue items (and optionally set the WorkContour on the ResourceAssignment to `WorkContour.CONTOURED`.

When reading .mpp files from Project, the modified flag on all TimeScaledValue entries are false and the WorkContour always displays the prior value from Microsoft Project before the Work was changed in the Task Usage view to get it to display contoured (e.g. `WorkContour.FLAT`).

Simple project created by hand in MSP, tasks 1-8 use each of the Work Contour values, task 9-16 are a copy of tasks 1-8 with manual updates to the hours in the time scale view, changing the WorkContour to Contoured automatically.

Reading the WorkContour property of an assignment inside MSP VBA reports a value of 8 for tasks 9-16 correctly (e.g. `PjWorkContourType.pjContour`).

![image](https://user-images.githubusercontent.com/40403963/119900499-38e45b80-bf0a-11eb-9576-9a4f9f97e1d5.png)

My test project code using MPXJ 9.3.1 consists of this, changing the project filename on each run to compare results:

```cs
using net.sf.mpxj;
using net.sf.mpxj.mpp;

namespace MPXJNext.Net {

    class Program {
        private const string PROJECT_FILENAME = "c:\\users\\blahblah\\documents\\project1-2013-standard.mpp";
        static void Main(string[] args) {
            var reader = new MPPReader();
            var project = reader.read(PROJECT_FILENAME);

            foreach (ResourceAssignment assignment in project.ResourceAssignments) {
                System.Console.WriteLine($@"{assignment.Task.Name}: {assignment.WorkContour}");
            }
        }
    }

}
```

Example output:
```
t1: FLAT
t2: BACK_LOADED
t3: FRONT_LOADED
t4: DOUBLE_PEAK
t5: EARLY_PEAK
t6: LATE_PEAK
t7: BELL
t8: TURTLE
t9: FLAT
t10: BACK_LOADED
t11: FRONT_LOADED
t12: DOUBLE_PEAK
t13: EARLY_PEAK
t14: LATE_PEAK
t15: BELL
t16: TURTLE
Press any key to continue . . .
```

Compare to the VBA dump from MSP immediate window:
```vba
for each t in thisProject.Tasks: for each a in t.Assignments: print t.Name; " "; a.WorkContour: next a: next t
t1  0 
t2  1 
t3  2 
t4  3 
t5  4 
t6  5 
t7  6 
t8  7 
t9  8 
10  8 
t11  8 
t12  8 
t13  8 
t14  8 
t15  8 
t16  8 
```

Sample projects attached, all identical, but from different versions of MSP (2013 standard, 2016 standard, project desktop online professional):

[project1-multiple.zip](https://github.com/joniles/mpxj/files/6557088/project1-multiple.zip)

**Comment by ndarlington** [comment]
Note: I noticed this the same in MPXJ 7.9.3 as well as 9.3.1 so it's not a new version issue.

**Comment by joniles** [comment]
I've merged a fix for this, it'll be in the next MPXJ release.
