### ISSUE TITLE
missing tasks when parsing mpp14

### ISSUE THREAD

**Issue by 331299** [joniles/mpxj#23]
After I deleted a task and its children in project 2010 or 2013, mpjx will get wrong result.
Distinguish deleted tasks with (flags & 0x02) != 0, seems not right for mpp14.

**Comment by joniles** [comment]
Hi, Can you attach a sample file which exhibits this behaviour? Thanks!

**Comment by 331299** [comment]
[demo.mpp.gz](https://github.com/joniles/mpxj/files/856847/demo.mpp.gz)
Sorry, I forgot to upload it.

**Comment by joniles** [comment]
Hi, I believe that this is fixed by the latest code in git.

**Comment by 331299** [comment]
Yes, thanks very much.
