### ISSUE TITLE
Getting Error using .Net Core 

### ISSUE THREAD

**Issue by ThakkarKhushbu** [joniles/mpxj#230]
Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.Security.AccessControl.FileSystemRights, System.IO.FileShare, Int32, System.IO.FileOptions)'.

Getting above error while using below code 

         
   UniversalProjectReader reader = new UniversalProjectReader();
            // ProjectFile project = reader.read(@"C:\A00-N0002 Master template CR Int.xer");
             ProjectFile project = reader.read(FilePath);

**Comment by joniles** [comment]
The .Net assemblies for MPXJ don't currently support .Net Core. This is an issue I will be addressing in future as this project https://github.com/ikvm-revived/ikvm, which will update IKVM to support .Net Core, progresses.

**Comment by ThakkarKhushbu** [comment]
HI but it is working in independent console application , but when I convert that console app to class library and us that in .net core it is giving me error.

**Comment by joniles** [comment]
I'm surprised that it works at all under .Net Core! Are you building your console application in Visual Studio?

**Comment by ThakkarKhushbu** [comment]
Yes , Let me send you that working application

**Comment by ThakkarKhushbu** [comment]
https://drive.google.com/file/d/1wGSe7m0IpawU1x6tzrvD3NhATmP3nBls/view?usp=sharing

**Comment by ThakkarKhushbu** [comment]
https://pasteboard.co/K5WmkgH.png

**Comment by ThakkarKhushbu** [comment]
As shown in above image , it works fine in console app , but when i convert it from console to class library and use it in my existing project , i am getting error

**Comment by ThakkarKhushbu** [comment]
https://pasteboard.co/K5WnaLV.png

**Comment by joniles** [comment]
![image](https://user-images.githubusercontent.com/4912864/121513882-41956100-c9e3-11eb-9da3-16c72fb36561.png)

It looks like you sample project is configured for a version 4 of .Net rather than 5 (.Net Core). This may be why it works.

**Comment by ThakkarKhushbu** [comment]
I see , is there any work around for this to use.  I need to read .Xer and .Mpp file in my current project , it's important

**Comment by joniles** [comment]
Are you targeting Windows?

**Comment by ThakkarKhushbu** [comment]
no , it's WebApi

**Comment by joniles** [comment]
So what platform will this code be running on, Linux?

**Comment by ThakkarKhushbu** [comment]
ohh , sorry I misunderstood your question. we are doing deployment on Azure cloud not on machine

**Comment by joniles** [comment]
Ah! So I assume .Net 5/Core is your only option... and you have no access to the machine itself (i.e. you can't install and run command line executables)?

**Comment by ThakkarKhushbu** [comment]
no we can not run command line executables

**Comment by joniles** [comment]
Unfortunately at the moment it means there is very little you can do. I can't guarantee when I'll be able to look at creating a .Net Core compatible version of MPXJ, and this work will be dependent on the progress of the IKVM Revived project.

The only other approach I can think of is to host a service outside of Azure which will allow you to run a Java-based web service which consumes schedule files and sends back JSON (using MPXJ's `JsonWriter`). You should then be able to read the JSON representation of the schedule in Azure and work with the data it contains. This won't give you all of the functionality MPXJ offers but it gets you further forward. You may even be able to do this as a Lambda in AWS (I think they support Java).

**Comment by ThakkarKhushbu** [comment]
okay thank you for your suggestion

**Comment by ThakkarKhushbu** [comment]
Hello @joniles ,

Sorry for disturb again. I am able to read .Xer file in .net Project , now i need to write that "Project Task" Into JSON File. 

Can I  write Only Project Task Using JSONWriter?

**Comment by joniles** [comment]
You can use `net.sf.mpxj.json.JsonWriter` to create a JSON file from a `ProjectFile` instance, but you may find it easier to create your own JSON schema and writer to match your specific needs.

**Comment by ThakkarKhushbu** [comment]
Can you give any link for sample code for JSON write similar like below

import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.mpx.MPXWriter;

// ...

MPXWriter writer = new MPXWriter();
writer.write(projectFile, outputFileName);

**Comment by joniles** [comment]
```java
import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.json.JsonWriter;import net.sf.mpxj.mpx.MPXWriter;

// ...

JsonWriter writer = new JsonWriter();
writer.write(projectFile, outputFileName);
```

**Comment by ThakkarKhushbu** [comment]
I have tried but getting below error 
https://pasteboard.co/Ka5aD1h.png

**Comment by joniles** [comment]
Looks like a collision between classes with the same name. Either fix your `using` statements to avoid brining in the other class if you don't need it, or use the fully qualified name for the MPXJ class:

```java
JsonWriter writer = new net.sf.mpxj.json.JsonWriter();
```

**Comment by ThakkarKhushbu** [comment]
It works , thank you so much
