### ISSUE TITLE
Resource.Code is not working 

### ISSUE THREAD

**Issue by khurram-saleem** [joniles/mpxj#232]
Resource resource1 = file.addResource();
                    resource1.Code = Resource1;
                    resource1.Name = Resource1;

I write this code but this thing only shows the Resource Name Column in mpx file but not showing a Column Resource Code

**Comment by joniles** [comment]
I've tried to reproduce this in both Java and C# but have been unable to. In both cases I can see the resource code value being written into the MPX file. If you're still having problems, could you ensure that you are using the latest version of MPXJ. I'm assuming you're using Visual Studio - if so you can create a sample project using the code here https://github.com/joniles/mpxj/blob/master/src.net/MpxjCreate/MpxjCreate/MpxjCreate.cs and update it to reproduce the problem. If you can zip up the project and attach here once you've done that I can take a look.
