### ISSUE TITLE
Data date for MPP File Returning Epoch Date (01.01.1970)

### ISSUE THREAD

**Issue by VipulADSK** [joniles/mpxj#235]
Hi @joniles,

I have a MPP file which doesn't have any data date set (data date is NA). While importing the extractor is sending the date as "1970-01-01T00:00:00.000Z" (epoch date) instead of null and hence are causing some confusion.

Can you please help us to take a look into it. I am attaching the file with this request.
[Sch-PB_Scheduled.mpp.zip](https://github.com/joniles/mpxj/files/6769049/Sch-PB_Scheduled.mpp.zip)

**Comment by joniles** [comment]
I believe this issue was fixed recently, can you try with the latest version of MPXJ? I've tried this locally with the MPP file you provided and I get `null` for the status date.
