### ISSUE TITLE
Import of P6 Resource Calendar

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#258]
Hi,

I was under the impression that the Resource property on Calendar was only set when the Calendar was of type CA_Rsrc. However this seems to also happen in other situations. In my case a calendar had resource set to a parent resource of a resource in the project. 
What is the logic for setting Resource on calendar during the import of a P6 file (.xer or .xml)?

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Hi, thanks for the notes on this. Sorry for not responding earlier, somehow my GitHub notifications were switched off. Anyhow, I'll prioritise this as the next area I work on.

**Comment by fdahlberg** [comment]
Hi Jon,
Have you had a chance to look at this? Happy to discuss over teams if you need more background. 
Fred

**Comment by joniles** [comment]
Hello! I'm pleased to say that this issue has been address in MPXJ 10.3.0. Let me know how you get on!
