### ISSUE TITLE
Cannot Read Phoenix Files

### ISSUE THREAD

**Issue by pdinahar** [joniles/mpxj#260]
Good day - 

We are having issues reading in Phoenix files using MPXJ (we have been using it in a .Net application). 
With the latest MPXJ version (10.0.5), when reading the files, there is an error "net.sf.mpxj.MPXJException: Invalid File Format'. 
![image](https://user-images.githubusercontent.com/46799935/149977904-4783fac4-98e4-470b-8803-e9496614d468.png)

Have tried it in several Phoenix files - same results. 

Interestingly enough, last year (Jan '21) we had a similar issue where we couldn't read Phoenix files - updating to the MPXJ version current at that time (8.4.0), solved it. 

We tried reverting our MPXJ version to the 8.4 version, and unfortunately while the Phoenix files we were testing from a year ago work just fine, current files (from Phoenix V4) still don't work. 

The Phoenix version is V4. 

We would greatly appreciate your assistance with this matter. One of our customers uses solely Phoenix at their company, and it's impacting their workflow, so we'd request that this issue be considered high priority.  

For security, I will email the Phoenix files directly (p###s###@g##.com). 
The 'Innslake' file was from last year - which worked with V8.4. 
The 'Altria' file is from this year - won't work regardless of the version. 

Thanks again!

**Comment by joniles** [comment]
Hi! Both of those files open fine for me. Are you using `UniversalProjectReader` to open the files or are you working with `PhoenixReader` directly?

**Comment by pdinahar** [comment]
Thank you for your response. I've tried with both of those readers - in both cases and with both files, I'm getting a java.lang.NullPointerException. MPXJ version = 10.0.5.
***@***.***

Code is below (in my test application).
***@***.***


Pratap Dinahar|
Senior Information Technology Manager
The Aegis Companies
w: +1 240.880.4433 ext. 108| c: +1 240.997.2040
www.consultaegis.com
15 YEARS & CHARGING AHEAD!

**Comment by joniles** [comment]
Not sure if you included some code or a screenshot, nothing is visible here on GitHub. Can you provide a copy of the stack trace if you are seeing a null pointer exception?

**Comment by pdinahar** [comment]
Looks like Github stripped out the screenshots when I replied from my email directly. 

Please find attached, the images.
![img_exception](https://user-images.githubusercontent.com/46799935/149988916-1415bcb0-ee44-4af2-8cf9-5359d07e523e.png)
![img_code](https://user-images.githubusercontent.com/46799935/149988917-2969deb2-d623-4c73-9a33-2827a38c1962.png)

**Comment by pdinahar** [comment]
One more image.
![img_immediate_win](https://user-images.githubusercontent.com/46799935/149989711-7f8b3b39-ae31-47e0-9883-a846619abbe1.png)

**Comment by joniles** [comment]
I can see there would be an issue using `PhoenixReader` directly as there is some logic built in to `UniversalProjectReader` to handle compressed files which `PhoenixReader` doesn't currently have. Can you switch to using `UniversalProjectReader` (as per your commented out lines) and see if you can reproduce the same problem?

**Comment by pdinahar** [comment]
I tried with the UniversalProjectReader as well - I got the same error with both files. 
![img_immediate_r2](https://user-images.githubusercontent.com/46799935/150009944-1d3b9a89-5ee7-4700-9a30-ee4f6a16f9af.png)

**Comment by joniles** [comment]
Just a quick check, I'm assuming you're using .NET Framework (rather than .NET Core)?

In the debugger can you break where you are catching the exception, then dig into the exception object to retrieve the stack trace for the main exception and repeat for the inner exceptions until you get to the bottom of the tree of nested exceptions.

**Comment by joniles** [comment]
Hi, I haven't heard back form you in a while, are you still having an issue with this?

**Comment by joniles** [comment]
Hello! I'm going to close this one now as I haven't heard back from you for a while. Feel free to reach out again if you are still having problems. Thanks!  Jon
