### ISSUE TITLE
Missing Tasks When Reading from a Export That Has Been Baselined.

### ISSUE THREAD

**Issue by amarkssmartpm** [joniles/mpxj#275]
If I set a baseline for a project then export it to MPP the task list gets messed up and I only get a subset of them when reading.  The same export file loads correctly back into MPP.  Attaching the project, before and after baseline.  The "BL" file does not read properly using mpxj, missing tasks.
[Documents.zip](https://github.com/joniles/mpxj/files/8613816/Documents.zip)
.

**Comment by joniles** [comment]
Hello! I've just released 10.4.0 which I believe fixes the issue. Let me know how you get on!

**Comment by ndarlington** [comment]
Is it possible to do the push of 10.4.0 to nuget for .net or will it be pending feedback or similar first?

**Comment by joniles** [comment]
@ndarlington oversight on my part! I'll push that version to Nuget as soon as I can.

**Comment by joniles** [comment]
@ndarlington nuget should be up-to-date now!

**Comment by ndarlington** [comment]
Thank you @joniles
