### ISSUE TITLE
Missing Tasks when processing an export from Microsoft Project Version 2204 Build 16.0.15128.20158

### ISSUE THREAD

**Issue by grahamleslie** [joniles/mpxj#276]
Howdy,

When importing an MPP file from Microsoft Project Version 2204 Build 16.0.15128.20158, some tasks are missing. When importing the same file exported as XML, all tasks are present.

It appears there may be some issue with processing MPP files from this latest Microsoft Project build.

Many thanks.

**Comment by joniles** [comment]
I think this may be the same issue as https://github.com/joniles/mpxj/issues/275, can you try using 10.4.0 which I've just released!

**Comment by grahamleslie** [comment]
The latest version did resolve our issues. Thank you @joniles !
