### ISSUE TITLE
ProjectCalendar non-working days calculation

### ISSUE THREAD

**Issue by darthWes** [joniles/mpxj#295]
In (net.sf.mpxj.)ProjectCalendar, there is a function getStartDate that allows me to calculate start dates based on having the finish date and a duration.

Basically, it's set up to take finish date and duration, walks through the calendar, and takes exceptions into account to determine what start date would have been needed to reach that {finish date, duration} tuple.  I've noticed that it occasionally fails because there's an early exit condition of 7 non-working days in a row.  I believe the spirit of this was to say if all 7 days are non-working, you've entered a calendar with no working days, and you can't possibly complete the calculation.  However, because "isWorkingDate" is doing double checks (it's checking if the specific day (ie, 12-28-2022) is an exemption as well as if the day (Wednesday) is a recurring exception according to the calendar), any stretch of time with 7 non-working days (Christmas, for most of my users) will also fail.  Obviously, this is not the desired behavior.

There's multiple ways this could be fixed, I usually change the protection condition from "if (count > 7)" to a larger "if (count > 365)" which doesn't actually completely fix the issue, but would be astronomically unlikely for a real person to setup a calendar with an entire year of exceptions.

Another way would be to decouple the "isWorkingDate" functionality into seperate checks:
1.  Is this specific date an exception?
2. Is this day (Thursday, for example) a recurring exception?
and then test for 7 concurrent day exceptions.

Jon, would you be able to address this?  Would you like me to take a stab at the 2nd solution?  I think the entire community would be better served if you implemented this, since I'm sure there's a simpler/more elegant way than the ham-fisted solution I would inevitably conceive.

Thanks!

**Comment by joniles** [comment]
I've added a fix for this. The approach I ended up taking was to use the project start date as the cut off point to stop looking for working days rather than counting an arbitrary number of non-working days.

**Comment by joniles** [comment]
Hi, just to let you know version 10.6.0 has been released which contains all of the changes relating to the last few issues opened here. Let me know how you get on!
