### ISSUE TITLE
Reading of Assignments with long period TimephasedData takes too long

### ISSUE THREAD

**Issue by stophi-dev** [joniles/mpxj#296]
Reading the attached XML file with one single assignment takes 8 minutes on my machine.
I created an extreme example with an 80 years period. But the time does multiply with the number of assignments, so it would actually even take longer in a more realistic example.

According to my analysis, the most time is spent in `MSPDITimephasedWorkNormaliser.java` in the `splitDays` method where it would loop through the while block for every single day in the time period.

I am fine if you reject the issue with the reason that the input file is nonsensical. But maybe there is room for improvement and it could be more robust in that regard.

[MSP-Long-Runner.zip](https://github.com/joniles/mpxj/files/8813146/MSP-Long-Runner.zip)

**Comment by joniles** [comment]
Hello! Thanks for opening the issue, definitely room for improvement here. Can I get some quick background information: are you working with the Java version or the .Net version of the library? Thanks!

**Comment by stophi-dev** [comment]
Java version

**Comment by joniles** [comment]
I've added a fix for this, it's in version 10.6.0 which has just been released. Let me know how you get on!

**Comment by stophi-dev** [comment]
Wow, I didn't expect such a fast response!
I can confirm that it's loading much faster now with MPXJ 10.6.0. Thank you very much.
