### ISSUE TITLE
Exception working with AstaFileReader class

### ISSUE THREAD

**Issue by wrustel** [joniles/mpxj#30]
Hey,

I need help with this issue, when I am trying to read one file with .PP extension in C# doing this:

AstaFileReader reader = new AstaFileReader();
ProjectFile projectFile = reader.read(inputFile);

This error appear

"Can not convert the type 'java.util.PropertyResourceBundle' to 'sun.util.resources.OpenListResourceBundle'." 

Maybe I am doing something wrong, could I get help please?

**Comment by joniles** [comment]
Can you confirm which version of MPXJ you are using, and could you supply me with a sample file which causes the problem? (Feel free to contact me directly if you'd prefer not to post a sample here).

**Comment by wrustel** [comment]
The version used is  5.13.  
And here is the file https://www.dropbox.com/s/75e6k4gxb2scedp/test-file.pp?dl=0

**Comment by joniles** [comment]
Thank you. I've just confirmed that the latest version of MPXJ (v7.0.0) reads this file successfully. I'd recommend updating the version of MPXj you are working with. Let me know if there is anything else I can help with.  Jon

**Comment by wrustel** [comment]
Ok thank you, could you give me your code? I'm going to try it.

**Comment by joniles** [comment]
You can use NuGet to retrieve the latest version of the package, or you can find the zipped release here on GitHUb under the releases menu item.

**Comment by wrustel** [comment]
Updated to 7.0 and throw the same exception again. I dont get it. Are you sure this is fixed for asp.net c#?. Because It doesn't make any sense. Here I attached to you the trace and the version

![image](https://user-images.githubusercontent.com/8282594/32906844-7d89f050-cafe-11e7-8230-ad0cb8c57645.png)

![image](https://user-images.githubusercontent.com/8282594/32906883-9826b916-cafe-11e7-8ffc-8a72343fd0cd.png)

**Comment by joniles** [comment]
Was this the first time you've used NuGet to install the package? Can you check to ensure that you don't have any of the old DLL versions hanging around?

**Comment by wrustel** [comment]
I did uninstall package and then install the new version, is not enough?

**Comment by joniles** [comment]
Possibly not. I'd restart visual studio, and check your project directories for copies of the mpxj DLL.

**Comment by wrustel** [comment]
Yeah, deleting the old versions in the package folder fixed that. Thank you!. 

Now I have a last question. When I import the same file I gave to you, and inspect the object result, there are not task. 


![image](https://user-images.githubusercontent.com/8282594/32945552-2fc2e868-cb94-11e7-9005-5bfe620578c1.png)


This is strange and I'd like to compare with you, both result, your and mine. The file give to you Task objects?

**Comment by joniles** [comment]
I've had a quick look, you should be seeing tasks. I'll investigate... it looks like it's the oldest version of the PP file format MPXJ supports...

**Comment by joniles** [comment]
I've updated MPXJ so it will now successfully read tasks from your sample file. I'll probably make a new release in the next couple of days.

**Comment by wrustel** [comment]
Ok, I'm waiting for your release, Thank you!

**Comment by joniles** [comment]
The new release is available now.

**Comment by wrustel** [comment]
Hello again, I updated the new release and tried it with a file. It worked, however I tried with another one and it didnt parsed the "AllTask" fields. I attach you a new file. As you can see, this file is the same extension .pp but the library does not take any task.



https://www.dropbox.com/s/tp8p1246wchh7um/Test-File-2.pp?dl=0

**Comment by joniles** [comment]
I'll take a look...

**Comment by joniles** [comment]
OK, made some more changes. I'll cut you a release now.

**Comment by joniles** [comment]
OK, 7.0.2 is now available.

**Comment by wrustel** [comment]
Works perfectly!, thank you, I owe you a beer.
