### ISSUE TITLE
PP file not opening due to Arch64 and sqlite3

### ISSUE THREAD

**Issue by kamalpanhwar** [joniles/mpxj#303]
I am using mpxj version 10.6.0 when I open my pp file it throws following error.
```
gems/3.0.0/gems/mpxj-10.6.0/lib/mpxj/reader.rb:63:in `report_error': net.sf.mpxj.MPXJException: Invalid file format (MPXJ::RuntimeError)
Caused by: java.sql.SQLException: Error opening connection
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
```
Because currently `mpxj` ruby gem using `sqlite-jdbc-3.30.1.jar` so it is happening, I tried using normal java file and same error come if I open Sqlite db.
but when I changed version to `sqlite-jdbc-3.36.0.3.jar` it is not giving any error and opening file successfully.

I updated version of sqlite-jdbc and it worked. Here is its  [pr](https://github.com/joniles/mpxj/pull/304)
Note I am ruby developer not Java, just tried seem test cases are also running.

**Comment by joniles** [comment]
I've updated the drive version, I'll get a new MPXJ release out as soon as I can.
