### ISSUE TITLE
Reading seq_nbr from P6 Activity Code Value

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#309]
Hi,

We need to import a field from the P6 activity code value that is called "seq_nbr" in an xer file. This is a field that is used to maintain the sorting order for the activity code values.
![image](https://user-images.githubusercontent.com/9571179/175288887-be0c2b0e-0339-498a-99ba-abc2a4bb1ecb.png)

It doesn't seem like that field is part of the mpxj model at the moment and I can't find "seq_nbr" anywhere in the mpxj code so I assume this is not implemented.
It would be great if you could add this field to the mpxj model. It's necessary in order to replicate the P6 sort order. This is important when the user is using an activity code to sort the activities. 

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Hi! I added support for this in 10.6.0. 

https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/ActivityCode.java#L93

Let me know if you're not seeing the data you need and I'll take another look.

Jon

**Comment by fdahlberg** [comment]
Excellent! That's great timing! I've tested it and it seems to work fine. Thanks a lot.
