### ISSUE TITLE
P6 Standard, Internal and External Resource Rates

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#311]
Hi,

In P6 it's possible to define up to 5 sets of unit rates on a resource. It looks like this in the UI:
![image](https://user-images.githubusercontent.com/9571179/176184491-5674076b-3284-4407-bf8e-52b5842d4db6.png)

On the activity you can then select which rate you want to use for each resource that is assigned to the activity. It looks like this:
![image](https://user-images.githubusercontent.com/9571179/176184825-8fc51a0e-9ce7-46ff-872e-141c6e331ab0.png)

It seems like only the Standard Rate is read into the mpxj model as per today. Is that true? If so would it be possible to add support for the other 4 rates (Internal, External, Price/Unit4 and Price/Unit5)?

I've attached an example of a project that has values for Standard, Internal and External. 
[RES_RATE_TEST.zip](https://github.com/joniles/mpxj/files/9001275/RES_RATE_TEST.zip)

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
To confirm: MPXJ is currently just reading the first rate from P6. I will look into adding support for multiple rates.

**Comment by joniles** [comment]
This functionality is now available in MPXJ 10.9.0.
