### ISSUE TITLE
getTimephasedWork reports negitive values for montly resource assignements

### ISSUE THREAD

**Issue by bmoore27** [joniles/mpxj#312]
I have an MPP file from MS Project 2019 that has a task assigned to 6 resources. Each resource has an allocation of 13 hours over 3 months.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/3245460/176322490-e2dbeeb0-344d-4fc0-ab5a-d714695e8b83.png">
Each resource has the 13 hours spread over 3 month interval as:

July: 4h      Aug: 4.6h    Sep: 4.4h which added together is 13h.

When I load the task and look at the resource assignement each has a total of 13 hours but when I try to get a monthly break down with getTimephaseWork() I get a breakdown like what is shown below:
July: 13h      Aug: -147h    Sep: -331h which doesn't match what MS Project shows.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/3245460/176322314-4b58b208-7734-422a-b450-8bcbfe44743d.png">

Is this a bug or have I missed something in how I should read timephasework?

**Comment by bmoore27** [comment]
I also noticed that getCurveValues returns null and getWorkContour returns `CONTOURED` for each ResourceAssignment.

**Comment by hendrik456** [comment]
I experience something similar; I have 36 hours of work between 17 April and 4 May
When I check the TimephasedWork of the ResourceAssignment, the amount per day is calculated incorrect.  Note the minus value of -341h at the end in amountPerDay on Thursday 4 May.

![image](https://user-images.githubusercontent.com/109575993/179677297-e50e54db-0724-4ad1-af35-58ebbca30cbd.png)

![image](https://user-images.githubusercontent.com/109575993/179677331-72982207-b593-4cdd-a91e-4aac7921d3ac.png)

But when I change the value of one day (21 April) from 2.25h to 3.25h the TimephasedWork of the ResourceAssignment shows the expected values in amountPerDay

![image](https://user-images.githubusercontent.com/109575993/179677350-b139e3b1-475f-4e0e-96f6-b0f3a3b2d2e9.png)

![image](https://user-images.githubusercontent.com/109575993/179677415-9c2fb8c5-9938-4805-beca-7fe5677a4e9d.png)

**Comment by joniles** [comment]
@hendrik456 would you be able to provide a sample file? Thanks!

**Comment by joniles** [comment]
Hi! I'm happy to take a closer look at this but unfortunately I do need to see some sample data in order to move forward. I haven't heard anything for a while so I'm going to close this issue for now. If you can attach a sample file here or email me with one I can re-open and take a look.

**Comment by bmoore27** [comment]
I can provide a sample file, I need a few minutes. I will get one posted today.

**Comment by joniles** [comment]
Hi @bmoore27, there were a number of timephased-related fixes in the last release of MPXJ, hopefully one of those may have solved the issue. If you can still reproduce the problem and can provide a sample file I can take another look.
