### ISSUE TITLE
Extended fields

### ISSUE THREAD

**Issue by lszoke66** [joniles/mpxj#316]

**Comment by joniles** [comment]
Hello! Not sure what happened to the original text, but the email notification contained the following question:

> Dear developers!
>
> I import MS Project files in a .net environment.
> I need the TEXT1 extended field, but I can't see it anywhere.
>Where/How can I get it?
>
> Thank you in advance for your help!

To access the TEXT1 field you'd use this method:

```c#
task.GetText(1);
```

Hope that helps!

**Comment by lszoke66** [comment]
Hi,
yes, in the meantime I also found the right method and it works great!
Thank you for answering !

Szőke László

Jon Iles ***@***.***> ezt írta (időpont: 2022. júl. 16., Szo,
2:59):
