### ISSUE TITLE
Latest version of MSProject and MPPReader.Read

### ISSUE THREAD

**Issue by bethfuruta** [joniles/mpxj#317]
[mpxjProblem.zip](https://github.com/joniles/mpxj/files/9252604/mpxjProblem.zip)

The attached schedule was created with the latest version of MS Project. It seems that an update to Project has messed up mpxj. In addition to the mpp, I have included the error message (ArrayIndexOutOfBoundsException) and the stackTrace indicating the problem is with mpxj.mpp.MPPUtility.getGUID line 278.

**Comment by rsinha9** [comment]
@joniles - we are seeing this as well. Btw I am happy to help maintain this piece in the long run if you could guide me on how you troubleshoot this

**Comment by joniles** [comment]
I've added a fix for this, it will be in the next version of MPXJ.

Thanks for the offer @rsinha9, much appreciated. In this case it was just a simple coding error - the bounds check for the array index was not correct. (Here's the diff https://github.com/joniles/mpxj/commit/4ba1646e1edbc850c5a7849c5f0a5cc36b9e0bfe)

**Comment by joniles** [comment]
BTW @rsinha9 - can you drop me an email - there is a link to my email address here https://www.mpxj.org/support/.
