### ISSUE TITLE
Activity codes not included in returned ProjectFile for PPX reader

### ISSUE THREAD

**Issue by cjohnspm** [joniles/mpxj#323]
I am using the UniversalProjectReader to read a Phoenix file (ppx).
The file has Activity Codes in it, but when the ProjectFile is returned from the read() call, using the getActivityCodes() method is always empty.

**Comment by rsinha9** [comment]
@joniles - looking into this further it looks like currently MPXJ is mapping the activity codes over to parent/child relationship based on the assigned activity codes. Is there any specific reason for this?

**Comment by joniles** [comment]
> looking into this further it looks like currently MPXJ is mapping the activity codes over to parent/child relationship based on the assigned activity codes. Is there any specific reason for this?

Yes, the code to work with Phoenix files was written some time before I added support for reading P6 activity codes. The original intention was to mimic the "default" hierarchical view Phoenix users see which is also, if I recall correctly, the way the schedule is organised if you export an MSPDI file from Phoenix.

Having now implemented support for activity codes for P6 and Powerproject, it would probably make sense to go back and re-do this for Phoenix. The default output when reading a Phoenix schedule would be a "flat" set of activities, with activity codes available to allow the schedule to be organised into a hierarchy according to the end user's requirements. I'd look to provide a flag to preserve the current behaviour for users who rely on this presently.

How does this approach sound?

**Comment by rsinha9** [comment]
Sounds like a plan to me. This is the road that @cjohnspm and I have started going down. We will get a PR put together and submitted.

**Comment by rsinha9** [comment]
PR #338 for this

**Comment by joniles** [comment]
Final changes implemented in https://github.com/joniles/mpxj/pull/353.
