### ISSUE TITLE
Import of Resource assignment property "Calculate costs from units"

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#368]
Hi,

In P6 there is a property on the resource assignment called "Calculate costs from units". When this is not selected one can input a cost on the resource assignment that won't be recalculated based on the units. 
![image](https://user-images.githubusercontent.com/9571179/194890720-5473c849-3d20-4638-804f-b883267e1afe.png)

This property comes into the .xer file as cost_qty_link_flag in the TASKRSRC table. 
In order to know how to emulate P6's calculation of the cost it would be useful to know this property. It doesn't however seem to be part of the mpxj model. Would it be possible to add it? Or is there some other way of knowing this value?

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Hello!  Just to confirm the changes to support this have been merged and will be available in the next release.
