### ISSUE TITLE
Python "UniversalProjectReader().read()" Report Log4j2 Error

### ISSUE THREAD

**Issue by ericsunplus** [joniles/mpxj#369]
Hi there,

I am setup in a new laptop for mpxj. The code running well before meet problems

The code snippet is as the following
```py
import jpype
import mpxj

destMPP = "example.mpp"
jpype.startJVM()
from net.sf.mpxj.reader import UniversalProjectReader

project = UniversalProjectReader().read(destMPP)    # error happens when executing to this line
jpype.shutdownJVM()
```
The error message is
```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```

My environment is
OS : WIN 10
PYTHON : 3.10.8 64bit
JPype1 : 1.4.0
mpxj : 10.11.0
JVM : Version 8 Update 341 64bit

Not sure what is going wrong in my config

**Comment by joniles** [comment]
Hello @ericsunplus! Thanks for the note.

MPXJ uses the Apache POI library to read MPP files. POI uses Log4j to provide logging, however this is not automatically enabled: only the log4j API is present by default. What you are seeing is simply a warning from log4j indicating that it only has the API, and any log messages passed to it will be written to the console.

You can safely ignore this error. If your project happened to be using log4j anyway, POI would have inherited your project's logging configuration and would write any messages it might produce to that log.

Hope that helps!

**Comment by ericsunplus** [comment]
Thanks @joniles for the quick help. I see the message starts with `Error` so don't though of checking my script's real output (another file). After checking it, the result is just fine.

So this seems just a warning message indicating `Log4j` is not available and jvm turn to use `SimpleLogger` instead. I am just using mpxj to parse and analysis project mpp file, so no other JVM context is there. Is it possible that I can install `Log4j` to my system to avoid this message?

**Comment by ericsunplus** [comment]
Works like a charm! Thank you @joniles
