### ISSUE TITLE
Specific error when reading timephased with calendar day 24 hours

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#371]
When we using 24 Hours Calendar and set, specify, 3 resource units which will give 72hrs, when reading and export to XML the value is 24hrs. Look below:
![Screenshot 2022-10-18 101143](https://user-images.githubusercontent.com/62966401/196441378-1057922c-2779-4b8b-90b0-f87b8da52227.png)
![Screenshot 2022-10-18 101311](https://user-images.githubusercontent.com/62966401/196441400-ba79c0f2-b446-4dea-8370-c0a937cbf360.png)
![Screenshot 2022-10-18 101225](https://user-images.githubusercontent.com/62966401/196441431-2d72e085-7ee0-4ca1-8398-4fbe594af9d3.png)

I was testing and replied a different situtation, set Standard Calendar (8hrs per day) and incresing resource units until give 72hrs. 
As result, this error not occurs. Look below:
![Screenshot 2022-10-18 101640](https://user-images.githubusercontent.com/62966401/196442290-86e13c27-a11a-4750-9a9b-3299783ea024.png)
![Screenshot 2022-10-18 101715](https://user-images.githubusercontent.com/62966401/196442353-e0c556f1-117e-4f8f-bfba-52d4d968bd05.png)
![Screenshot 2022-10-18 101611](https://user-images.githubusercontent.com/62966401/196442380-5ce262cb-8bee-48ba-974d-1d03fa7b7c4b.png)

**Comment by joniles** [comment]
@evertondevelop would you be able to send me a copy of the sample file? Thanks!

**Comment by evertondevelop** [comment]
Of course!

**Comment by joniles** [comment]
@evertondevelop I'm pleased to say that I have fixed this issue, the changes have been merged and will be in the next MPXJ release.
