### ISSUE TITLE
Additional Attributes does not exist in XML when extracted using a class MSPDIWriter.

### ISSUE THREAD

**Issue by SaromAndrade** [joniles/mpxj#373]
Adding attribute
![image](https://user-images.githubusercontent.com/48956569/197780999-907b244f-1444-4358-b5ef-3d9b77d636b5.png)

Attribute exists in class
![image](https://user-images.githubusercontent.com/48956569/197781409-be1d5138-6e9a-4c4e-a84b-46f991052f8a.png)
Extracting to XML
![image](https://user-images.githubusercontent.com/48956569/197782221-14336880-0ce2-4395-8144-21c3f26ac15d.png)
XML file
![image](https://user-images.githubusercontent.com/48956569/197782539-bcc8e6c5-7552-4993-8956-8f87a1516e0a.png)

**Comment by SaromAndrade** [comment]
File XER example:
https://drive.google.com/file/d/1ZA1B8aL7BeWhW0I5stxUMuEMPwkev4VK/view?usp=sharing

**Comment by diegosechin-timenow** [comment]
@joniles  you have idea when will see it?
If you need help to simulate or more informations, we are here to support you.

**Comment by joniles** [comment]
Hi, thanks for opening this issue, and apologies for the delay in responding.

As I understand it from your first screenshot you are reading an XER file and are adding an entry to the activity fields for Percent Complete type.

You should not need to make this change as the percent complete type is already read for you and converted to the appropriate enum value [here](https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/primavera/PrimaveraReader.java#L956).

The Percent Complete Type attribute is only relevant to P6 schedules, so MPXJ will read it from XER or PMXML files, and will write it to PMXML files, but it won't write it to an MSPDI file as MS Project does not have this concept.

Hope that helps!

Jon
