### ISSUE TITLE
MPP Exception

### ISSUE THREAD

**Issue by rsinha9** [joniles/mpxj#377]
We are seeing this exception on certain MPP files.
```
java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15\n\tat net.sf.mpxj.mpp.MPPUtility.getGUID(MPPUtility.java:300)\n\tat net.sf.mpxj.mpp.FieldMap$FieldItem.readFixedData(FieldMap.java:944)\n\tat net.sf.mpxj.mpp.FieldMap$FieldItem.read(FieldMap.java:756)\n\tat net.sf.mpxj.mpp.FieldMap.populateContainer(FieldMap.java:443)\n\tat net.sf.mpxj.mpp.MPP14Reader.processResourceData(MPP14Reader.java:1620)\n\tat net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:94)\n\tat net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:147)\n\tat net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:66)\n\tat com.construx.file.service.MppFileMetadata.getMetadataFile(MppFileMetadata.java:34)
```

Should https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/mpp/MPPUtility.java#L280 be data.length >= offset + 15 or data.length > offset + 15, because if we think about the case where data.length = 15 and offset = 0, the indexes should be from 0 to 14 and https://github.com/joniles/mpxj/blob/master/src/main/java/net/sf/mpxj/mpp/MPPUtility.java#L300 would assume that the offset of 0 and a length of 15 the indexes being retrieved would end up being 0 to 15.

**Comment by rsinha9** [comment]
I've created PR378 for this. I tested this against the file I am having issues with and also the file that was reported in issue 317 that switched this from a > to a >= and they both worked.

**Comment by joniles** [comment]
Thanks for the fix, I have merged your change.

**Comment by rsinha9** [comment]
@joniles - do you know when the next release will happen?

**Comment by joniles** [comment]
@rsinha9 released a couple of hours ago - let me know if you have any problems retrieving the new version.

**Comment by rsinha9** [comment]
Thanks @joniles ! All is good
