### ISSUE TITLE
Issue reading custom fields populated using a lookup

### ISSUE THREAD

**Issue by irbouho** [joniles/mpxj#38]
Hi,

I use the java version and this is reproducible using 7.2.0 and 7.2.1

I have a use case where I need my users to populate a field using a lookup (**Reporting Flag**), when I try to parse and read the content of the file, I am not able to read the values for the custom column (I get null).

I am able to read 'simple' custom columns where the value is a string (**Overall Rag**)

Below is a small code snippet to reproduce the issue, please find a screen shot of the file in the attachment. Reporting Flag has a lookup of values (Flag1, Flag2, Flag3 ...).

I am not able to attach the mpp to github, but let me know if you want me to send it by email.

![project](https://user-images.githubusercontent.com/1569824/35445125-a2313dd4-027e-11e8-8c68-fa300a1ae60e.jpg)

```java
import net.sf.mpxj.CustomField;
import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.Task;
import net.sf.mpxj.mpp.MPPReader;
import net.sf.mpxj.reader.ProjectReader;

import java.nio.file.Path;
import java.nio.file.Paths;

public class CustomFieldsMain {

	public static void main(String[] args) throws Exception {
		Path path = Paths.get("path to the file", "Project-1.mpp");

		ProjectReader reader = new MPPReader();
		final ProjectFile projectFile = reader.read(path.toFile());

		// print custom fields values for task# 1
		final Task task = projectFile.getTasks().getByUniqueID(1);
		System.out.println(task.getName());

		for (CustomField customField : projectFile.getCustomFields()) {
			System.out.printf("%s : %s\n", customField.getAlias(), task.getFieldByAlias(customField.getAlias()));
		}
	}

}
```

**Comment by irbouho** [comment]
@joniles , can you please let me know if this is something doable?

**Comment by joniles** [comment]
Hi @irbouho I will try to take a look at this next week.

**Comment by joniles** [comment]
I believe this issue is fixed by the code now committed to git. There will be an MPXJ release this week which contains the fix.

**Comment by irbouho** [comment]
This is great news, thank you!

**Comment by joniles** [comment]
The release is available now.

**Comment by irbouho** [comment]
@joniles, this is working as expected, thanks a ton!
