### ISSUE TITLE
UDF values ​​in WBS do not exist when extracted from PRIMAVERA XML format

### ISSUE THREAD

**Issue by SaromAndrade** [joniles/mpxj#380]
I'm trying to get the values ​​of the UDFs for the WBS, but which one I extract using the PrimaveraPMFileReader class
and saved in another XML format using the MSPDIWriter class, these values ​​do not appear.
NOTE: Values ​​appear normally when I use the XER file.

![image](https://user-images.githubusercontent.com/48956569/199299438-4169a93e-0018-426c-aaf9-2b687bd01051.png)
![image](https://user-images.githubusercontent.com/48956569/199299863-43afece0-1e23-4240-917c-c18e3496bc3d.png)
XML EXPORTED FROM PRIMAVERA

![image](https://user-images.githubusercontent.com/48956569/199300023-2be04045-cd87-4d17-ba87-670a86b09961.png)
![image](https://user-images.githubusercontent.com/48956569/199300272-3f445030-0317-4ebb-93ce-d8d7aeade7fa.png)
AFTER THE EXTRACTION PROCESS

![image](https://user-images.githubusercontent.com/48956569/199300591-ac4777f5-86a1-453e-931c-734d71a7a0f3.png)
EXPORTED XER

**Comment by SaromAndrade** [comment]
XMLs AND XER
https://drive.google.com/drive/folders/1PabkuI24YbhqzXyGXy4rt9WVZNmzNO-Q?usp=sharing

**Comment by diegosechin-timenow** [comment]
It's occurs with project too.

**Comment by diegosechin-timenow** [comment]
@joniles you have idea when will see it?
If you need help to simulate or more informations, we are here to support you.

**Comment by joniles** [comment]
Hello! Thanks for the bug report, and apologies for the delay in responding. I've merged a fix today which will ensure that UDF values will be read for WBS entries. The fix will be in the next MPXJ release so I'll close this issue for now.

Note that if you are using MPXJ's functionality to write PMXML files, unfortunately at the moment we won't be writing these UDF values for WBS entries, which is something I'll be tackling in future.

@diegosechin-timenow currently reading UDF values at the project level is not supported, however one of the first pieces of work I'm planning to tackle this year will enable this functionality.

**Comment by joniles** [comment]
Hello @diegosechin-timenow hope you are well. Just a quick note to let you know that I released MPXJ 11.0.0 today, which has the ability to read project level UDF values from P6 schedules. Enjoy!

**Comment by diegosechin-timenow** [comment]
Thanks @joniles .

We will update and test it soon.
