### ISSUE TITLE
Incorrect timephased work with even non-full split

### ISSUE THREAD

**Issue by mgubis** [joniles/mpxj#383]
Thanks a lot for the great library to read mpp file!

I am however experiencing issue with getting the timephased work. I have created simplified plan for proper testing (please find it attached to this issue): [mpxj-test.zip](https://github.com/joniles/mpxj/files/9978808/mpxj-test.zip)

The resource assignment uses only 50% of the daily capacity (4h instead of 8h):

![image](https://user-images.githubusercontent.com/35179604/201054657-79405db3-7bc0-49a7-be0b-211ee6560b78.png)

I am trying to extract this information from plan using this code:

![image](https://user-images.githubusercontent.com/35179604/201055072-83e41551-77d5-4889-95c9-62d93ca1c15e.png)

Works returned by the mpxj are:

![image](https://user-images.githubusercontent.com/35179604/201055333-7bc3089e-d92a-49f1-b3fc-752f3dbfe9b7.png)

This happens only when the split is even - in case I change one assignment to in example 2h instead of 4h, timephased work is reported correctly.

**Comment by joniles** [comment]
Hello! I _think_ I've fixed this issue, the changes have been merged and will be available in the next MPXJ release.

**Comment by mgubis** [comment]
I have upgraded NuGet and it works correctly. Thank you.

**Comment by joniles** [comment]
That's great news, thanks for letting me know.
