### ISSUE TITLE
Cannot read Task Status from 97-task mpp file

### ISSUE THREAD

**Issue by onepager-nblack** [joniles/mpxj#385]
In the the mpp file available here -- https://onepager.com/support/1170.mpp -- each of the 97 tasks has a Status. I read this file into a ProjectFile object using the UniversalProjectReader Read method. Then, for each Task theTask, I call

theTask.GetCurrentValue(TaskField.STATUS)

But instead of getting status values such as "Late", "Complete", etc., I get null for each task. This is in v10.12.0 of MPXJ for .NET.

**Comment by joniles** [comment]
Hello! The status field is actually a calculated field and it appears that Project doesn't cache this value in the MPP file... so there is nothing for MPXJ to read. I would like to add the necessary code to calculate the value for this field, but the logic used to determine the value (https://support.microsoft.com/en-us/office/status-task-field-769145ac-e052-45af-a847-e5ef15778bb1) relies on timephased cumulative percent complete, which we also don't have presently. I'll add it to my to-do list though!
