### ISSUE TITLE
Automatic scheduling

### ISSUE THREAD

**Issue by tesla-cat** [joniles/mpxj#393]
can mpxj do "Automatic event scheduling"?

as described here:

https://bryntum.com/docs/gantt/guide/engine/gantt_events_scheduling#automatic-event-scheduling

**Comment by joniles** [comment]
Unfortunately the URL returns a 404 for me. Is this the documentation you are referring to:

https://bryntum.com/products/gantt/docs/engine/classes/_docs_src_gantt_events_scheduling_.gantteventsscheduling.html

Assuming I'm looking at the correct thing the answer is no, MPXJ does not currently support recalculating the schedule. Having said that that, this type of functionality (basic critical path scheduling) is on the list of things I'd like MPXJ to be able to do.
