### ISSUE TITLE
Version 10.13.0 - When reading MPP file the timephased is empty

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#394]
When reading MPP file with calendar task and resource calendar is 24hours, there's no timephased. 

I looked deeper and it looks like when working times of day ends at 12:00AM (8:00AM-12:AM), this day is exclude from timephased list.
Obs: This happens when write to XML. Take a look below:

There's no timephased:
![Screenshot 2022-11-18 144531](https://user-images.githubusercontent.com/62966401/202769670-5243e0dd-1ab1-4bba-a748-c6a3b0645a7d.png)
![Screenshot 2022-11-18 144826](https://user-images.githubusercontent.com/62966401/202769679-927e7e87-c3b0-4ecf-ada6-ca233df37fae.png)

Exclude timephased:
![Screenshot 2022-11-18 144220](https://user-images.githubusercontent.com/62966401/202769893-fbd5d2eb-e534-4733-8255-728c3f593226.png)
![Screenshot 2022-11-18 144352](https://user-images.githubusercontent.com/62966401/202769907-c8cb2565-6789-41bf-8630-7834cdd4a2ed.png)

it's noted days 12/06/2022 and 12/08/2022 not ends 12:00AM. But 12/07/2022, it do.

I'll send both MPP files to your e-mail.

**Comment by joniles** [comment]
Thanks for the example files, they were very helpful. I've fixed the issue, the changes will be in the next MPXJ release.

**Comment by diegosechin-timenow** [comment]
@joniles you know when the version will be released?

**Comment by joniles** [comment]
I've just released it!
