### ISSUE TITLE
Version 10.13.0 - No write on MSPDIWriter

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#395]
When the library read and try write MPP File, it was like ifinite loop, it's wierd. I don't find out the exactly problem. Only pattern i could find is when MPP File contains 24hours calendar and increase a exception with day work and contain task calendar.

I'll send MPP File to your e-mail.

**Comment by joniles** [comment]
Thanks for the file, I've fixed the issue, the changes will be in the next MPXJ release.
