### ISSUE TITLE
Incorrect timephased data (units 0 suspected)

### ISSUE THREAD

**Issue by mgubis** [joniles/mpxj#404]
Thanks for the previous fix. I have run the mpxj with our test bench (we have approximately 3000 human-created plans) and came across problem with many plans (we are comparing data retrieved via COM interface and Mpxj). I have created one, which produces error - please find it attached: 
[221202-TestPlanFromScratch.zip](https://github.com/joniles/mpxj/files/10141952/221202-TestPlanFromScratch.zip)

Plan has single task and single resource with 77h of work:

![Screenshot1](https://user-images.githubusercontent.com/35179604/205317728-1d39baf3-e94d-44c8-ae5c-766d9c9bab09.png)

When I retrieve the timephased data I get all zeros:

![Screenshot2](https://user-images.githubusercontent.com/35179604/205317819-d680b878-eb51-495e-a381-2b352b6017de.png)

I suspect the problem is related to the fact, that the resource has 0% units (but I can't confirm it):

![image](https://user-images.githubusercontent.com/35179604/205318093-14a9873e-87ee-43db-a5b0-59f57552e4a6.png)

Please let me know in case I can provide more information - I will gladly do so.

Thanks.

**Comment by joniles** [comment]
Hi! Thanks for the bug report, I think I've fixed the issue, the changes have been merged and will be in the next MPXJ release.
