### ISSUE TITLE
Task Baseline Duration is equals to Task Duration

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#406]
Let me explain, even differents dates (Baseline and Task) a both durations is equals when read MSProject and convert to XML. Look at images below:
![Screenshot 2022-12-09 090320](https://user-images.githubusercontent.com/62966401/206715987-89452d2c-9b77-401d-8b50-8e464ce40825.png)
![Screenshot 2022-12-09 090341](https://user-images.githubusercontent.com/62966401/206716002-c945987a-2eac-499e-87db-b6ab871063ce.png)

Is it really this way ? Or is a bug ?

Thank you for your dedication to library!

**Comment by joniles** [comment]
Could you add a sample MPP file (or email one to me)? Thanks!

**Comment by evertondevelop** [comment]
Sorry to reply after so long. I'll send MPP file in e-mail and a image below to exemplify:
![Screenshot 2022-12-26 111357](https://user-images.githubusercontent.com/62966401/209557849-2ff64656-3c52-4687-935e-0cf67e7340b1.png)
![Screenshot 2022-12-26 112206](https://user-images.githubusercontent.com/62966401/209558187-744de123-56c6-4359-9655-f5a95e9d5ff4.png)
![Screenshot 2022-12-26 112222](https://user-images.githubusercontent.com/62966401/209558195-13cfce7e-7415-4659-bf54-e80083610d00.png)

I guess that Task Duration and Baseline Duration must be different. But they're same. 
Baseline Duration 8hrs and Task Duration 24hrs.

**Comment by joniles** [comment]
Just had a quick look at the sample file you sent through.

When viewed in Microsoft Project the Duration and Baseline Duration for the task are the same value. Is this what you were asking about?

These values don't make sense when you look at the Start/Finish Baseline Start/Baseline Finish dates. It looks like MS Project doesn't enforce the relationships between the baseline fields once they have been set, so if they are manually edited they may well be inconsistent. If I set the baseline using the "Project->Set Baseline..." menu in MS Project the baseline values are consistent, and remain consistent when I update the Duration/Start/Finish values on the task.

Let me know if I've been looking at the wrong thing!
