### ISSUE TITLE
An error in work duration when over 35,791,000 hrs

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#408]
I'll send MPP file in e-mail. Look at below:
![Screenshot 2022-12-26 110131](https://user-images.githubusercontent.com/62966401/209557013-f3eda50e-129e-43a0-8878-eb24112793de.png)
![Screenshot 2022-12-26 110433](https://user-images.githubusercontent.com/62966401/209557024-5fb74b61-516b-41a4-afa1-0366b8fa830e.png)
![Screenshot 2022-12-26 110456](https://user-images.githubusercontent.com/62966401/209557031-c3ecc329-af07-41c4-8fdd-591123b4f492.png)

Thank you for your dedication to library!

**Comment by joniles** [comment]
I've merged a fix for this, will be available in the next MPXJ release.
