### ISSUE TITLE
Incorret values TimePhased when there is Work Task but without resources (MSProject)

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#411]
Allright, it'll be take a long time. 
Unlike the other times, i don't get to identify a pattern. Here we go.

The tasks in line 2 and 4 contains the same values in columns as tasks in line 3 and 5, respectively. But tasks in line 2 and 4 have some days that no there is work when export to XML. The tasks in line 3 and 5 is correct. 
Look at below:
![Screenshot 2023-01-05 140209](https://user-images.githubusercontent.com/62966401/210840979-71a3af29-640e-4b72-b78e-cb04a4b26c77.png)
The marked days are the ones with errors.

![Screenshot 2023-01-05 135457-wbs-2 1 1](https://user-images.githubusercontent.com/62966401/210841266-ea4e3ae9-5ecf-431c-95d9-d5e55600610c.png)
XML from task in line 2

![Screenshot 2023-01-05 135653-wbs-9 1 1](https://user-images.githubusercontent.com/62966401/210841456-aa562ed4-18f7-4fde-b4d9-0c7afd5ba9ec.png)
XML from task in line 1

![Screenshot 2023-01-05 135837-wbs-2 3 1](https://user-images.githubusercontent.com/62966401/210841511-221199d6-a686-475d-b2ca-1f5a285ddbb4.png)
XML from task in line 4

I'll send mpp file to your e-mail.

I wish you a happy new year!
I hope you can help me.
Thank you for your dedication to library!

**Comment by diegosechin-timenow** [comment]
@joniles if you can support us in this item or show what we are doing wrong.

**Comment by joniles** [comment]
Hi @diegosechin-timenow - I'll set aside some time to look at this tomorrow.

**Comment by joniles** [comment]
Hello! I've merged a fix for this, it seems to work correctly for the test data you supplied. The change will be available in the next MPXJ release.

**Comment by diegosechin-timenow** [comment]
@joniles Thanks for your support.
