### ISSUE TITLE
The file or assembly 'mpxj-for-csharp,..could not be loaded

### ISSUE THREAD

**Issue by SantoshBhatLPS** [joniles/mpxj#449]
Hi one our users is experiencing an error trying to connect to and import from a MPP file. They are receiving an error that when translated from their language says 

> "The file or assembly 'mpxj-for-csharp, Version=10.10.0.0, Culture=neutral, PublicKeyToken=8783d630753e2b3f' or one of its dependencies could not be loaded. The specified file was not found"

The user has said this only occurs when performing the task on their "work" laptop, but do not face this problem when performing the same actions on their personal laptop. 

Any clues what could be the cuase?

**Comment by joniles** [comment]
Hello - that's an interesting one! At a guess from the description, I wonder if one of the MPXJ dependencies has fallen foul of a corporate AV product as this is a work laptop...

First question: would it be possible to produce a detailed stack trace from this error so we can determine if there is any additional context information that comes with it (hopefully which file it is having a problem with!)

If your user is amenable to running some diagnostics, there is a Microsoft tool we could try, with the catchy name `fuslogvw.exe` (https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer). It comes with Visual Studio, for me it was located in `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools`, and you'll also need  the `flogvwrc.dll` DLL which for me was in the `1033` sub directory alongside the exe.  Both of these files need be copied to the users machine into a directory.

The user will need to: 
* Run `fuslogvw.exe` as an administrator
* Click the settings button and select "log all binds to disk" and hit OK
* Run your application until they get the failure
* Hit refresh in `fuslogvw.exe`

All being well they'll get a list like this:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/4912864/223389727-b67bbfaf-e6ef-4911-94eb-f9e44cb2dbd3.png">

Double clicking each entry will open a web browser to display the log - the last one in the list should contain the failure (if not they'll need to click through the list to find the failure):

<img width="919" alt="image" src="https://user-images.githubusercontent.com/4912864/223390063-81082017-187b-4e59-baa5-e71c05d9d025.png">

With a bit of luck that'll give us some insight into why the assembly is failing to load.

**Comment by SantoshBhatLPS** [comment]
Thanks for the detailed steps. I'm not sure if we can ask our user to follow all those steps immediately. But you did hint that some AV might be the culprit, so perhaps we'll go back to them initially with that, then suggest we have a method to investigate that might require the above. Thanks for the help Jon!

**Comment by joniles** [comment]
As this issue has gone quiet, I'll close it for now. Feel free to reopen or create a new one if more information comes to light.
