### ISSUE TITLE
Expose Relation ID and Proj ID

### ISSUE THREAD

**Issue by forenpm** [joniles/mpxj#45]
I love your library!

I am wondering if you might be open to exposing some of the IDs when reading XER files.
The two I'm currently interested in are the Relation ID (integer) and the Project ID (integer).

I believe that would be adding "task_pred_id" to processPredecessors() and exposing "proj_id" in project properties.

It would be useful for tying back to the data source for BI.

Thank you for the work you put into this great library.  I would be happy to fork and contribute if I knew how the java -> C# build was done.

**Comment by joniles** [comment]
Hi! Thanks for the note.

I've updated the code to store `proj_id` as the `UniqueID` attribute which already existed in `ProjectProperties`. I'll take a look at theRelation ID next.

There are some build instructions [here](http://www.mpxj.org/howto-build.html) although I'm sure they could be improved.

I'll let you know when the Relation ID part is done.

**Comment by forenpm** [comment]
Oh wow, somehow I missed those build instructions.  That looks very easy, I'll definitely try it out.

Thank you for being open to making requested modifications.  If I am able to monetize what I'm doing, I'll make a donation.  This library saved me a lot of time in being able to import XER files.

**Comment by joniles** [comment]
I've added a "Unique ID" attribute to the `Relation` class, it should now be populate with the value you need when reading P6 data. I'll probably create a new MPXJ release this week.
