### ISSUE TITLE
WBS generated incorrectly if child comes before parent

### ISSUE THREAD

**Issue by chris-wright-nl** [joniles/mpxj#453]
Hi, 

We have been testing with an XER were the parent WBS comes after the child WBS in the `PROJWBS` table. This leads to the WBS field being created incorrectly. Hopefully this screenshot will help explain what I mean:

![image](https://user-images.githubusercontent.com/101633757/223443796-d1b4f005-d1b3-44cc-9c72-1a88859aebe3.png)

I believe that this error may occur due to how the table is processed in `PrimiveraReader` as there is this comment:

>       //
>       // Read WBS entries and create tasks.
>       // Note that the wbs list is supplied to us in the correct order.
>       //
      
Maybe  a check is needed to see if the `parent_wbs_id` exists and if not postpone until that has occurred. 

Or if MPXJ already handles this case and I'm doing something wrong, let me know. 

Thanks

Chris

**Comment by joniles** [comment]
Hello! Thanks for the bug report. Do you have a test XER file which exhibits the issue? Thanks!

**Comment by chris-wright-nl** [comment]
[MPXJ.zip](https://github.com/joniles/mpxj/files/10922723/MPXJ.zip)

Mock project which exhibits the same issue as found in our original XER.

Chris

**Comment by chris-wright-nl** [comment]
Awesome - Thanks! @joniles
