### ISSUE TITLE
A working day in Timephased does not exist

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#462]
Basically, when export .MPP file the day 1/23 does not exist on the timephased from XML. Look below:
![Screenshot 2023-03-20 181806](https://user-images.githubusercontent.com/62966401/226468967-28ba71e8-e0c7-45db-8782-d88f1f41bf2b.png)
![Screenshot 2023-03-20 181701](https://user-images.githubusercontent.com/62966401/226468997-de011389-8bdb-4703-8390-37db44c698e2.png)

I will send .MPP file by email.
Thanks for your support.

**Comment by joniles** [comment]
Hi! Thanks for opening the issue - sounds like an interesting one! I'll look at this as soon as I can.

**Comment by joniles** [comment]
Hello! It looks like related changes I made to fix the other timephased data issue may have fixed this. When I generate an MSPDI file from the sample MPP file with `writer.setSplitTimephasedAsDays(true);` I get an entry for each day, including 1/23. Let me know how you get on once the new release is available.
