### ISSUE TITLE
At Complete Duration is not correct in case it is different from Actual Duration + Remaining Duration

### ISSUE THREAD

**Issue by VipulADSK** [joniles/mpxj#468]
Hi @joniles,

We are working with a XER file and saw that the At Complete Duration which is visible on the P6 is different from what we get from the MPXJ. The special thing about this activity is that the At Complete Duration is not equal to Actual + Remaining Duration which is mostly the case for schedules. Attached image below

![image](https://user-images.githubusercontent.com/79574817/228141999-72426f65-0e0f-4d6e-8aa8-0927d58e7f15.png)

![image](https://user-images.githubusercontent.com/79574817/228142765-b43d2890-911f-4b79-825e-eff071b08002.png)

Do we know on why there is this mismatch! Your help would be appreciated. Attaching the Sample XER file.

[Sample Project.xer.zip](https://github.com/joniles/mpxj/files/11085879/Sample.Project.xer.zip)

**Comment by joniles** [comment]
Hi @VipulADSK thanks for opening the issue. I've merged a change which I believe will correct the At Completion Duration calculation. This will be in available in the next MPXJ release.
