### ISSUE TITLE
[BUG] Timephased start and finish is wrong when there's gap

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#478]
Hey, Jon. 
Some situations, like that, timephaseds not get exactly start and finish when there's gap
![image](https://user-images.githubusercontent.com/62966401/231476462-d3454ae8-492f-4327-99d1-b955c440858d.png)
In image above, we see a little bit work on the day 23. 
This case, i receive the XML below:
![image](https://user-images.githubusercontent.com/62966401/231477915-71711c6a-9970-45e7-b374-d348e8869b54.png)
I guess that be a little detail because to simulate it in a new .MPP file was hard because i was receiving correct timephased, look below:
![image](https://user-images.githubusercontent.com/62966401/231479627-db0ee1cc-7c75-4843-88ac-d2bf6cbd2102.png)

I hope i help you solved.
I'll send you .MPP file by e-mail.
Thank you for your dedication.

**Comment by diegosechin-timenow** [comment]
@joniles Perhaps could you fix it and deliver it in the release of this weekend?

**Comment by joniles** [comment]
@diegosechin-timenow unfortunately I'd almost completed the release process by the time this issue was opened.

@evertondevelop can you update to MPXJ 11.3.0 to see if this fixes the issues you opened previously, and with a bit of luck it might also fix this current issue!

**Comment by evertondevelop** [comment]
@joniles , unfortunately that issue is not solved with a new release.

**Comment by diegosechin-timenow** [comment]
@joniles tks for the other issues, we have tested it and it was solved.
We are consolidating the use the library and we have every kind of schedules, and the library was very consistent and useful.

Do you have a forecast of this fix?

**Comment by joniles** [comment]
@diegosechin-timenow I'll take a look this week.

**Comment by joniles** [comment]
I've merged a change which I believe fixes this issue. I'll start working on getting a new release out.

**Comment by diegosechin-timenow** [comment]
Thank you very much.
We will test it when it will be released.
