### ISSUE TITLE
XER file, P6 Location Attribute

### ISSUE THREAD

**Issue by michelespinella** [joniles/mpxj#479]
Good day all,
   we are using mpxj to import xer file from primavera P6, but on project object there is no method to get location. How we can get the location of the project?
Best regards
Michele Spinella

**Comment by joniles** [comment]
Hello! Unfortunately MPXJ doesn't support he location attribute currently, but this is something I should be able to add for the next release. I'll update this issue once I've added the functionality.

**Comment by michelespinella** [comment]
Great, thanks a lot. We are mapping a set of attributes, from rest API. If you want we share the mapping.
Michele

**Comment by joniles** [comment]
Would you be able to attach (or send me via email) a sample XER file and a sample PMXML file containing locations, ideally with project, activities etc with assigned locations? This will be very helpful for my testing. Thanks!

**Comment by michelespinella** [comment]
I will check the xer we are using to send, but I have only xer and not pmxml.
Thanks a lot

**Comment by joniles** [comment]
@michelespinella I had some time last night so I've implemented the necessary changes (https://github.com/joniles/mpxj/pull/480). I'll hold off merging until I've bee able to verify with a sample file.

**Comment by michelespinella** [comment]
I attach the xer file that we are using, let me know the file is ok.
[EC02016.zip](https://github.com/joniles/mpxj/files/11260218/EC02016.zip)

**Comment by joniles** [comment]
Many thanks for the sample data. I've confirmed the changes work, you'll be able to retrieve the location from the project after reading the XER file. The changes have been merged and will be in the next MPXJ release.
