### ISSUE TITLE
Processing UDFs from XER: Performance

### ISSUE THREAD

**Issue by forenpm** [joniles/mpxj#48]
Hey Jon,

I finally got around to forking and building this awesome project (jar and .NET).

The reason I did it was to debug some performance issues I am having.  Basically I have a huge client XER (350mb) that is taking ~2 hrs to process.

I discovered that the UDF processing is taking about 95% of that time, due to there being ~3 mil UDF rows.  Commenting out the loop in PrimaveraReader.getContainerUDF() takes that 2 hrs down to 4.5 min.  That method is called in two places and it's exponential based on the number of UDF rows.

I can keep my fork and leave it commented, since I don't need UDFs at this time, but thought you might like to know.  I'm not too familiar with Java, but some type of Dictionary with O(1) lookup (Map<int, List<Row>> maybe?) might be a good candidate for storing the UDF rows by ID?

Thanks!

**Comment by forenpm** [comment]
Hey Jon,
Thanks for looking at this so quickly.  The fix does indeed work! 2 hrs -> 3 min based on my last test.

I did have to initialize m_udfValues in readAll() though, as it wasn't being initialized (null ref).

Also, I do not use UDF values, so I don't have a way of testing that specifically, but the performance is great!

Thank you

**Comment by joniles** [comment]
Thanks for the heads up about `readAll`... wasn't covered by unit tests! I added support for reading UDFs from P6 databases, which lead me to refactor the code and tidy things up considerably. Anyway, to cut a long story short, I've merged the performance fix into the `master` branch so you should be good to use that. I'm hoping to get a new MPXJ release out later this week, which will also contain this fix. Let me know if you have any problems!
