### ISSUE TITLE
Unable to read outline codes and values of a task from c# lib

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#487]
Hello joniles, 
Hope you are doing good :)

We have an .xml and .mpp file which has some schedule and some assignment to outline codes. After converting these files using MPXj lib, we are unable to find out outline code and value of a task.

If you see below screenshot, ActivityCodes are empty, but CustomFields property has outline codes and values info and nothing on UserDefinedFields at project level, **Which property we should use to access the outline codes ?**
![image](https://user-images.githubusercontent.com/64011743/234571376-e90863b2-a1f1-4720-b0f5-f0a83b22d0ff.png)

When we access Task info, we dont see any property or method to read outline code and value info. 
But there is a method shown below giving outline value, but we need its code and value
![image](https://user-images.githubusercontent.com/64011743/234572862-5cc2b193-c684-4160-965e-fefb10678b7f.png)
**How to read outline codes and value of a task ?**

**And we need to read this info from .pp, .mpp, .xer files as well. Is there any common property we can use to find codes and values ?
We can see ActivityCodes property is there on task object, when this will be filled ?**

Below are the ref files
[Reference files.zip](https://github.com/joniles/mpxj/files/11332744/Reference.files.zip)

Thanks,
Dinesh

**Comment by joniles** [comment]
> Which property we should use to access the outline codes ?

With the MPP file example, you have three options for accessing the outline code. The first option is the one you have already identified: you can use the `getOutlineCode` method and pass in an index to select which outline code you need.

```java
task.getOutlineCode(1);
```

You also have the option of using the `get` method to pass in a value from the `TaskField` enum to select the field you are interested in:

```java
task.get(TaskField.OUTLINE_CODE1);
```

Finally, I see from your sample that the outline code fields have been renamed by the user. If you are expecting the user to have configured fields with specific names, you can use that name to retrieve the value you need.

The example below will work, but is inefficient as MPXJ is having to work out which field to read each time you call this method:

```java
// This is inefficient
Object value = task.getFieldByAlias("Zone");
```

A better way would be to determine the field which contains the data you want once, then use that field type each time you need to retrieve the value:

```java
// Do this once to look up the field type
FieldType type = projectFile.getTasks().getFieldTypeByAlias("Zone");

// Use the type each time you need to access this value
Object value = task.get(type);
```

With regard to accessing fields, you may find [this](https://www.mpxj.org/howto-use-fields/) documentation useful.

> And we need to read this info from .pp, .mpp, .xer files as well. Is there any common property we can use to find codes and values ?

Each of the file types you mention will store data in different ways. _If_ your users are adding the same attributes to each schedule and giving them consistent names (e.g. Zone, Location as shown in your example) then you can use the approach shown in the last example above to lookup the field by name, then retrieve the value it contains. This will work regardless of file type. If users are likely to be storing the information you need in different fields with inconsistent names, you might need to read the schedule to see what data it contains, and present the user with a UI to allow them to select the fields that you should be working with and indicate which values they contain.

> We can see ActivityCodes property is there on task object, when this will be filled ?

Activity codes are populated when reading schedules from P6, Asta Powerproject, or Phoenix.

**Comment by ndinesh231** [comment]
Thanks Jon, We tried above solutions and we are able to read activity codes and outline codes.
