### ISSUE TITLE
Incorrect parsing 

### ISSUE THREAD

**Issue by aohanhongzhi** [joniles/mpxj#488]
mmp file 

![image](https://user-images.githubusercontent.com/37319319/234856299-50a40978-7732-409b-8a87-dc9c19ba24aa.png)

result
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37319319/234856231-dc5fcc14-7868-4402-96b7-4dbbfccb5ee4.png">

**Comment by joniles** [comment]
Hello! Thanks for opening the issue. Could you attach the MPP file you are working with? Thanks!

**Comment by aohanhongzhi** [comment]
> Hello! Thanks for opening the issue. Could you attach the MPP file you are working with? Thanks!

thanks for you replay . I am so sorry for the issues. Due to the lower version I am using, so the  error occurred during parsing.
when I bump the version from 5.2.2 to 11.3.1. the issue has been solved. I am so sorry for that. pls close it .

**Comment by joniles** [comment]
No problem.
