### ISSUE TITLE
Powerproject files - Issue with bar and single task name

### ISSUE THREAD

**Issue by tomerweisman** [joniles/mpxj#489]
Hi, I see that when a single task is associated with a bar, the bar name is not added as a prefix to the task name (similar to the behavior in the powerproject software itself).
can it be changed so the task will have the bar name as well?

**Comment by tomerweisman** [comment]
actually, its a [setting](https://help.elecosoft.com/powerproject/english/16.0.02/Content/HTML_Topics/Conceptual/Starting_work/Entering_bar_and_task_names/Task_bar_names.htm) you can toggle on/off. So maybe its possible to have this option in mpxj as well.
Powerproject convention for the task name is - {bar name . task name}

**Comment by joniles** [comment]
Can you screenshot the setting so I can see where it is in Powerproject, and screenshot a view which shows names formatted with and without this setting enabled? Thanks!

**Comment by tomerweisman** [comment]
hi @joniles I think that this setting does something different than I thought, and if a task doesnt have a name, it inherits the name of the bar.  
I think it make sense also to add BarName to the Task Fields, this way we could append the bar name to the task name if needed...
wdyt?

**Comment by joniles** [comment]
Moving https://github.com/joniles/mpxj/issues/493 to here to maintain context.

> hi, @joniles
> can you please add the bar name to the taskFields?

I will take a look at this in due course.

**Comment by joniles** [comment]
@tomerweisman I've added a Bar Name attribute to `Task` which is populated when reading a Powerproject schedule. This change will be in the next version of MPXJ.

**Comment by tomerweisman** [comment]
amazing. thank you 👍🏼
