### ISSUE TITLE
Critical property inconsistency 

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#492]
Hi Jon,

We have .xer and .pmxml files which has same schedule ideally. But when we convert them using MPXj, critical property of a task is not consistence.

Its is giving false (which is correct) From xml, we are getting true from .xer.

Can you confirm what's going wrong here?

[RefFiles.zip](https://github.com/joniles/mpxj/files/11373946/RefFiles.zip)

Thanks,
Dinesh

**Comment by joniles** [comment]
Hi @ndinesh231 I've merged the change to fix this issue.

Jon

**Comment by ndinesh231** [comment]
Hi jon, May i know the version to get this update ?

Thanks,
Dinesh

**Comment by joniles** [comment]
Hi @ndinesh231, the change was in version 11.5.0, although if you are able to use a later version there are lots more fixes and improvements since then!

Jon
