### ISSUE TITLE
Calendar Working/Non-Working issue(s)

### ISSUE THREAD

**Issue by darthWes** [joniles/mpxj#498]
I'm seeing issues with calendar exceptions showing as non-working when they should be working.  I believe this is happening because there are multiple exceptions that apply to the same date, but this is not unreasonable.  For example, a user might declare every other Friday off.  Later, it might be determined that more work is needed to catch up to the plan, and certain Fridays be turned from non-working to working.  Nothing I do seems to reveal the source of my misunderstanding; thus, I believe this is a bug in mpxj related to multiple recurring exception types impacting a single date.  It seems that MS Project gives some kind of priority when the exceptions conflict, and, althought I cannot find documentation for this, I do see what MS Project reports when I bring up the calendar (See attached image)

I'll paste some simple code and a test file here, if anyone can shed light on this issue I would be thrilled.  Thanks.

```
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import net.sf.mpxj.ProjectCalendar;
import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.mpp.MPPReader;
import net.sf.mpxj.reader.ProjectReader;

/**
 * @author Wesley Lund
 *
 * A simple test to demonstrate the reading of a project file by mpxj and how
 * the non-working calendar dates do not seem to be correct. In my example, we
 * expect August 5, August 19, and August 21 (2022) to be working. However, the
 * 5th and 19th are reported as non-working.
 */
public class WorkingTest
{

    public static void main(String[] args) throws Exception
    {
        String fileName = "C:\\java_code\\projects\\Calendar Issue Test.mpp";

        ProjectReader reader = new MPPReader();
        ProjectFile project = reader.read(fileName);

        //Grab the Calendar
        ProjectCalendar myCal = project.getCalendarByName("TEST");

        //Use a constrained date range to demonstrate the specific issue(s)
        Calendar startCal = Calendar.getInstance();
        Calendar endCal = Calendar.getInstance();
        startCal.setTime(new GregorianCalendar(2022, 7, 1).getTime());
        endCal.setTime(new GregorianCalendar(2022, 7, 31).getTime());

        /**
         * Simple loop over the range to print the working/non-working status of
         * the individual dates in the range.
         */
        while (!startCal.after(endCal))
        {
            Date thisDate = startCal.getTime();
            boolean isWorking = (myCal.isWorkingDate(thisDate));

            System.out.println(thisDate + ": " + (isWorking ? "working" : "non-working"));

            /**
             * I had hoped to find the exception giving me different data for
             * the specific dates, but alas, they agree (as I believe is
             * intended) with the calendar's isWorkingDate result.
             */
            /*ProjectCalendarException myCalException = myCal.getException(thisDate);
            if (myCalException != null) {
                System.out.println(myCalException);
            }*/
            
            //move the while loop forward
            startCal.add(Calendar.DAY_OF_YEAR, 1);
        }
    }
}
```
[Calendar Issue Test.zip](https://github.com/joniles/mpxj/files/11425392/Calendar.Issue.Test.zip)
![MPP_Calendar_Issue](https://user-images.githubusercontent.com/1068944/236946124-4927eec9-5cd1-4490-8a4b-6ffad9a0386b.JPG)

**Comment by joniles** [comment]
@darthWes thanks for the thorough writeup, I will look at this as soon as I can.

**Comment by diegosechin-timenow** [comment]
Hi @darthWes between the calendars have common time? Cause, in the library, we got situations that combining the calendars, we got 0 time, what is correct, but, project works differently, they ignore the calendar of the resource when there is no common time between task calendar and resource calendar. Inclusivelly, MS Project shows a Message.

**Comment by joniles** [comment]
@darthWes I've merged a fix for this, will be in the next MPXJ release.

**Comment by darthWes** [comment]
Jon,

Thanks for taking a look at this; I appreciate it.

Now that we've got that done, I went on a journey to see if I could understand how the calendar exceptions were prioritized. I have determined how MSProject prioritizes multiple calendar exceptions impacting the same day, and it looks like this:

1. No exceptions, take base calendar information.
2. Daily exception
3. Yearly exception
4. Monthly exception
5. Weekly exception

Regardless of how any of us feels about that, that's how it's working. As if to prove this, MSProject restricts the use of more than one of the same recurrence types against any given date. i.e. One day can have only one "Daily" exception, only one "Yearly" exception, etc., etc.

I've compiled a few example files to demonstrate this. When I use (your newly modified) mpxj to examine these files, there are still outstanding issues, and I've zipped up my demonstration files and attached them here.

Specifically, all these project files have Friday May 12, 2023 as non-working. Unfortunately, that's not what I'm getting from (your newly modified) mpxj for the Yearly/Monthly example files. I believe the fact that the Daily and Weekly files are getting the correct answer is just happenstance. Somehow we have to implement the above priorities against the exceptions (using RecurrenceType available on the exceptions).

If anyone has the time and ability, implementing this change would be much appreciated.  Please find my example files zipped together on this comment, and thank you.


[Cal Exception Priority Examples.zip](https://github.com/joniles/mpxj/files/11467282/Cal.Exception.Priority.Examples.zip)
