### ISSUE TITLE
Baseline dates returning null value when reading from P6 XER file.

### ISSUE THREAD

**Issue by Mahesh572000** [joniles/mpxj#502]
Hi,
I am using mpxj library for my project. Where client provides me XER file and I have to read the file, projects, wbs, activities, relationships and import them to our internal tool. So basically what the issue is when I am reading all the tasks from p6 xer file I am filtering the activites from all the tasks. So when I am iterating each activity I am unable to read baseline start and finish dates which are both returning null values but I am able to read normal start and finish dates. I tried so many ways, methods in mpxj. The P6 version is 21 and when I am taking XER file the baseline was assigned before exporting. I also tried using task.getFieldByAlias("BL Project Start") it is also not working. I hope you understand my issue.
Thanks.

**Comment by joniles** [comment]
Hi,

thanks for opening this issue. When P6 creates a baseline for a schedule, it creates a separate copy of the current schedule in its database which is hidden from you in the P6 client. The problem you are encountering is that the XER file format does not contain a copy of this baseline schedule, so MPXJ can't populate the baseline attributes.

There are a couple of approaches you can take:

1. Export a PMXML file. When exporting an XML file from P6 you have the option of including baseline schedules. Providing the user performing the export has selected the correct baseline schedule, MPXJ will automatically read the baseline and populate the baseline attributes for the current schedule.

2. Export the baseline and current schedule separately. P6 does allow you to make the baseline schedule visible again within the P6 client, at which point you can export it as an XER file. You can also export the current schedule as an XER file. You can read them both using MPXJ, the set the baseline yourself:

```java
ProjectFile current = new UniversalProjectReader().read("current.xer");
ProjectFile baseline = new UniversalProjectReader().read("baseline.xer");
current.getProjectConfig().setBaselineStrategy(PrimaveraBaselineStrategy.PLANNED_DATES);
// current.getProjectConfig().setBaselineStrategy(PrimaveraBaselineStrategy.CURRENT_DATES);
current.setBaseline(baseline);
```
Note: P6 will read different dates from the baseline schedule depending on the Earned Value Calculation setting in the P6 client. The `setBaselineStrategy` method can be used as shown in the example above to select the correct approach. This setting is not available as part of the data exported from P6.
