### ISSUE TITLE
Question: compatibility  .NET 6 and up

### ISSUE THREAD

**Issue by DimitryOkken** [joniles/mpxj#521]
Hi Jon,

Does the 'net.sf.mpxj-for-csharp' package have (any) compatibility with .NET 6.0 (and/or newer versions)?
if not, might there be an ETA on this development?

Kind regards
Dimitry

**Comment by joniles** [comment]
Hi @DimitryOkken thanks for the note. MPXJ supports .NET 6 and later versions - I'm actually using it in a .NET 7 project myself.
