### ISSUE TITLE
Issue with Asta PP files when we build solution on docker (Linux)

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#536]
Hi jon, we are building the solution on docker with Linux platform. We are facing one problem with deliverables generated from the library
All the files are working fine but Asta PP files are failing with below error

**Unable to load shared library 'ikvm-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libikvm-native: No such file or directory.**

But it is working in development environment which is windows.

After checking the output directory on docker, ikvm-native DLL is missing.
Is this expected to not to have ikvm-native DLL on Linux docker build?
Does MPXj supports Linux platform ?
Is there any config we need to do while building the solution with docker to get this DLL in output folder?

Thanks,
Dinesh

**Comment by joniles** [comment]
Hello Dinesh!

The shared libraries you'll need are part of the nuget package:

<img width="299" alt="image" src="https://github.com/joniles/mpxj/assets/4912864/2a74e6a4-d4f6-42be-b7b7-d27bc8a97466">

(I opened the package using NuGet explorer: https://nuget.info/packages/net.sf.mpxj/12.0.0)

It may be that you'll need to ensure that your Visual Studio config copies the native libraries across to your target directory for all of the architectures you want to support.

**Comment by ndinesh231** [comment]
Hi @joniles ,
We configured everything to copy native libs to the target directory for linux. But no luck, still the same issue
**Unable to load shared library 'ikvm-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libikvm-native: No such file or directory
After try-catch**

How to resolve this ? 

Thanks,
Dinesh
