### ISSUE TITLE
In Java10 when writing MSPDI there is a ClassNotFoundException

### ISSUE THREAD

**Issue by quyifei** [joniles/mpxj#55]
The MSPDI writting works well in Java 8.  But in Java10 , there is an exception of ClassNotFoundException caused by the sentense " MSPDIWriter writer=new MSPDIWriter();" 

The codes are same, only the jave version is different.

**Comment by joniles** [comment]
Hi,

unfortunately this is fallout from the introduction of modules into Java. There are some detailed notes here:

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/46455026

I found that the `--add-modules java.xml.bind` command line option worked for me.

Jon

**Comment by quyifei** [comment]
Hello Joniles,

Yes  it works. Thank you so much!

Best Regards,
Yifei 
------------------------------------------------------------------
Sender:Jon Iles <notifications@github.com>
Sent at:2018 Jul 6 (Fri) 22:04
To:joniles/mpxj <mpxj@noreply.github.com>
Cc:quyifei <yifei.qu@aliyun.com>; Author <author@noreply.github.com>
Subject:Re: [joniles/mpxj] In Java10 when writing MSPDI there is a ClassNotFoundException (#55)

Hi,
unfortunately this is fallout from the introduction of modules into Java. There are some detailed notes here:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/46455026
I found that the --add-modules java.xml.bind command line option worked for me.
Jon
