### ISSUE TITLE
PercentageComplete property is incorrect for specific PP file 

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#553]
Hi @joniles 
Hope you are doing good,

We encountered a an issue with specific asta PP file where "PercentageComplete" is different compared to asta PP tool.
For example consider wp3 in below and see PercentageComplete complete is 89 (In fact all other properties related to percentage is 89)
![image](https://github.com/joniles/mpxj/assets/64011743/5c59752e-8d62-4560-a02a-17f9ae18a4f3)

When we load this file into MPXj its 44.5
![image](https://github.com/joniles/mpxj/assets/64011743/05b2e92e-e28f-4d13-b044-ab3dd0a6136b)

**Why PercentageComplete is different? Is there any logic behind this?** 

Please use below reference PP file.
[Asta Power Project PP.zip](https://github.com/joniles/mpxj/files/12378592/Asta.Power.Project.PP.zip)

Thanks,
Dinesh

**Comment by joniles** [comment]
@ndinesh231 thanks for opening the issue, I will take a look as soon as time allows.

**Comment by ndinesh231** [comment]
Hi @joniles 
Any update on this ?

Thanks,
Dinesh

**Comment by joniles** [comment]
I have started looking at this, and will continue working on a fix as time allows.

**Comment by joniles** [comment]
Hi @ndinesh231 I've made some changes which appear to fix the issue. The changes have been merged and will be part of the next MPXJ release.

**Comment by ndinesh231** [comment]
Hi @joniles 
Is it available in 12.1.3 release ? or upcoming release ?

Thanks,
Dinesh

**Comment by joniles** [comment]
Hi @ndinesh231 - I've just released version 12.2.0 which contains these fixes.
