### ISSUE TITLE
Property mapping from native files to MPXj

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#554]
Hi @joniles ,

Can you share information related to each MPXj property and its equivalent native file property for all entities(tasks, calendars, etc..)
This will help us on what we are importing from native file into our system through MPXj

Thanks,
Dinesh

**Comment by ndinesh231** [comment]
Hi @joniles 
Any update on this ?

Thanks,
Dinesh

**Comment by joniles** [comment]
Hi @ndinesh231. Not sure if you've seen the tables on these pages https://www.mpxj.org/field-guide/ and https://www.mpxj.org/mpp-field-guide/ . They're not the easiest to use (although they can be pasted into a spreadsheet for easier consumption). These give you an idea of which attributes are populated for each file type, which you may find helpful.

Documenting every individual attribute being read by MPXJ  would be a very large undertaking, which I wouldn't be able to accommodate in the time I have available to look after MPXJ. You can however find this information by reading the source, and I'd be happy to answer questions if you find anything in the source which is not obvious or lacks explanatory comments.
