### ISSUE TITLE
Invalid File Format on PowerProject file

### ISSUE THREAD

**Issue by tomerweisman** [joniles/mpxj#562]
Hi 
Im trying to read an Asta PowerProject file but im hitting this exception. When I open the file in Powerproject it reads it OK. 
any idea how to fix this issue on my side?
Thank you

```
Traceback (most recent call last):
File "UniversalProjectReader.java", line 134, in net.sf.mpxj.reader.UniversalProjectReader.read
java.lang.java.lang.NullPointerException: java.lang.NullPointerException: Cannot invoke "net.sf.mpxj.ProjectCalendar.getDuration(java.time.LocalDateTime, java.time.LocalDateTime)" because the return value of "net.sf.mpxj.Task.getEffectiveCalendar()" is null
```

**Comment by tomerweisman** [comment]
after poking around the codebase a little bit, I came across this flow:
![image](https://github.com/joniles/mpxj/assets/17765396/f6e99dc6-3037-4bfa-b891-bbbcee4e2f06)

the exception I get is because the task has no calender associated with it and the project doesnt have a default calender defined to fallback on. could it be that we should define a default calender before creating the tasks?

**Comment by joniles** [comment]
@tomerweisman thanks for opening the issue. Would you be able to provide me with a sample file which exhibits this behaviour, either attached here or email me something directly? Thanks!

**Comment by joniles** [comment]
@tomerweisman I've made some changes in a related area which may have an effect on the problem you've raised. These changes are now in git, and will be in the next MPXJ release. In the meantime I'm going to close this issue now as I can't investigate this further without a sample file to look at. Feel free to attach a file here or send me something directly if you would like me to look at this further.
