### ISSUE TITLE
Primavera XML - Relationship Lag Calendar

### ISSUE THREAD

**Issue by rsinha9** [joniles/mpxj#574]
It looks like relationship lag calendar is defined on the Project for Primavera XML files exported out of OPC which is correctly defined in the schema. It just is not mapped over to the CustomProperties since the CustomProperties is only dependent on ScheduleOptions.

Two Options:
1) I can update the ProjectProperties object to have a RelationshipLagCalendar with an enum on it and map it over.
2) I can update to map from the project level property into the CustomProperties

Let me know which one you prefer and I can implement and get a PR over to you.

**Comment by rsinha9** [comment]
I've implemented option #1, and I left the custom properties there. Let me know if you want any changes. Happy to make them.

**Comment by joniles** [comment]
@rsinha9 I'm (eventually) going to stop using custom properties for P6 configuration options, they'll all have their own attributes on the project, so option 2 is the best approach. I'll take a look at implementing this myself over the weekend, and will also add support read/write support for XER files.

**Comment by joniles** [comment]
Of course when I said option 2 above, what I actually meant was option 1. It's late here...

**Comment by joniles** [comment]
It looks like you've implemented the change, I'll take a look.

**Comment by rsinha9** [comment]
> Of course when I said option 2 above, what I actually meant was option 1. It's late here...

Not your fault, I preferred Option 2 so I made it Option 1 in an edit

**Comment by rsinha9** [comment]
> It looks like you've implemented the change, I'll take a look.

Yup, did it for both read/write. I left the original custom property there, but happy to remove it as well. I also added tests for all of them.

**Comment by joniles** [comment]
Thanks again for the PR - changes merged in https://github.com/joniles/mpxj/pull/576

**Comment by joniles** [comment]
I've just publish a new release which contains these changes.
