### ISSUE TITLE
Read Unit of Measure values

### ISSUE THREAD

**Issue by JanecekPetr** [joniles/mpxj#581]
At the very least in P6 each Resource (namely, Materials) can have a Unit of Measure (UMEASURE in XER). As far as I can see there is no way to read it in MPXJ. The only place where Unit of Measure is read is Expense Items when they're assigned to Tasks.

Resource.getUnit() always returns null, no matter where the resource was read from.

Would you please consider adding the Unit of Measure to Resources?

**Comment by joniles** [comment]
I started working on this a while back (https://github.com/joniles/mpxj/pull/582) I'll bring that branch up-to-date and finish it off.

**Comment by joniles** [comment]
The changes to read and write unit of measure have now been merged. Sadly it looks like the units of measure on expense items are just text labels and aren't validated against the master list of units of measure managed by P6.
