### ISSUE TITLE
A Unique ID clash is still possible for Relations

### ISSUE THREAD

**Issue by JanecekPetr** [joniles/mpxj#584]
I have a particularly nasty P6 XML file containing two completely different and unrelated Task Relations which have the same uniqueId (ObejctId).

Now, having seen https://github.com/joniles/mpxj/pull/540, I hoped that either automatically or after manually calling `projectFile.fixUniqueIdClashes();` this problem would go away. It does not, as it seems Relation objects are not part of this deduplication process.

Is that intentional? Should I just deduplicate it myself? If yes, what other objects are missing in the uniqueId deduplicatiom mechanism and I need to care about them?

**Comment by joniles** [comment]
Hello! I've update the code to fix this issue - the changes will be in the next release.
