### ISSUE TITLE
XER Writing Support

### ISSUE THREAD

**Issue by samirotiv** [joniles/mpxj#59]
Hi,

Is there any reason why writing to XERs is not supported? Is there a license issue or something? It would be really useful!

Happy to contribute to this if required.

Best,
Samir.

**Comment by joniles** [comment]
Hi Samir, thanks for the note.

I wasn't intending to support XER creation simply because I felt that I didn't understand the file format in enough detail to produce usable results. If you'd like to contribute an XER writer class I'd be very pleased to include it in MPXJ.

Thanks!

Jon
