### ISSUE TITLE
Non-default WBS separator

### ISSUE THREAD

**Issue by JanecekPetr** [joniles/mpxj#595]
Primavera has `<WBSCodeSeparator>.</WBSCodeSeparator>` in XML files (and `PROJECT.name_sep_char` in XER files I think) for setting a non-default WBS code separator char. MPXJ is not currently using this while reading not writing.

Obviously this is a low-priority thing, but it would be nice if MPXJ could respect the setting.

**Comment by joniles** [comment]
Done! This will be in the next MPXJ release.
