### ISSUE TITLE
WBS not read correctly during import of Microsoft Office Project 2003 file

### ISSUE THREAD

**Issue by andrebaaij** [joniles/mpxj#6]
During the import of a Microsoft Office Project 2003 file, the WBS of tasks are read correctly until the yellow part, after that they all WBS are _null_, I am using **mpxj-for-csharp 5.1.9** to import the mpp file:

![image](https://cloud.githubusercontent.com/assets/5176592/9833045/16ec689c-598a-11e5-9aa3-71455030f376.png)

I can't share the project file I have, due to confidentiality, I can of course try to replicate it in a different project file. I hope the image above gives you enough information. If not, let me know how I can help you further pinpoint the issue.

**Comment by joniles** [comment]
Just doing some housekeeping on old issues. Sorry this one is very old! I have tried to reproduce this with Project 2003 but with no luck. If by some chance this is still an issue after all these years, please feel free to give this a try with the latest version of MPXJ and let me know if it's still a problem!
