### ISSUE TITLE
Issue after publishing

### ISSUE THREAD

**Issue by AnupRaviP** [joniles/mpxj#62]
I am able to read values from MPP, but and publish it in my local machine, but while publishing in a different laptop got error "System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."

Did I miss something to add while packaging.

any help will be highly appreciated.

**Comment by joniles** [comment]
Are you still seeing this problem? If so, what version of MPXJ are you using?

**Comment by AnupRaviP** [comment]
Issue Solved,
Rolled back code to pre-MPXJ included version,
Updated Nugget Manager to latest Version and 
just added the minimal required MPXJ components to my existing code.
Now Working Fine. Thanks
