### ISSUE TITLE
Support for P6 project fields for activity Id generation

### ISSUE THREAD

**Issue by smacharacek** [joniles/mpxj#626]
Hi Jon,

would it be possible to add support for the following P6 fields used for generating task codes (in both XER and XML format)?

```
    <Project>
        ...
        <ActivityIdBasedOnSelectedActivity>1</ActivityIdBasedOnSelectedActivity>
        <ActivityIdIncrement>10</ActivityIdIncrement>
        <ActivityIdPrefix>A</ActivityIdPrefix>
        <ActivityIdSuffix>1000</ActivityIdSuffix>
        ...
```

I can see in the codebase that the dafaults are used when e.g.  exporting to XML:

```
      project.setActivityIdBasedOnSelectedActivity(Boolean.TRUE);
      project.setActivityIdIncrement(Integer.valueOf(10));
      project.setActivityIdPrefix("A");
      project.setActivityIdSuffix(Integer.valueOf(1000));
```
(i.e. those fields are not in `ProjectProperties`).

Thanks,
Simon

**Comment by joniles** [comment]
@smacharacek  - no problem, I should be able to get these into the next release.

**Comment by joniles** [comment]
Done! The new release including this change should be out today.
