### ISSUE TITLE
Incorrect timephased actual work data for material resources

### ISSUE THREAD

**Issue by ConstructionProject** [joniles/mpxj#63]
Hi Jon!
Please look at ActualWork timephased for Res2Material assignment (getting by assignment.TimephasedActualWork) in attachment.
List has 4 TimephasedItem(s). 2,3,4 have incorrect Start and Finish dates (outside of assignment start-finish range)   

[MPXJ_test7_SplittedTaskBug.zip](https://github.com/joniles/mpxj/files/2412414/MPXJ_test7_SplittedTaskBug.zip)

**Comment by ConstructionProject** [comment]
Hi Jon !
I have probably solved incorrect timephased data for material resources and wrong flag1-20 values on assignment level. I can send you java-source with modifications made and explain details. If it is still interesting for you - please write me to vgerya@gmail.com

**Comment by joniles** [comment]
I'm looking to close this issue - does the recent update fix this for you?

**Comment by ConstructionProject** [comment]
Yes, It is OK now, Thank you!


сб, 20 окт. 2018 г., 15:08 Jon Iles <notifications@github.com>:
