### ISSUE TITLE
MSPDI reader and writer will omit OutlineCode and LookupTable information

### ISSUE THREAD

**Issue by ndarlington** [joniles/mpxj#64]
Using Mpxj 7.6.2 (.net), if I read a .mpp file containing a simple lookup table, Mpxj can view it and extend it in memory with additional lookup values.

Reading an MSP 2016 generated .xml file with the same lookup table, results in saying that the ProjectFile has no lookup table or custom field information values, when opening the same .xml again into MSP 2016 still shows them correctly.

Writing either of these read ProjectFile instances to .xml with MSPDIWriter has the following observations:
- OutlineCodes project level element does not exist at all.
- ExtendedAttributes is incomplete and has a FieldID element reference that points nowhere.
- Ltuid and related elements are missing

SaveVersion is 14

Simplified read/write program:
```
using System;
using System.IO;
using net.sf.mpxj;
using net.sf.mpxj.mspdi;
using net.sf.mpxj.reader;

namespace mspdi {

    class Program {
        static void Main(string[] args) {
            FileInfo file = null;
            if (args.Length == 1)
                file = new FileInfo(args[0]);

            if (file != null && file.Exists)
                ConvertUsingMpxj(file.FullName);
            else
                ShowUsage();
        }

        private static void ConvertUsingMpxj(string filename) {

            if (string.IsNullOrEmpty(filename)) {
                ShowUsage();
                return;
            }

            // If .mpp then lookup table exists, if .xml it does not (even though MSP 2016 shows it when opening the same .xml file)
            var reader = new UniversalProjectReader();
            var project = reader.read(filename);

            Console.WriteLine($"Has lookup table: {project.CustomFields.GetCustomField(TaskField.TEXT1)?.LookupTable}");

            // Neither .mpp or .xml as source when written out using MSPDIWriter is having the custom field and lookups in the generated .xml
            var writer = new MSPDIWriter {SaveVersion = SaveVersion.Project2016};
            writer.write(project, filename + "-converted.xml");

            Console.WriteLine("Finished");
        }

        private static void ShowUsage() => Console.WriteLine("Usage: mspdi [filename]");
    }

}
```

Console output showing detection of lookup table w/MPP reader
```
D:\Projects\mpxj\mspdi\bin\Debug>mspdi c:\temp\Project2.mpp
Has lookup table: [[CustomFieldValueItem uniqueID=1 guid=0191cf35-78c6-e811-afd5-001fbc126620 parentId=0 value=Yes, [CustomFieldValueItem uniqueID=2 guid=0291cf35-78c6-e811-afd5-001fbc126620 parentId=0 value=No]
Finished
```

Console output of identical project saved as .xml in MSP (and persists when re-opening in MSP):
```
D:\Projects\mpxj\mspdi\bin\Debug>mspdi c:\temp\Project2.xml
Has lookup table: []
Finished
```

Excerpt of resulting .xml file generated by MSPDIWriter:
```
    <ExtendedAttributes>
        <ExtendedAttribute>
            <FieldID>188743731</FieldID>
            <FieldName>Text1</FieldName>
        </ExtendedAttribute>
    </ExtendedAttributes>
```

Files used and generated:
[project2-before-and-after.zip](https://github.com/joniles/mpxj/files/2440435/project2-before-and-after.zip)

**Comment by ndarlington** [comment]
I also tried using specific readers (MPPReader and MSPDIReader) instead of UniversalProjectReader just in case.

**Comment by ndarlington** [comment]
It looks like these references are applicable despite their relative age:
https://stackoverflow.com/questions/9871906/write-outline-codes-with-mpxj-to-a-xml-file-and-import-it-to-ms-project-2003-200
https://sourceforge.net/p/mpxj/bugs/197/

I would be tempted to apply the suggested patch to a recent version myself to try it out, but I'm afraid my ignorance for how to build the IKVM part for a .net library of MPXJ holds me back.

**Comment by joniles** [comment]
Hello! Thanks for the extensive notes. Unfortunately the attributes you mention are not currently read/written for MSPDI files. I can start looking at implementing support but it's going to take me a while. What is the highest priority item?

**Comment by ndarlington** [comment]
Thanks Jon, I appreciate your interest in this.

Our primary (and I'll have to see if it's not our only) need will be reading and writing the Lookup Table types against their supporting records:

![image](https://user-images.githubusercontent.com/40403963/46678488-5c680580-cbaa-11e8-9458-5dbb2debb738.png)

I think the MPP reader gives us some if not all of this already?  I haven't pursued it fully yet as I got stuck on the MSPDI part, but I could see the lookup table definition was there at least.

So in the ProjectFile we want to populate the lookup table and then from the Text1-Text30 fields be able to reference them, and write that out in the MSPDI writer much as I have it in the example project2.xml attached in the first post.

We'll be creating that .xml file, letting the MSP users make their project changes including the choosing of different values from the lookup table (or making it blank/null), then when they are saving (to .mpp generally) we're reading it back in and updating the central server.

These lookup tables have options to be mapped at project, resource, task, and resourceassignment levels (though MSP restrictions on that may overrule it), with task and resource being the main ones.

It's a fairly typical use case I guess? That scope would get us far, not sure if we could narrow it down further at this point other than any natural barriers put up by MSP (2013-2016+).

**Comment by ndarlington** [comment]
Not that I think it matters much as far as the read/write implementation, but users won't be able to add additional items to the lists, they'll get only what is available from the start when they begin working on the project.

**Comment by joniles** [comment]
I have just merged changes which allow outline code/custom field lookup tables to be read from and written to MSPDI files.
