### ISSUE TITLE
XER: proj_node_flag is not being set

### ISSUE THREAD

**Issue by JanecekPetr** [joniles/mpxj#652]
When writing XER files with mpxj, the `proj_node_flag` in WBS section is currently always `false`. The flag should be `true` when the WBS is a root node of a project. Oracle Primavera Cloud currently requires this.

In single-project files, this means when `parent_wbs_id` is `null`, `proj_node_flag` should be `true`.  
In multi-project files, this is of course more interesting and the easiest naive rule, I think, is that if the parent WBS is from a different project, the `proj_node_flag` should be true.

**Comment by joniles** [comment]
I've updated MPXJ to handle the single project case, so the `proj_node_flag` should be set appropriately.

**Comment by JanecekPetr** [comment]
Thank you for your continuing support!
