### ISSUE TITLE
Add Comment field to net.sf.mpxj.Relation 

### ISSUE THREAD

**Issue by alex-matatov** [joniles/mpxj#659]
Hi Jon,

Would it be possible to add `comment` field to `net.sf.mpxj.Relation` and provide possibility to set/get it ? 

Thanks,
Alex

**Comment by joniles** [comment]
I can do that, it'll probably be next week before it's available, hope that's ok.

Jon

**Comment by alex-matatov** [comment]
Thank you!

**Comment by joniles** [comment]
The changes to support this have been merged, and will be available in the next release. The attribute on the class is named "notes" for consistency with the other classes in MPXJ.
