### ISSUE TITLE
PrimaveraPMProjectWriter: save [Actual|Planned]LaborUnits fields

### ISSUE THREAD

**Issue by alex-matatov** [joniles/mpxj#662]
Hi Jon,

Would it be possible to save `Activity.plannedWork` (or `PlannedLaborUnits`/`PlannedNonLaborUnits`) and `Activity.actualWork` (or `ActualLaborUnits`/`ActualNonLaborUnits`) in  `PrimaveraPMProjectWriter.writeActivity(Task mpxj)` ? 

Thanks,
Alex

**Comment by JanecekPetr** [comment]
(related to #664 and #665)

**Comment by joniles** [comment]
@alex-matatov I have implemented this, see the discussion in https://github.com/joniles/mpxj/issues/664 for details.

**Comment by alex-matatov** [comment]
Thank you!
