### ISSUE TITLE
Missing TimePhased conversion to XML in C#

### ISSUE THREAD

**Issue by juanlp** [joniles/mpxj#667]
Can anyone please point me to the right syntax for writing to XML with TimePhasedData in C#

**Comment by joniles** [comment]
@juanlp thanks for the request, I will make some notes for you in the next day or so to explain how timephased data can be used now, and the changes I'm planning to make shortly in this area.

**Comment by joniles** [comment]
Hi @juanlp, I've written some sample code for you illustrating various scenarios using timephased actual and remaining work. Unfortunately the sample is current just Java, I haven't had the time to create a C# version, but hopefully you'll find it simple enough to translate. I'll let you know if I have the opportunity to update this to C# myself.

You'll find code the code [here](https://github.com/joniles/mpxj-java-samples/blob/main/src/main/java/org/mpxj/timephased/WriteTimephasedData.java)

Here's what the output looks like when opened in MS Project:

<img width="648" alt="image" src="https://github.com/joniles/mpxj/assets/4912864/f4b8dd9b-e2ac-49f1-b385-29deafaa7b55">

Here's the timephased work and actual work breakdown, as illustrated in MS Project:

<img width="1028" alt="image" src="https://github.com/joniles/mpxj/assets/4912864/b6433130-42aa-47b0-b79a-71939e4f5f8e">

Timephased data is an area I'm actively working on, so some of the APIs shown here may change.
