### ISSUE TITLE
PrimaveraPMProjectWriter: set "ResourceAssignment.ResourceType" tag

### ISSUE THREAD

**Issue by alex-matatov** [joniles/mpxj#685]
Hi Jon,

There is a small MPXJ/P6-XML `ResourceAssignment` export issue…  

Primavera P6 wants to see `ResourceAssignment.ResourceType` attribute in XML file. Otherwise it shows all ResourceAssignments as `Labor` . For XER everything is fine.

![image](https://github.com/joniles/mpxj/assets/50991460/c7625667-fee5-440e-adf2-9d8406eaab70)

Hopefully, the fix is really simple and trivial. It is just enough to add the line below to `mpxj/src/main/java/net/sf/mpxj/primavera/PrimaveraPMProjectWriter.java` 

```
private void writeAssignment(ResourceAssignment mpxj) {
….
xml.setResourceType(ResourceTypeHelper.getXmlFromInstance(mpxj.getResource().getType()));
```

Do you think it would be possible to do ?

Cheers,
Alex

**Comment by joniles** [comment]
Done! The change will be available in the next release, hopefully in the next few days.

**Comment by alex-matatov** [comment]
Thank you!
