### ISSUE TITLE
MPXJ outputs empty start/finish dates for specific file

### ISSUE THREAD

**Issue by MadaraUchiha** [joniles/mpxj#691]
Using both `UniversalProjectReader` and `PrimaveraXERFileReader` when I try to parse the attached file `Norbis 01.xer` MPXJ outputs empty start/finish dates for every activity. When opening the same file in P6 it appears correctly. When exporting the same project from my P6 instance (version 21.x) MPXJ reads the file correctly (attached as `Norbis 02.xer`).

Faulty project was exported normally from Primavera P6 version 20.12.18.45982.

[empty-dates.zip](https://github.com/joniles/mpxj/files/15092874/empty-dates.zip)

**Comment by joniles** [comment]
Hi, thanks for opening the issue. The problem stems from a datetime format in the XER file which doesn't match what MPXJ is expecting. I have a fix and will try and get a new release out with the change as soon as I can.

**Comment by joniles** [comment]
Just to confirm, the fix has been merged, I will publish a new release later.

**Comment by MadaraUchiha** [comment]
Thank you very much! <3
