### ISSUE TITLE
`getPredecessors` throws NullPointerException

### ISSUE THREAD

**Issue by freddie-freeloader** [joniles/mpxj#7]
When there are no Predecessors of a `task`, `task.getPredecessors` throws a NullPointerException.
One might expect instead an empty list.

**Comment by joniles** [comment]
Just to clarify... calling `task.getPredecessors` throws a `NullPointerException`, or the method returns `null`?

**Comment by freddie-freeloader** [comment]
I got it wrong first.
It returns `null`, which is a bit unhandy, when you do something like: 
```java
for(Relation relation : task.getPredecessors) {...}
```

But it's mostly unhandy, not unreasonable. Thanks for the quick reply!

**Comment by joniles** [comment]
Thanks for the feedback. Just to confirm I've just updated the code to ensure that MPXJ will return an empty list rather than null for task predecessors and successors.

**Comment by freddie-freeloader** [comment]
Cool! Thanks a lot!
