### ISSUE TITLE
XER Writer/RelationshipLagCalendar - incorrect value for "TWENTY_FOUR_HOUR"

### ISSUE THREAD

**Issue by alex-matatov** [joniles/mpxj#700]
Hi Jon,

`net/sf/mpxj/primavera/RelationshipLagCalendarHelper.java` has incorrect value for `RelationshipLagCalendar.TWENTY_FOUR_HOUR`. Due to it P6 ignores it in Scheduler/Options and uses default "rcal_Successor" one.
 
Fix is very simple => Instead of `rcal_24hour` should be `rcal_24Hour`.

 ```
...
TYPE_XER_MAP.put(RelationshipLagCalendar.TWENTY_FOUR_HOUR, "rcal_24Hour");
```

**Comment by joniles** [comment]
Hi Alex - many thanks for picking that up. I've merged the suggested change. I'll probably be able to get a new release out this week.

Jon
