### ISSUE TITLE
[QUESTION - MS PROJECT] - Start and finish dates not being respected by their dependencies

### ISSUE THREAD

**Issue by pedrohcarvalhom** [joniles/mpxj#710]
Hey, I have a question about the task attributes in Ruby MPXJ.

I have two tasks that have a FS relation with 0 lag between them. For example: The first task starts at day 10, and his successor starts at day 11. In MS Project, we can edit the successor to start before day 10, disrespecting the FS Relation constraint.

Is there a prop in MPXJ Task that we can get the "correct" start and finish dates from the successor task? Thanks in advance!

**Comment by joniles** [comment]
Hi, apologies for the delay in responding. I had a quick play with MS Project to see if I could reproduce the scenario you describe, and from there look at what dates are available. Unfortunately in the couple of versions of Project I tried, Project itself wouldn't allow me to keep the link between the tasks while moving the successor back:
<img width="403" alt="image" src="https://github.com/joniles/mpxj/assets/4912864/96c2ac52-bc32-49ed-8c59-a5e7025ccde7">
You can add a negative lag to achieve the effect you describe, but I'm not sure if that was what you had in mind. Can you create a sample MPP file which illustrates the kind of change you describe?

**Comment by joniles** [comment]
Hi, I haven't heard back from you in a while so I'm going to close this issue. Feel free to add more notes here if you create a sample file.
