### ISSUE TITLE
[ISSUE] Converting .MPP to XER

### ISSUE THREAD

**Issue by saucedasf** [joniles/mpxj#711]
I am trying to create an MPP to XER converter, however the output doesn't seem to be properly converting, I go to import into P6 and it gets stuck on the "Finish" screen. I opened the output Xer in a text editor and it seems to be slightly out of line but I don't see any major issues to why P6 can't recognize the project.
Using V13.0.0 of MPXJ.Net 

Any help appreciated.

![image](https://github.com/joniles/mpxj/assets/121167287/f38f5045-ab45-43b1-a2c3-4dbedb82a8a2)

**Comment by joniles** [comment]
Hello! Thanks for opening the issue. Can you provide a sample MPP file and the XER file you're generating from it. Feel free to send them directly to me via email if you'd prefer not to make them public.

**Comment by saucedasf** [comment]
Thank you heaps, email sent.

**Comment by joniles** [comment]
Thanks for the sample file - that was very helpful. I identified two issues, which I believe I have now fixed, and I can now import the converted sample file to P6. I have some more testing to work through, and once that's done I'll create a new release containing the fixes.

**Comment by joniles** [comment]
Hi, MPXJ 13.0.1 is now available with fixes for the issue you encountered. Let me know how you get on!
