### ISSUE TITLE
Issue with getting `getUniqueIdObjectSequence`

### ISSUE THREAD

**Issue by smacharacek** [joniles/mpxj#716]
We have a scenario when we read the project and then we add new UDFs - and we are getting unique ids this way:

`project.getUniqueIdObjectSequence(UserDefinedField.class).getNext()`

And we get id = 1 even though the orginal file had UDFs.
(The issue also applies to other entities than UDFs).

The root cause is that `net.sf.mpxj.ProjectFile#getUniqueIdObjectSequence` uses internally map with `Class` type as key which is problematic for us (and IMO in general) - the class we pass to the method is loaded by a different classloader than the original class used when reading the project.

Would it be possible to use className as a key instead to avoid classloder issues? I.e. st. like this

```

private final Map<String, ObjectSequence> m_uniqueIdObjectSequences = new HashMap<>();

...

public ObjectSequence getUniqueIdObjectSequence(Class<?> c)
   {
      return m_uniqueIdObjectSequences.computeIfAbsent(c.getName(), x -> new ObjectSequence(1));
   }
```

**Comment by joniles** [comment]
Hi Simon - thank makes perfect sense, I hadn't thought about issues stemming from using multiple class loaders, I'll get your suggested change made shortly.

**Comment by joniles** [comment]
Hello! I've just merged a change based on your suggestion, which will be available in the next MPXJ release.
