### ISSUE TITLE
Missing clean way of adding ActivityCodeValue to ActivityCode

### ISSUE THREAD

**Issue by lnevaril** [joniles/mpxj#732]
When migrating to the latest version 13.1.0, I noticed the changes in the assignment of `ActivityCodeValue` to `ActivityCode`. In older library versions the method `addValue(Integer uniqueID, Integer sequenceNumber, String name, String description, Color color)` was deprecated and it is now completely removed. Documentation for the deprecation was as follows `@deprecated use ActivityCodeValue.Builder and pass result to addValue(ActivityCodeValue) method` but in the end there is no method `addValue(ActivityCodeValue)` and one has to use `activityCode.getValues().add(activityCodeValue)` to add new `ActivityCodeValue` to ensure it will be included in the exported file.
This is more like a suggestion to add new method `addValue(ActivityCodeValue)` as initially intended based on the deprecation comment to have a cleaner way for adding new `ActivityCodeValue`s since one has to first verify that `activityCode.getValues()` is returning mutable collection.

**Comment by joniles** [comment]
Hello! Thanks for the feedback, I've added `the `addValue` method as suggested, the change will be in the next release.
