### ISSUE TITLE
MPP: Incorrect Timephased work in Manual task mode

### ISSUE THREAD

**Issue by Fabian-Schmidt** [joniles/mpxj#733]
Hi,
Thank you for this library.
I am using the MPXJ library to read time phased work from MPP files. I encountered an issue when reading the work via MPXJ. It does not match what is reported in Project in the Task usage view.

Simplified scenario is as follow:

1. New blank Project.
2. Create a Task and Resource and create a 3 day assignment. The task is by default in manual schedule mode.
3. Modify the start time from 8:00(default) to 7:00. Manual task mode allows this change. Auto scheduled will not allow this change as it is outside of the work calendar.

|             | Day 1 | Day 2 | Day 3 |
| -------- | - | -| - | 
| Project | 9h | 8h | 7h |
| MPXJ                                                      | 8.3478..h | 8.3478..h | 7.3043..h |
| MPXJ with setUseRawTimephasedData | 8.3478..h | 8.3478..h | 8.3478..h |

The sum is correct but the distribution is wrong.

I am using the latest .NET version of the MPXJ library.

MPP example file:
[ManualTaskTimephasedv2.zip](https://github.com/user-attachments/files/16521618/ManualTaskTimephasedv2.zip)

**Comment by joniles** [comment]
Hello! Thanks for opening this issue. The timephased work handling code in MPXJ does have some shortcomings and I am planning to begin overhauling this code in the next few months to address this and other related problems. Apologies that this won't be a short term fix.

In the meantime you can try setting the "Use Raw Timephased Data" flag to true:

```java
MPPReader reader = new MPPReader();
reader.setUseRawTimephasedData(true)
```

this should give you the data exactly as it is represented in MS Project, but you will probably need to write your own code  merge/segment it into the timescale you need.

I will update this issue once I have made progress with the longer term work on improving timephased data handling.

**Comment by Fabian-Schmidt** [comment]
Thanks for the quick response.
When using "Use Raw Timephased Data" the result is worse. As it reads `8.3478..h` for every day. So the sum does no longer match.
I updated the first message with this new data.
