### ISSUE TITLE
Primavera Resources shifts not being parsed 

### ISSUE THREAD

**Issue by soumilbaldota** [joniles/mpxj#742]
What are shifts in resources:
[Oracle Docs](https://docs.oracle.com/cd/F37128_01/English/User_Guides/p6_pro_user/helpmain.htm?toc.htm?define_resource_shifts.htm)
Hi, I recently started using mpxj and would like to use resources with shifts to be parsed /  the starts and ends to be correctly parsed when shifts exist, currently the shifts cause the starts to begin after the end time.

I have added a sample plan with shifts in the resources here.
[sample.zip](https://github.com/user-attachments/files/16760438/sample.zip)

**Comment by joniles** [comment]
Hello! Thanks for the request, I will take a look at implement support for shifts over the next coupld of weeks.

**Comment by soumilbaldota** [comment]
@joniles Thank you.

**Comment by soumilbaldota** [comment]
@joniles Have started working on this? would love to use this feature.

**Comment by joniles** [comment]
@soumilbaldota I'm aiming to have the changes how have requested available next week.

**Comment by joniles** [comment]
I've just merged the changes for this, they will be available in the next MPXJ release which I'm aiming to get out this week.

**Comment by soumilbaldota** [comment]
@joniles That is great to hear, looking forward to test them out.
