### ISSUE TITLE
Scheduling Options not Accessible.

### ISSUE THREAD

**Issue by amarkssmartpm** [joniles/mpxj#744]
The Retain Logic and Progress Override flags are not accessible.  I don't see them being set anywhere from the Phoenix reader.  I would suspect they should be set in the ProjectProperties object.

**Comment by amarkssmartpm** [comment]
BTW this is for reading Phoenix schedules.

**Comment by joniles** [comment]
Thanks for raising this, I'll take a look as soon as I can.

**Comment by joniles** [comment]
I've merged a change which will populate the Scheduling Progressed Activities project property based on the settings from the Phoenix schedule. Using the getter method you should see either `SchedulingProgressedActivities.RETAINED_LOGIC` or `SchedulingProgressedActivities.PROGRESS_OVERRIDE` returned.

Unfortunately I won't be in a position to create a new release containing this change until 16th September.
