### ISSUE TITLE
Is it possible to reschedule in auto planning mode?

### ISSUE THREAD

**Issue by szadev** [joniles/mpxj#747]
Hello. 

I am using .Net, when I change the end date of a task, the linked task is not shifted automatically. Am I understanding correctly that there is no such functionality as of today. If so, if there is any information on when such a thing might become available?

Sorry, I couldn't find information about my problem, but I saw one ticket closed in 22 with an answer similar to what I'm looking for.

**Comment by joniles** [comment]
I think you've joined the conversation over at https://github.com/joniles/mpxj/issues/745 so I'll close this issue, and if there is anything else you need we can discuss over on the other issue.
