### ISSUE TITLE
How to set a role in a resource

### ISSUE THREAD

**Issue by kolovrat566** [joniles/mpxj#755]
Hello! I have a question, is it currently possible to add a role to a Resource? (not to an ResourceAssignment), if so, can you please tell me how to do this?

**Comment by joniles** [comment]
Hi! Currently MPXJ doesn't support assignment of roles to resources. I will look at implementing this shortly.

**Comment by joniles** [comment]
I've just added support for role assignments. The changes have been merged and will be available as part of the next MPXJ release.

**Comment by joniles** [comment]
This functionality is now available in 13..5.0.
