### ISSUE TITLE
Missing Successors

### ISSUE THREAD

**Issue by torteliv** [joniles/mpxj#763]
Hi,
We noticed that from version 12.4 the Successor property of the Task can be empty although the Task on the other end of the relation has a Predecessor. It happens when the tasks are in different projects, and one of the projects is not exported (attached is a simple XER example). Is there a way to get the successors?
Thanks!
[MissingSuccessor.zip](https://github.com/user-attachments/files/17472749/MissingSuccessor.zip)

**Comment by joniles** [comment]
I've merged a change which I believe fixes this issue. I'll start preparing a new MPXJ release containing the change now.
