### ISSUE TITLE
Calendar in ruby sdk

### ISSUE THREAD

**Issue by DanLucena** [joniles/mpxj#766]
Hello,

I'm currently using the Ruby SDK and would like to access both the project and task calendars. Is there a method available that allows this? I've attempted to use the task_calendar method but consistently receive nil for all tasks. However, when I use calendar_unique_id, I do get the calendar IDs.

Is there a way to retrieve the task's calendar along with the project's base calendar?

**Comment by joniles** [comment]
Hello! Thanks for opening the issue. Access to calendars is not currently provided via the Ruby interface. I will take a look at adding support early next week.

**Comment by joniles** [comment]
Hi, I've just merged the changes to provide access to calendar data via the ruby gem. These changes will be available as part of the next MPXJ release.
