### ISSUE TITLE
Ruby gem class not found

### ISSUE THREAD

**Issue by DanLucena** [joniles/mpxj#771]
I noticed that the calendar functionality for Ruby has been completed and is scheduled for release in the next version. I wanted to test it early, so I installed the master branch in my project. However, when I try to run the code, I got the following error:

```
Error: Could not find or load main class net.sf.mpxj.ruby.GenerateJson
Caused by: java.lang.ClassNotFoundException: net.sf.mpxj.ruby.GenerateJson
```

**Comment by joniles** [comment]
When the gem is packaged it includes the MPXJ JAR files in the `lib/mpxj` folder. If you find where the latest version of the MPXJ gem is installed on your system, you should be able to locate the JAR files and copy them to the `lib` folder of the master branch you have pulled from git. Alternatively you can manually download the gem to find the JAR files, but you will need to unpack the gem by unzipping two files to get the the `lib/mpxj` folder.
