### ISSUE TITLE
IsPprimary property in resource Primavera

### ISSUE THREAD

**Issue by kolovrat566** [joniles/mpxj#780]
Hello, please tell me how I can add the “Primary” resource property, if this is not possible, could you tell me when you plan to add this property?
Thanks in advance

**Comment by joniles** [comment]
Hi @kolovrat566, if I understand correctly what you need, you'll find the unique ID of the primary resource stored on the task. You can use the `getPrimaryResourceID()` method to retrieve the resource's ID. You can then look up the corresponding `Resource` instance via the container returned by the `ProjectFile` method `getResources()`. I will have a look at this area shortly with a view to making it more convenient to retrieve the `Resource` instance.

**Comment by kolovrat566** [comment]
Sorry please, I meant the parameter in resource assignment
![image](https://github.com/user-attachments/assets/3fa91207-9e88-4b8c-817a-f9669e0ff11c)

**Comment by kolovrat566** [comment]
Thanks a lot
