### ISSUE TITLE
My UniqueId is a Long Number, but Task.uniqueId is Integer. Overflow of Int

### ISSUE THREAD

**Issue by marciojr** [joniles/mpxj#79]
My uniqueId is create by the gantt plugin. So, when i am trying to create a projectFile Task passing the uniqueId, the value of my uniqueId is changed, cause of int overflow. 

long myUniqueId = myTask.getUniqueId(); // 1544482355525 -> long
ProjectFile project = new ProjectFile();
Task task = project.addTask();

task.setUniqueId((int) myUniqueId);

**Comment by joniles** [comment]
Hi! Can you give me a little more detail about where the unique ID comes from, what is the gantt plugin you mention? Thanks!

**Comment by joniles** [comment]
I'm assuming you need the unique identifier of each task to allow the tasks to be linked together correctly in a hierarchy, and to manage predecessors and successors.

Assuming that's the case I'd create a `Map` (or a hash, don't know what language you are using) which stores the DHTMLX unique ID along with a new ID value which you create yourself, so for example:
```
{
  1544533784119: 1
  1544533787689: 2
  ...
}
```
You use your own unique ID value when you are adding tasks to MPXJ, and use the `Map` to perform the conversion when you need to refer to other tasks (e.g. when you build the hierarchy or add predecessors).

If it is useful to you, you can also store the original Unique ID in a custom field (e.g. Text1) so you still have a record of the original value if you need it later.

**Comment by marciojr** [comment]
Thanks. I implemented your abordation and it's working. 

Thanks for the solution.

**Comment by joniles** [comment]
You're welcome!
