### ISSUE TITLE
MPXJ C# - Resource assignment count

### ISSUE THREAD

**Issue by MRaeesi** [joniles/mpxj#82]
Hi,
I have a XER file that I imported to my trial version of Primavera P6. Here is an screen shot of one of the activity's assigned resources:
![image](https://user-images.githubusercontent.com/19883830/50421069-af1f9800-0850-11e9-8949-db781b79bc40.png)
As you see I have 14 resources in Primavera but when I watch it in Visual Studio I have 13 resources:
![image](https://user-images.githubusercontent.com/19883830/50421059-a202a900-0850-11e9-8712-1b96f403293f.png)
Well I guess it has problem with duplicate assignment of same resource(I marked in the first screen shot).

Am I right? Is there any way to get all 14 resources on C# side?

**Comment by joniles** [comment]
Just to follow up on this (and the [related StackOverflow question](https://stackoverflow.com/questions/53921048/mpxj-c-sharp-resource-assignment-count)), MPXJ currently only supports assigning a resource to a task once.
