### ISSUE TITLE
MSPDIWriter.writeProjectProperties() isn't writing comments field

### ISSUE THREAD

**Issue by sardanalokesh** [joniles/mpxj#9]
I am setting the project header comments using ProjectProperties.setComments() method. But, when I write the ProjectFile into xml using MSPDIWriter.write() method, it's not writing the comments field as it's not being taken care of in MSPDIWriter.writeProjectProperties(). Can we fix that?

**Comment by joniles** [comment]
Please see the notes I've added to [this ticket](https://sourceforge.net/p/mpxj/bugs/294/).

**Comment by connecttobn** [comment]
Hi @joniles 
I see that we need to create a project summary task. But can elaborate on that?
I tried to create a task and `setSummary(true)`. But that didn't create any project summary task.
Thanks in advance.

**Comment by joniles** [comment]
I haven't tried this myself, but if you create a project with tasks in a hierarchy like this:
```
Task 1
   Task 1.1
   Task 1.2
   Task 1.3
```
then you manually update the Unique ID attribute of Task 1 to to be zero and export that as an MSPDI file, that might work. We might need to play around with renumbering the ID attributes also. Let me know how you get on.

**Comment by connecttobn** [comment]
<img width="603" alt="Screenshot 2020-10-07 at 11 12 24 PM" src="https://user-images.githubusercontent.com/715128/95367661-a186b580-08f2-11eb-8675-5b3abb0dd596.png">

I tried as below, but no luck :|

```
Task  summaryTask = fProjectFile.addTask();
summaryTask.setSummary(true);
summaryTask.setUniqueID(0);
```

**Comment by joniles** [comment]
Try setting the ID attribute to zero as well.

**Comment by connecttobn** [comment]
Thank you @joniles! 👍 🌮 

```
Task  summaryTask = fProjectFile.addTask();
summaryTask.setSummary(true);
summaryTask.setUniqueID(0);
summaryTask.setID(0);
```
