### ISSUE TITLE
PrimaveraP6 Attribute

### ISSUE THREAD

**Issue by syafik92** [joniles/mpxj#93]
Hi im syafik
How to find this PrimaveraP6 Attribute from .xer file
1.Performance % complete
2.Schedule Performance Index
3.Cost performance index
4.Planned value cost
5.Earned value cost
thank you

**Comment by joniles** [comment]
Unfortunately these values are not available directly from the XER file, and the code isn't present in MPXJ to calculate them. MPXJ provides methods to access these values as they are present in other file formats (MPP in particular caches a lot of these values).

**Comment by syafik92** [comment]
Ok thanks for the info.
